\mainmatter

# The Sacraments in General

For some time past we have been occupied with the subject of the ordinances of the Christian Church. We have discussed the questions connected with the public worship appointed in the Church, the special time set apart and sanctified for worship, and the ministry by means of which the worship of the Church is conducted. All these are outward ordinances which Christ has established in His Church, as parts of that external provision which He has made for the spiritual benefit and advancement of His people, and which He specially makes effectual to that end by the presence and power of His Spirit. All of these ordinances are in themselves, perhaps, and naturally adapted by their inherent character and influence to promote the edification of Christians; but above and beyond this natural or moral efficacy for that end, there is a spiritual blessing connected with them in consequence of the positive appointment of Christ, and the positive promise of His Spirit fulfilled in the right use of them. There may be a natural or moral efficacy in the ordinances of the Church considered in themselves, so that, apart from any other influence, they would, to a certain extent, be beneficial and advantageous in the case of those who used them. But in addition to this, there is a spiritual efficacy in the ordinances of the Church, distinct from the natural, and which is derived from the blessing of Christ and the working of His Spirit in them who by faith make use of them as He has appointed. What this spiritual and supernatural efficacy of outward ordinance exactly is,—what is the measure or amount of the inward benefit to the believer,—in what way and to what extent grace is connected with the external observance,—how beyond the sphere of this natural or moral influence the positive institutions of the Church have a blessing not natively their own,—these are questions which it is impossible for us distinctly to answer. The only wise and fitting reply to such questions is, that we have now reached the region of the supernatural, and that *there* we have no data to guide us beyond what has been revealed. We know, from revelation, that there is a promise of grace annexed to outward ordinances when rightly used; we know that in the external observances Christ meets with His people to bless them and to do them good;—but beyond this we do not know. The character, the measure, the amount of the blessing promised,—how it stands connected with the outward ordinance, and what is the extent and efficacy of the supernatural grace over and above the natural efficacy of the ordinance,—of all this we know nothing, because we have been told nothing. We can distinctly understand, from the analogy of other cases, how the preaching of the Word, viewed as a system of human teaching of truth, and no more, may have a natural tendency to benefit the understanding and the heart. But we do not understand the supernatural efficacy which, over and above the natural, is imparted to it by the presence and the power of the Spirit in the ordinance.

In passing, as we do at this stage, from the non-sacramental to the sacramental ordinances appointed by Christ in His Church, it is of great importance to carry this general principle along with us. A supernatural grace is not peculiar to the Sacraments, although it may be found in them in larger measure than in other ordinances. It is common to all the ordinances which Christ has appointed in His Church. Whatever mystery there may be in the connection which by the promise of Christ has been established between the outward act and the inward blessing,—between the external observance rightly used and the internal grace divinely bestowed,—it is a mystery not belonging to Sacraments alone, but belonging to them in common with all Church ordinances. *There is the supernatural element in them all.* There is that supernatural element connected in some manner with the outward act of the believer in the use of ordinances. There is a mystery in respect to any ordinance, not less than in respect of sacramental ordinances, which we cannot explain. It is, in short, the mystery of the Spirit of God, promised to dwell in the Church, and making every ordinance of the Church, whether sacramental or not, the channel for the conveyance of supernatural grace. If we would rid ourselves of this mystery, we can only do so by denying that the Spirit is present in ordinances at all. "As the wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth,"—so is every ordinance, as well as each person, touched and sanctified of the Holy Ghost. There can be no natural explanation of the supernatural.[^1]

[^1]: [Bannerman, *Inspiration: The infallible Truth and Divine Authority of the Holy Scriptures*, Edin. 1865, pp. 217–228, 472 f.]

What, then, is the character of those special ordinances instituted by Christ in His Church, which are usually denominated sacramental ordinances; and in what respect are they to be distinguished from the other ordinances of the Christian Church, not sacramental? In administering Sacraments, what is the peculiar nature or character of the Church's act; and in what manner does the administration differ from that of common ordinances?

The term *Sacrament*, by which these peculiar ordinances are known, is not of scriptural, but of ecclesiastical origin; and there is some doubt as to the manner in which it came to be applied to these special solemnities of the Church, and to be restricted to the peculiar meaning in which it is now almost universally employed. In classical use, the word "*sacramentum*" is almost always, if not invariably, employed to signify an oath,—more especially the military oath by which a soldier bound himself to obey the officer placed over him. And it has been conjectured that from its classical use it was transferred into the service of the Church, as significant of the obligation which the Christian comes under, in voluntarily participating in the Sacraments, to serve Christ as the Captain of his salvation,—these Sacraments being the characteristic badges or symbols by which the Christian is distinguished from other men. There is a second explanation, advocated by not a few, of the way in which the Latin term Sacrament came to be appropriated to its present ecclesiastical sense. It is the ordinary translation of the Greek word μυστηριον among the ecclesiastical writers of the early ages, and more especially in the Vulgate and other old Latin translations of the Bible. The term Sacrament, according to this supposition, came to be employed to signify the "mysteries" of Christianity,—whether "mystery" is employed to denote a doctrine unknown until it was revealed, or a type or emblem bearing a hidden and secret meaning.[^2] There is some reason to believe that both the Greek term μυστηριον and the Latin translation of it—sacramentum—came at an early period to be applied by the primitive Christians to those special solemnities of their faith, which, although made up of outward and sensible signs or actions, bore in them a secret and spiritual meaning. In one or other of these ways, or perhaps in both, the term "Sacrament" soon came to be restricted in its meaning and application, by ecclesiastical practice, to those outward ordinances of Christianity which signify and seal its most precious and momentous truths. But as the term itself is of Church origin, and not found in Scripture, we must look not to it, but to the descriptions and intimations given in Scripture in regard to the ordinances themselves, for an explanation of their true nature and import.[^3] In what respects, then, do the Scriptures represent the Sacraments of the Church as differing from its other ordinances which are not sacramental? What, according to Scripture, must we regard as the true nature and design of a Sacrament? To this general question we shall direct our attention in the first place, postponing for the present the special consideration of the Sacraments individually. And in endeavouring to ascertain the real nature and design of the Sacraments of the New Testament, we shall be enabled to understand at the same time, and by means of the same inquiry, in what respects they differ from other ordinances not sacramental.

[^2]: Turrettin, *Opera*, loc.\ xix. qu.\ i. 1–6. Halley, *The Sacraments*, Lond. 1844, pp.\ 7–14.
[^3]: ["The Apostle calleth the vocation of the Gentiles a mystery (Eph.\ 3:4–6); the conjunction quhilk is begun here betwixt us and Christ is called a mystery (Eph.\ 5:32), and the Latin Interpreters call it a Sacrament; and, to be short, ye will not find in the Book of God a word mair frequent nor the word mystery. .\ .\ . Alwayis, the word Sacrament is very ambiguous in itself, and there raise about the ambiguity of this word many tragedeis quhilk are not yet ceased, nor will cease while the warld lasts; quher otherwise, gif they had keeped the Apostle's words, and called them, as the Apostle calls them, signs and seals, all this digladiatioun, strife, and contention appearandly had not fallen out. But quher men will be wiser than God, and give names to things beside God, upon the wit of man, quhilk is but mere folly, all this cummer falls out. .\ .\ . The ancient theologues took the word Sacrament in a fourfold manner. Sometimes they took it for the hail action, that is, for the hail ministrie of the elements. Sometimes they took it, not for the hail action, but for the outward things that are used in the action of Baptism and of the Supper; as they took it for the water and sprinkling of it, for the bread and wine, breaking, distributing, and eating thereof. Again, they took it, not for the hail outward things that are used in the action, but only for the material and earthly things,—the elements; as for bread and wine in the Supper, and water in Baptism. After this sort sayeth Augustine: 'The wicked eats the body of our Lord concerning the Sacrament only;' that is, concerning the elements only. (Aug. in *Joann.* Tract\ xxvi.\ 18). Last of all, they took it not only for the elements, but for the things signified by the elements. And after this manner, Irenæus saith, 'that a Sacrament stands of twa things,—the ane earthly, the other heavenly.' (*Adv. Hæres.* lib.\ iv. cap.\ 18.) The ancients, then, taking the word after thir sorts, na question all thir ways they took it rightly."—Robert Bruce, *Sermons on the Sacraments*, p.\ 6, Wodrow Soc. ed. Edin. 1843.]

## Nature and Efficacy of the Sacraments of the New Testament, and Difference between Them and Non-sacramental Ordinances

### The Sacraments of the New Testament are Divine institutions appointed by Christ.

It is the positive institution by Christ that sets these ordinances apart to the religious purpose for which they are intended, that makes them significant of spiritual things, and connects them with the virtue or blessing which they are made instrumental to impart. An express Divine appointment is necessary to constitute a Sacrament. In this respect they are similar to the other ordinances which form part of Church worship. Like them, they can claim Divine authority for their institution; and without this authority they would not be Sacraments at all. No observance not ordained by God can properly form any part of His service; far less can any observance not instituted by Him become a sign of His spiritual grace, or a pledge of a blessing which it depends upon His pleasure to give or to withhold. Hence, that any outward institution may answer to our idea of a Sacrament, it must be a positive appointment of God, and made both a sign and a pledge of spiritual blessings, in consequence of His promise and command. Without this, it would be a mere human ordinance, not only destitute of all real religious significance and efficacy, but profanely mimicking the form and character of a Divine ordinance in the Church. This is the first element that goes to make up a Sacrament, and which it has in common with all other ordinances, really forming a lawful or proper part of Divine worship,—namely, that it be of positive appointment by Christ.

### The Sacraments of the New Testament are sensible signs of spiritual blessings, teaching and representing by outward actions Gospel truths.

The word or promise of God is an appeal to the understanding only; the Sacraments, embodying the same word or promise in outward and sensible signs, form a twofold appeal, *first*, to the senses, and *secondly*, to the understanding. There is Christ in the Word preached; and in the preaching of the Word, Christ is presented directly to the understanding and heart, and the truth addressed singly to the spiritual nature of man. But Christ is also in the Sacrament administered; and, in the administration of the Sacrament, over and above the same truth taught to the understanding and spiritual nature of man, there is the truth taught to the senses, and impressed by sensible signs upon them. There is a striking similarity between the method God has employed in the Sacraments of the New Testament to embody the Word and promises of Christ, and of a *past* salvation, to the view of His people since His departure, and the method that He employed before Christ's coming to embody the Word and promises of a *future* salvation. Under the Old Testament Church, there were, from the very first, two lines of promise and prediction,—both pointing forward to the coming of the Redeemer, running parallel with each other, and throwing mutual light upon each other's announcements. There was the line of promise embodied in verbal revelation, and there was the line of promise embodied in outward representation or type.

These two revelations ran parallel with each other since the first hour that a revelation was given to man in Paradise concerning the future coming of a Saviour. At that time there was a promise embodied in words, that "the woman's seed should bruise the serpent's head, while His own heel was to be bruised;" and side by side with that verbal announcement, there was the same promise embodied in type through means of the ordinance of sacrifice then appointed. There was Christ in the word of promise, and Christ in the sign of promise. When the promise was renewed to Noah, the second father of the human family, we have again the revelation by word, and the revelation by sensible sign; the covenant was repeated in another form, and the bow was set in the cloud as the outward representation of it. Once more: when Abraham was selected by God to be the depositary of a new development of the promise, we have again that promise embodied in words, and also in outward action; we have the special covenant with Abraham revealed in words, and revealed side by side with the word in the external sign of circumcision; and—to mention no further examples of a practice which must be familiar to every reader of the Old Testament—the whole of the Jewish economy was an exemplification of the two parallel lines that run through every economy of God,—the promise in word and the promise in sign revealed together, and throwing mutual light on each other. The typology of the Old Testament shows us God embodying His promises in signs; the revelation of the Old Testament shows us God embodying the same promises in words; and the Sacraments of the New Testament afford, under the Gospel economy, an exemplification of the same great principle.

The connection between the outward action in the Sacraments and the spiritual blessings to which they stand related is not a mere arbitrary one, arising from positive institution: there is a natural analogy or resemblance between the external signs and the things represented; so that, in the Sacraments of the New Testament, as in the types of the Old, our senses are made to minister to our spiritual advantage, and the outward action becomes the image of inward grace. In the Word, Christ is impressed on the understanding; in the Sacraments, Christ is impressed both on the understanding and the senses. They become teaching signs, fitted and designed to address to the believer the very same truths as are addressed to him in the Word; but having this peculiarity, that they speak at the same time and alike to the outward senses and to the inward thought. In this respect the Sacraments differ from other ordinances of the New Testament Church. Prayer and preaching and praise are ordinances that address themselves to the intellectual and spiritual nature of man alone. They are the expressions and utterances of his intellectual and spiritual being in holding intercourse with God; or they are the means fitted to speak to that nature, and that only, in impressing Divine truth upon men. But in those significant and teaching signs, which we call the Sacraments, Christ is embodied in the ordinance in such a manner as to appeal to the twofold being of man, as made up of body and soul, to minister both to the senses and the understanding; and to speak at once to the outward and inward nature of the believer. In addition to Christ in the Word, we have Christ also in the sign, taught as really in the latter way as in the former, and taught with the advantage of being submitted to the eye, and pictured to the outward senses. This, then, is one important difference between the sacramental ordinances of the New Testament Church and those which are not sacramental.

### The Sacraments of the New Testament are federal acts affording a seal or confirmation of the covenant between God and His people.

This is the main and primary characteristic of sacramental ordinances. They constitute a formal testimony to an engagement entered into by two parties through means, not of words, but of speaking and significant actions,—these actions being the visible witnesses to the engagement, and the outward confirmations of its validity. In other words, they become, according to the expression of the apostle in his Epistle to the Romans, when speaking of one of the Sacraments of the Old Testament, visible "*seals*" of the covenant, and of the blessings contained in it.[^4]

[^4]: Rom. iv. 11.

There are not a few examples to be found in the Old Testament Scriptures of covenants between man and man ratified by some outward monument, framed or chosen to attest and confirm the transaction. When Jacob parted from his father-in-law Laban, they made a covenant together, and raised a heap of stones and a pillar, to be a memorial of the transaction, and to serve as a witness on both sides to attest their fidelity to the terms of the covenant. "This heap be a witness, and this pillar be a witness, that I will not pass over this heap to thee, and that thou shalt not pass over this heap and this pillar to me, for harm."[^5] The outward monument or memorial of the covenant entered into between Jacob and Laban was a witness of the engagement, serving to bind the obligation of it more strongly on both parties, and to ratify and confirm, in a formal and significant manner, its validity. And what we find in patriarchal times, we also find, in one shape or other, in every stage of society, some outward sign or significant action being made use of between men to confirm and attest their plighted faith. In addition to the spoken promise or oath, there has been—if not the stone of the times of Jacob—at least the formal signature and solemn deed, and seal attached to the deed, to remain after the verbal engagement, as the witness and ratification of the transaction. Such outward monuments or significant solemnities are intended for the satisfaction of both parties, and to give additional certainty and confirmation to the agreement. And the practice in this respect, which has obtained universally among men, we find to be made use of also by God. There are repeated examples in the Old Testament Scriptures of God ratifying His engagements or covenants with men by means of appropriate signs or solemnities, and making use of these solemnities for the very same purpose that a signed and sealed deed is employed for in the present day, when it attests or confirms a previous engagement, and gives additional security to both parties for the fulfilment of it. That in such a sense the rainbow in the cloud was employed by God, when it became the sign of His covenant with Noah, is very expressly stated by Himself: "And the bow shall be in the cloud; and I will look upon it, that I may remember the everlasting covenant between God and every living creature of all flesh that is upon the earth. And God said unto Noah, This is the token of the covenant, which I have established between me and all flesh that is upon the earth."[^6] In this point of view the bow was a seal, giving validity and additional security to the covenant then made, and serving as a standing witness for the truth of it. In a precisely similar manner, the rite of circumcision was appointed to Abraham for a voucher of the covenant between God and him. The terms of the institution of the rite would themselves lead us to this conclusion, even had they not been interpreted by the inspired commentary of the Apostle Paul in that sense. "And, God said unto Abraham, Thou shalt keep my covenant therefore, thou, and thy seed after thee in their generations. This is my covenant, which ye shall keep, between me and you, and thy seed after thee. Every man-child among you shall be circumcised. And ye shall circumcise the flesh of your foreskin; and it shall be a *token of the covenant* betwixt me and you." And in reference to this transaction, the Apostle Paul expressly says of Abraham: "And he received the sign of circumcision, *a seal of the righteousness of the faith* which he had yet being uncircumcised."[^7] The outward act of circumcision, then, was a witness or a seal of the covenant transaction between God and the patriarch, and thus became a voucher to ratify and confirm the validity of it.

[^5]: Gen. xxxi. 52.
[^6]: Gen. ix. 16, 17.
[^7]: Gen. xvii. 9-11; Rom. iv. 11.

In exact accordance with the practice, universal in one shape or other among men, and expressly sanctioned by the example of God Himself in the Old Testament Church, we affirm that the Sacraments of the New Testament are parts of a federal transaction between the believer and Christ, and visible and outward attestations or vouchers of the covenant entered into between them. In addition to being signs to represent the blessings of the covenant of grace, they are also seals to vouch and ratify and confirm its validity. That the Sacraments of the Christian Church are thus seals of the covenant, appears to be very explicitly asserted, in so far at least as regards the Lord's Supper, in the words of the institution themselves: "*This* cup," said our Lord, "*is the new covenant in my blood, which is shed for you*,"[^8]—language which seems undoubtedly intended to convey the idea that the element used in the Supper was to be the witness of the new covenant,—a visible seal or security to ratify and vouch for it. No doubt that covenant in itself is sufficiently secure without any such confirmation, resting as it does on the word of God. That word alone, and without any further guarantee, is enough. But in condescension to the weakness of our faith, and adapting Himself to the feelings and customs of men, God has done more than give a promise. He has also given a guarantee for the promise,—has vouchsafed to bestow an outward confirmation of His word in the shape of a visible sign, appealing to our senses, and witnessing to the certainty and truth of the covenant. In the case of the Sacraments, God has proceeded on the same principle as is announced by the Apostle Paul in reference to His oath: "God, willing more abundantly to show unto the heirs of promise the immutability of His counsel, confirmed it by an oath; that by two immutable things, in which it was impossible for God to lie, we might have a strong consolation, who have fled for refuge to lay hold upon the hope set before us."[^9] The word of promise was itself enough to warrant and demand the belief of God's people. But more than enough was granted: He has not only said it, but also sworn it. By two immutable things—His word and His oath—is the faith of the believer confirmed. The oath is the guarantee for His word. And more than this still: In the visible seal of the Sacraments God would add another and a third witness,—that at the mouth, not of two, but of three witnesses, His covenant may be established. He has not only given us the guarantee of His word, and confirmed that word by an oath, but also added to both the seal of visible ordinances. There is the word preached to declare the truth of the covenant to the unbelieving heart. More than that,—there is the oath sworn to guarantee it. More than that still,—there is the sign administered in order to vouch for all. Christ in the word, unseen but heard, is ours, if we will receive that word with the hearing ear and the understanding heart. Over and above this, Christ, both seen and heard in the Sacrament, is ours, if we will see with the eye or hear with the ear.[^10]

[^8]: Luke xxii. 20.
[^9]: Heb. vi. 17, 18.
[^10]: ["What mister (need) is there that thir Sacraments and seals suld be annexed to the Word? Seeing we get na new thing in the Sacrament but the same thing quhilk we gat in the simple Word, quherefore is the Sacrament appointed to be hung to the Word? It is true certainly, we get na new thing in the Sacrament, nor we get na other thing in the Sacrament nor we gat in the Word; for *quhat mair walde thou crave nor to get the Son of God*, gif thou get Him weil? Thy heart cannot wish nor imagine a greater gift nor to have the Son of God, quha is King of heaven and earth. And therefore I say, quhat new thing walde thou have? For gif thou get Him, thou gettest all things with Him. Quherefore, then, is the Sacrament appointed? Not to get thee a new thing. I say it is appointed to get thee that same thing *better* nor thou gat it in the Word. The Sacrament is appointed that we may get a better grip of Christ nor we gat in the simple Word; that we may possess Christ in our hearts and minds mair fully and largely nor we did of before in the simple Word; that Christ might have a larger space to make residence in our narrow hearts nor we could have by the hearing of the simple Word. And to possess Christ mair fully it is a better thing; for suppose Christ be ae thing in Himself, yet the better grip thou have of Him thou art the surer of His promise."—Bruce, *Sermons on the Sacraments*, Wodrow Soc. ed. Edin. 1843, p. 28.]

The Sacraments are the outward and sensible testimony and seal of the covenant, added to the word that declares it. This is the grand peculiarity of sacramental ordinances, separating them by a very marked line from ordinances not sacramental. They are federal acts,—seals and vouchers of the covenant between God and the believer. They presuppose and imply a covenant transaction between the man who partakes of them and God; and they are the attestations to and confirmations of that transaction, pledging God by a visible act to fulfil His share of the covenant, and engaging the individual by the same visible act to perform his part in it. Other ordinances, such as the preaching of the Word, presuppose and attest no such personal engagement or federal transaction between the individual and God. Christ in the Word is preached to all, and all are called upon to receive Him; but there is no personal act on the part of the hearer that singles him out as giving or receiving a voucher of his covenant with his Saviour. But when the same individual partakes of the Sacraments, his own personal deed is an act of covenanting with God; and Christ in the ordinance is made his individually, and he is made Christ's by the very action of partaking of the ordinance. He is singled out by his own voluntary act, if he rightly partakes of the ordinance, as giving a voucher for his engagement with Christ; and Christ Himself gives a voucher of His engagement to the individual; and the visible Sacrament is the seal to the personal and mutual engagement. In this respect, as not only signs but seals of the covenant of grace to the individual who in faith partakes of them, the Sacraments are very markedly distinguished from ordinances not sacramental.

### The Sacraments of the New Testament are made means of grace to the individual who rightly partakes of them.

It is carefully to be noted that they presuppose or imply the possession of grace in the case of those who partake of them; but they are also made the means of adding to that grace. They are seals of a covenant already made between the soul and Christ,—attestations of a federal transaction before completed,—confirmations, visible and outward, of engagement between the sinner and his Saviour previously entered into on both sides. They presuppose the existence of grace, else they could not be called seals of it. Just as the signature and seal of some human covenant necessarily presuppose that the covenant exists before they can become vouchers for it, so the seal of God's covenant, affirmed by means of sacramental ordinances, presupposes the existence of that covenant as already subsisting between God and the rightful participator in the ordinance. But although grace exists in the soul before, the Sacraments are made to those who rightly receive them the means of increasing that grace, and communicating yet more of spiritual blessing. They serve to strengthen the faith of those who already believe, and add to the grace of those who previously possessed grace. They become effectual means of imparting saving blessings in addition to those enjoyed before.[^11] In this respect they are similar to the other ordinances which Christ has appointed in His Church, and which by His power and Spirit are made instrumental in advancing the interests of His people. But from the very peculiarity that attaches to their distinctive character, as seals of a personal covenant between God and the believer, Sacraments may reasonably be supposed to be more effectual than non-sacramental ordinances in imparting spiritual blessings. The spiritual virtue of Sacraments is more and greater than other ordinances, just because, from their very nature, they imply more of a personal dealing between the sinner and his Saviour than non-sacramental ordinances necessarily involve.

[^11]: ["The Church has always seen in the Sacraments," says Mr. Liddon in his recent very valuable work on the Divinity of our Lord, "not mere outward signs addressed to the taste or imagination, nor even signs, as Calvinism asserts, which are tokens of grace received independently of them, but signs which, through the power of the promise and Word of Christ, effect what they signify." For this very defective statement of the Calvinistic doctrine of the Sacraments the only authority Mr. Liddon gives is a single secondhand quotation from Cartwright. He then proceeds to contrast with this supposed Calvinistic view the words of the 25th Article: "The Sacraments are *effectual* signs of grace and God's goodwill toward us, by which He doth work invisibly in us;" and the definition of the Church Catechism: "A Sacrament is an outward and visible sign of an inward and spiritual grace given unto us, ordained by Christ Himself as a *means whereby* we receive the same, and a pledge to assure us thereof." *Bampton Lectures*, 1866, p. 721. A very slight reference to the symbolical books or the leading theologians of some of the Calvinistic Churches would of course have shown that all these phrases have been constantly used by them with respect to the Sacraments. The isolated sentence from Cartwright adduced by Hooker, from whom Mr. Liddon takes it, refers to a particular aspect of a particular Sacrament; it was never designed to be a full definition of the efficacy of these ordinances in a typical case. Moreover, the passage in question is just a translation of Calvin, *Inst*. iv. xv. 22. It might as well, therefore, have been brought forward as expressive of *his* whole doctrine on the subject. But Mr. Liddon must surely be aware that Calvm constantly speaks of the Sacraments both of the Old and New Testaments as "*effectual* means of grace," "efficacious instruments," "signs in which God *gives* what He holds out to us," etc. ("non modo salutaria exercitia, et adjumenta pietatis, sed etiam *eficacia gratiae instrumenta*." "*Praestat* igitur vere Deus quicquid signis promittit ac figurat; nec effectu suo carent signa, ut verax et fidelis probetur eorum Author").—*Comment. in* Gal. iv. 9, Col. ii. 17, *Inst*. iv. xiv. 17, etc. Cf. i. *Conf. Helv*. c. 21, ii. c. 21. Conf. Gall. Art. 37, Catech. Gen. v. etc. Some of the expressions in the Church Catechism, indeed, with respect to Baptism seem to Presbyterians to require at least all the explanation which Dean Goode and others have bestowed upon them. And the passage from Martensen about the "communication of Christ's glorified corporeity" in the Lord's Supper, which Mr. Liddon quotes, seemingly as supplementary of the Catechism, would of course be disapproved of by Calvinists generally, although there are statements in the works of Calvin himself which might perhaps be adduced in its favour. Mr. Liddon concludes by observing that, "though there have been and are believers in our Lord's Divinity who deny the realities of sacramental grace, experience appears to show that their position is only a transitional one." There is "a law of fatal declension," which will ultimately, Mr. Liddon thinks, bring all who do not hold the High Church doctrine of the Sacraments to the Socinian position. "Centuries," however, "may intervene between the premisses and the conclusion;" so that the prediction is a singularly safe one. By a precisely similar process of reasoning, Dr. Manning and others are prepared to prove that there is an indissoluble connection between the worship of the virgin and a belief in the Divinity of Christ.—*Engl. and Christend*. p. civ. Faber, *Growth in Holiness*, p. 72.]

What is the nature and extent of the supernatural grace imparted in Sacraments,—in what manner they work so as to impart spiritual benefit to the soul, it is not possible for us to define. As visible seals of God's promises and covenant, we can understand how they are naturally fitted, in the same way as the vouchers of any human engagement or covenant are naturally fitted, to attest and confirm them. But beyond this, all is unknown. The blessing of Christ and the working of His Spirit in Sacraments we cannot understand, any more than we can understand the operation of the same supernatural causes in respect of other ordinances. They have a virtue in them beyond what reason can discover in them, as naturally fitted to serve the purposes both of signs and seals of spiritual things. They have a blessing to the right receiver of them, not their own to give. "They are made effectual means of salvation, not from any virtue in them, or in him that doth administer them, but only by the blessing of Christ, and the working of His Spirit in them who by faith receive them."[^12] In this respect their power and virtue are not more and not less mysterious than those of ordinances non-sacramental.

[^12]: Shorter Catechism, qu. 91.

Such are the general conclusions which a consideration of the nature of the Sacraments of the New Testament lead us to acquiesce in. They are Divine institutions appointed by Christ; they are signs and significant representations of spiritual things; they are seals and vouchers of a federal transaction between God and the worthy receiver of Sacraments; they are the means for applying spiritual grace to the soul. To sum up the discussion in the language of the Shorter Catechism: "A Sacrament is an holy ordinance instituted by Christ, wherein by sensible signs Christ and the benefits of the new covenant are represented, sealed, and applied to believers."[^13]

[^13]: Shorter Catechism, qu. 92. Calvin, *Inst*. lib. iv. cap. xiv. *Consensus Tigurinus* in Niemeyer's *Collectio Confess*. Lipsiae 1840, pp. 192-217, translated in Calvin's *Tracts*, Edin. 1849, vol. ii. pp. 205-244. Turrettin, *Opera*, tom. iii. loc. xix. qu. i.-ix. Cunningham, *Works*, vol. i. pp. 225-291, vol. ii. pp. 201-207, vol. iii. pp. 121-133. Amesius, *Bellarm. Enerv*. tom. iii. lib. i. cap. i. Willison, *Works*, Hetherington's ed. pp. 456 f. Gillespie, *Aaron's Rod Blossoming*, B, iii. chap, xii.-xiv. Mastricht, *Theol. Theoretico-Pract*. tom. ii. lib. vii. cap. 3.

Sacraments and non-sacramental ordinances are like each other in two respects; and in two respects they differ. In the first place, sacramental and non-sacramental ordinances agree in this: first, that they are both positive institutions of Christ; and second, that they are both means of grace to believers. Without a Divine warrant and institution, neither non-sacramental ordinances nor Sacraments could have any place in the worship of God as part of His service; and both are therefore Divine appointments. They are both likewise means of grace to believers,—there being a positive promise attached to the right use of them, and that promise being fulfilled in the bestowment of spiritual blessing in connection with their use. This spiritual benefit, linked to the proper use of ordinances, whether sacramental or not, is over and above and quite distinct from the natural or moral influence such ordinances may have to benefit those who employ them. There is a benefit, for example, which the ordinance of preaching the Word is naturally fitted to impart, because the truth preached is adapted to man's moral and intellectual nature, and so naturally fitted to be of advantage to the hearers. In like manner there is a benefit which Sacraments are naturally fitted to impart, because they are symbolical ordinances or teaching signs; and the truths represented or taught by them are, upon the very same principle, naturally fitted to be of advantage to the receiver. But in both cases there is a blessing distinct from and additional to the natural or moral effect of the Word preached or the Sacraments administered. There is the work of the Spirit making use of Word and Sacrament to reach the understanding and the heart, and to convey to the worthy hearer or worthy receiver a spiritual blessing. And this work of the Spirit, over and above the natural effect of the truth received, is a mystery, both in the case of the ordinance of preaching and the ordinance of the Sacraments; and not, I think, a greater mystery in the one case than in the other.

We do not plead for the Sacraments as means of grace, viewed merely as natural actions and ceremonies apart from the truths which they represent, any more than we would plead for the preaching of the Word being a means of grace, viewed as the mere letter of the Word apart from the meaning of the truth which is uttered. The case of *infant* Baptism, which is, as we shall afterwards see, in some respects exceptional, and not to be taken as completely bringing out the full and primary idea of the Sacrament,[^14] we for the present put aside, postponing it for future consideration. But in the case of adult participation in the Sacraments, we do not plead for these generally as means of grace, when viewed simply as outward acts, and apart from the truths represented, any more than the sound of the Word preached would be a means of grace apart from the intelligent apprehension of it. Through the truths, however, in one case impressed on the hearer by significant words, and in the other case impressed on the participator through significant actions, the Spirit of God *does* operate upon the intellectual and moral nature of man, making both the one ordinance and the other a means of grace. How the Spirit thus operates and imparts of His gracious gifts, we cannot tell in the one instance more than in the other. What is the mode or measure of His communications of a spiritual kind, over and above the natural or outward influence of the truth, we cannot tell. It is His own secret and supernatural work, known and recognised by the believer in the effects wrought on His soul, both in the case of the Word preached and the Sacraments administered, but not to be explained or defined in the manner of working. Let it never be forgotten that there is a mystery not to be explained whenever we get beyond the natural effect of the ordinance, whether sacramental or not, necessarily resulting from the fact that it is an effect of the Spirit, and not of any natural cause. All ordinances, as means of grace, must in that character have something in them mysterious and inexplicable. We cannot rid ourselves of the mysterious by simply ridding ourselves of sacramental ordinances,—as very many in the present day seem to imagine. We can only disconnect all mystery from the ordinances of the Church when we limit their efficacy simply to their natural influence, and deny the influence of the Spirit of God as at all connected with them.

[^14]: Cunningham, *Works*, vol. iii. pp. 144-154.

In the second place, Sacraments differ from ordinances not sacramental in the New Testament Church, in these two things: first, they are sensible signs of spiritual truths; and second, they are seals or vouchers of a federal transaction. In respect that they are sensible exhibitions and significant actions, having a definite meaning in them, Sacraments stand out distinctly marked from other ordinances. Speaking generally, sacramental ordinances are spiritual acts of the mind or soul embodying themselves in outward and sensible actions, in so far as regards the part of the receiver in the ordinance. They are outward representations, by means of certain actions on the part of the worthy participator, of the great fact that he gives himself to Christ according to the terms of the covenant of grace. In partaking of the ordinance, he embodies in the sensible actions of the ordinance a spiritual surrender of himself to Christ, in the manner and upon the terms which Christ has appointed. This is the receiver's part in the ordinance. On the other side, Christ, through the person of the administrator of the ordinance, embodies in the actions of it a picture or representation of a spiritual communication of Himself and all the blessings of His grace to the worthy receiver. Christ, in the Sacrament, and by means of its sensible signs, gives Himself and the benefits of the new covenant, spiritually, although under an outward representation, to the believing participator. The outward signs of the Sacrament exhibit, then, a twofold action: the believer giving himself to Christ in covenant, and Christ giving Himself to the believer in the same covenant. There is a spiritual act on the part of the believer embodied in outward representation,—the act, namely, of his surrendering of himself to Christ in the way and on the terms which Christ has appointed; and there is a spiritual act on the part of Christ embodied in outward representation also,—the act, namely, of Christ with all His precious and unspeakable blessings communicating Himself to the soul of the worthy receiver. There is thus a double significance comprehended in the administration and in the participation of the sacramental ordinance, each of them having a definite and intelligible meaning of its own. In the administration of the Sacrament, Christ makes over Himself and all the benefits of His atonement to the believer, and accepts in return the believer as His. In the participation of the Sacrament on the part of the worthy receiver, he makes over himself to Christ; and receives, in return for his own soul, Christ and His covenant blessings. The double action of the administration and participation of the Sacrament is the embodiment in outward sign of a double spiritual act. There is a mutual intercommunication spiritually of Christ and the believer embodied and represented in action,—a covenant interchangeably exhibited in sensible signs, whereby Christ becomes the believer's, and the believer becomes Christ's. In their being signs of spiritual truths, Sacraments differ in a marked manner from non-sacramental ordinances.

Sacraments differ also from other ordinances in this, that they are seals or vouchers of a federal or covenant transaction. This, after all, is the grand and essential distinction between sacramental and non-sacramental ordinances. As a kind of types, as speaking and teaching signs, they are fitted to express, by the help of significant actions cognisable by the senses, the twofold spiritual act of Christ making over Himself and all His blessings to the believer, and of the believer making over himself with all his poverty and sins to Christ. But they are more than signs of a covenant thus entered into between the two parties,—they are seals and vouchers for the covenant, serving to give confirmation and validity to the engagement, as one never to be broken. In the Sacraments there is a twofold seal, as well as a twofold action, represented. There is a seal on the part of Christ, and there is a seal on the part of the believer. In marvellous condescension to our infirmity and unbelief, Christ has been pleased to add to the promise of His covenant an outward and visible voucher for it,—thereby, as it were, binding Himself doubly to the fulfilment of it, and pledging Himself, both by word and by sign, to implement all its terms. And in the worthy receiving of the Sacrament, the believer gives also a visible voucher for his part of the engagement,—thereby placing himself under new and additional obligations to give himself to Christ, and adding the outward seal to ratify the inward pledge of his heart. The covenant is mutual, and the seal is mutual. Without either part of the covenant transaction, the Sacrament would be incomplete. Withdraw Christ from the ordinance as both entering into covenant with the believer and giving him a seal of it,—take away Christ sealed to the soul in the Sacrament,—and the ordinance is reduced to a bare sign of spiritual blessing, having, perhaps, a certain natural effect by signifying truth, but empty and destitute of all spiritual grace. Or withdraw the believer from the ordinance in so far as he really by means of it gives himself to Christ,—take away the spiritual act by which the worthy participator surrenders his soul to the Saviour through his outward participation of the Sacrament,—and the Sacrament is made to be a charm, in which Christ and grace are communicated apart from the spiritual act or state of the receiver. Abstract from the ordinance the act of Christ covenanting with the believer and giving to the soul Himself and His blessings, and the remaining portion of the ordinance may continue,—the believer may still be accounted as giving himself to Christ in the Sacrament; but in the absence of Christ's act there is no spiritual blessing given in return, and the believer's act of participating in the Sacrament becomes a mere sign of adherence to Christ on his part, and nothing more than a sign.[^15] Again, abstract from the ordinance the act of the believer spiritually covenanting with Christ and giving his soul in faith to the Saviour, and the remaining portion of the ordinance may continue,—Christ may be held as present in the Sacrament giving Himself and His supernatural grace; but in the absence of the receiver's act surrendering his soul in faith to his Saviour, the communication of spiritual grace is degraded to the position of being the result of a charm or talismanic formula,—something effected, *ex opere operato*, apart from the spiritual character or faith of the receiver. It is only when the separate spiritual acts of both parties meet and combine in one transaction, that the covenant is real or complete; or that the ordinance, as a seal of the mutual engagement, is a true and proper Sacrament. As the voucher or seal of a real covenant, spiritually entered into between Christ and the believer through the ordinance, a Sacrament differs, in a very marked and important way, from ordinances not sacramental.

[^15]: ["Quod omnes fere opinantur, hoc ritu, quem Sacramentum appellant, confirmari saltem fidem nostram, ne id quidem verum censeri debet; cum nec ullo sacro testimonio comprobetur, nec ulla ratio sit cur id fieri possit. Quomodo enim potest nos in fide confirmare id *quod nos ipsi facimus, quodque, licet a Domino institutum, opus tamen nostrum est?*"—Faustus Socinus, *De Caena Dom, Tract. Brev*. Racovian Catechism, 1609, p. 144 f.]

## Unscriptural Or Defective Views Of The Sacraments

The principles which I have laid down in regard to the nature of Sacraments, and in regard to the difference between them and ordinances not sacramental, stand opposed to the views of two parties holding extreme positions on either side of this question. There is one party who deny the grand and characteristic distinction between sacramental and other ordinances already enunciated, and hold that the Sacraments have no virtue except as badges of a Christian profession, and signs of spiritual truths. There is another party holding opinions on the subject admitting of various modifications, but agreeing in this, that they ascribe a high spiritual efficacy to the Sacraments apart from the faith or spiritual act of the receiver. By the first party the views of the Sacraments already stated by me are held to be erroneous in the way of attributing to them a greater virtue than actually belongs to them. By the second party these views are regarded as defective in the way of ascribing to Sacraments a less virtue than really belongs to them. Let us endeavour briefly and generally to estimate the merits and truth of the principles adopted by these two parties,—reserving until a future stage in our discussions the more particular examination of their theories, in their application to the Sacraments of the New Testament individually.

### Signs, and no more than signs, of spiritual things

The Sacraments of the New Testament are regarded by one party as signs, and no more than signs, of spiritual things,—symbolical actions fitted to represent, and impress upon the minds of men, Gospel truths. The Socinian party have made this doctrine peculiarly their own. According to their views, a federal transaction between the believer and Christ founded on His atonement is no part of the Gospel system at all; and hence the Sacraments of the New Testament can be no seals appointed and designed to ratify such a covenant. The Socinian doctrine concerning the nature of the Sacraments allows to them no more than a twofold object and design. They are not essentially distinct from other ordinances, as set apart by themselves to be the seals of the one great covenant between the believer and Christ, at his entrance into the Church at first, and from time to time afterwards, as occasion justifies or demands. But in the first place, they are signs in which something external and material is used to express what is spiritual and invisible,—the only virtue belonging to them being what they are naturally calculated to effect, as memorials, or illustrations, or exhibitions of the important facts and truths of the Gospel; and in the second place, the Sacraments are solemn pledges of discipleship on the part of those who receive them, discriminating them from other men, and forming a public profession of or testimony to their faith as Christians. These are the two grand objects, which, according to the Socinian view, the Sacraments were intended to serve; and such, according to their theory, is the nature of the ordinance.

The same system in substance, making, as it does, Sacraments entirely or essentially teaching and symbolical signs, has been adopted by many who disown the tenets of Socinianism in regard to the Gospel system generally. The theory of the Sacraments now described has been and is held by not a few in the Church of England of somewhat latitudinarian views,—the representative of such, as a class, being Bishop Hoadly. It is avowed and advocated in the present day by a very large proportion of the Independent body, who count the Sacraments to be no more than symbolical institutions, and who are ably represented by Dr. Halley in his work, entitled, *An Inquiry into the Nature of the Symbolic Institutions of the Christian Religion, usually called the Sacraments*. The single difference between the Socinian doctrine, as maintained by Socinians in the present day, and the Independent doctrine, as maintained by Dr. Halley and others, is probably this, that Socinians limit the efficacy of the Sacraments to the natural or moral power that belongs to them as signs of Gospel truth, while Independents may admit that beyond the natural and moral power of the ordinance, as symbolical of truth, the Spirit of God makes use of them in representing truth to the mind. Let Dr. Halley speak his own views as they are generally held by English Independents. "The opinion we propose is, that the Sacraments are significant rites,—emblems of Divine truth,—sacred signs of the evangelical doctrine,—designed to illustrate, to enforce, or to commemorate the great and most important truths of the Gospel. Baptism, we believe, is the sign of purification, on being admitted into the kingdom of Christ, but neither the cause nor the seal of it; the Lord's Supper the commemoration of the death of Christ, the symbol of its propitiatory character, but not the assurance of our personal interest in its saving benefits. The truth exhibited in the Sacraments, just as when it is propounded in words, may be the means of the communication of Divine grace; but then the evangelical doctrine and not the Sacrament, the truth and not the symbol, the spirit and not the letter, gives life and sanctity to the recipient, as it may even to a spectator."[^16] According to this theory, it is the truth signified in the Sacrament—and not, over and above that, the Sacrament itself as a seal—that possesses any spiritual virtue; and that virtue may be, according to Socinians, the natural influence of the truth on the mind,—or, according to Independents, that natural influence, with the addition of the power communicated through the truth by the Spirit.

[^16]: Halley, *The Sacraments: an Inquiry*, etc. Lond. 1844, vol. i. p. 94 f.

Now, in reference to this view of the Sacraments, it is necessary to bear in mind that there is no dispute as to the fact that sacramental ordinances are symbolical,—signs fitted to represent and to teach Gospel truths. Further, there is no dispute as to the fact, acknowledged by some of the advocates of this theory, that in so far as they teach or convey truth to the mind, they may be made the means of the communication of Divine grace, in the same manner very much as when the truth is propounded in words.[^17] But the point in debate is, whether the Sacraments are not more than signs, and more than merely symbolical representations of truth. We hold that they are. We contend that, in addition to being signs, they are also seals,—the visible vouchers of a federal transaction between Christ and the believer who partakes of His Sacraments,—the outward pledges speaking to the eye and the senses of the completed covenant by which Christ becomes the believer's, and the believer becomes Christ's. And further, we contend that, as seals, they are made a means of grace more powerful and efficacious than simply as signs of truth.

[^17]: ["Es geschah in dem Zeitpunkte der Reformation, aber nicht zum ersten Male, dass die hypermystische oder zauberische Vorstellung den entgegengesetzten Fehler, die Behauptung des *signum nudum* oder des blossen Bekenntnisszeichens, hervorrief. Gegen diejenige Kirche, die im Dienste der Verwandlungslehre und des *opus operatum* die symbolische Natur des Sacraments verleugnete und zerstörte, hatte die sogenannte Ketzerei allezeit Recht, zunächst nur wieder das Daseyn des Symbols und die Bedeutung zu behaupten. Diejenige Kirche, die des Sacramentes Wirkung und Wesen vom lebendigen Worte und Glauben, den Sohn vom Geiste losgerissen hatte, durfte einen Gegner nie Lügen strafen oder des Unchristenthums zeihen, der der Gemeinschaft des Erlösers durch die Speise des Wortes als durch die rechte Assimilation mit seinem Leben theilhaft zu werden hoffte, und sich des Sacramentes nur noch als eines Zeichens dieser Gemeinschaft, oder auch dieses Zeichens nicht mehr bediente weil es so sehr vom Wesen abgelenkt und etwa nur habe bei noch nicht ganz befestigter Wirksamkeit des Wortes einem anfänglichen Bedürfnisse dienen sollen." (This is still the position of the Quakers as expounded by Barclay in his *Apology*.) "*Blosse Gebetschristen*, Messalianer und dergleichen, *sind nicht weniger Christen als blosse Sacramentschristen; blosse Symboliker stehen sich nicht schlechter mit der Quelle des Lebens als die Hierurgen die den Leib Christi conficiren*. Diese sind am Ende des verschwindenden Christenthums angelangt, jene stehen am Wiederanfange der Entwickelung."—Nitzsch, *prot. Beant. der Symb. Möhlers*, Hamburg 1835, p. 162.]

The arguments urged by Dr. Halley against this additional office and virtue attributed to Sacraments as more than signs, and as the seals of a federal engagement between the worthy recipient and Christ, are the two following, as stated in his own words: "First, The ceremonial institutes of preceding dispensations, the Sacraments of the patriarchal and Jewish Church, correspond only with the view which we take of the Christian Sacraments as sacred signs of Divine truth. Second, The Sacraments considered as the causes or the means, or even the seals of converting or regenerating grace, stand opposed to the great Protestant doctrine of justification by faith without works."[^18] We shall very briefly examine each of these two objections to the view which we have announced. And we do this all the more readily, as it will afford us the better opportunity of bringing out our own principles in contrast with those embodied in the Independent theory of the Sacraments.

[^18]: Halley, p. 95.

1*st*, Dr. Halley alleges, against the ascription to the New Testament Sacraments of the character of seals, that the ceremonial institutes of preceding dispensations, the Sacraments of the patriarchal and Jewish Church, correspond only with the views which he advocates of the Christian Sacraments as exclusively signs of Divine truth. Perhaps there never was a more unfortunate or unfounded assertion. "One passage of St. Paul," says Dr. Halley, "will establish this proposition."[^19] And the single passage which is to bear the weight of the whole argument is the following one from the Epistle to the Romans: "He is not a Jew which is one outwardly; neither is that circumcision which is outward in the flesh. But he is a Jew which is one inwardly; and circumcision is that of the heart, in the spirit, and not in the letter; whose praise is not of men, but of God."[^20] This is the solitary passage quoted to prove the broad and general assertion, that the Sacraments of the patriarchal and Jewish Church afford no precedent or example of Sacraments as seals, but only of Sacraments as signs. The verses quoted plainly amount to nothing more than a statement of the difference between what the apostle calls circumcision outwardly and circumcision inwardly, the external rite and the internal grace, and a declaration that a man might have the outward rite, and not the inward grace. The apostle does not say, and cannot, except by a violent misapplication of his words, be made to say, that *in the case of the man who has both the outward and inward circumcision*, the external rite may not be the visible seal of the spiritual grace. The very opposite of this the same apostle in the very same Epistle undeniably asserts. In language as plain as he could possibly select or employ, Paul affirms that in the case of Abraham, who had the inward grace, the outward rite of circumcision was a seal to him of that grace. "Abraham," says the apostle, "received the sign of circumcision, a *seal* of the righteousness of the faith which he had yet being uncircumcised."[^21] And how is it that Dr. Halley gets rid of this express assertion of the apostle, standing as it does in explicit contradiction to his general averment that the Sacraments of the Jewish Church were signs and not seals? He admits that to Abraham personally and individually circumcision was a seal, and not merely a sign. But by a strange misapprehension of the doctrine of his opponents, he argues that it could not be a seal of faith to others of Abraham's family or countrymen who had not his faith. "Although," says Dr. Halley, "to him circumcision was the seal of faith, it could not have been so to his posterity." "Was it," he asks, "was it, in this sense, a seal of the righteousness which they had, an approval of their faith, to the men of his clan, or to Ishmael, or to the infants of his household, or to any of his posterity in subsequent ages?"[^22] The answer to such a question is abundantly obvious. If the men of Abraham's clan had not faith, if Ishmael had not faith, circumcision could have been no seal of faith to them. The outward rite could not be a seal of the inward grace, when the latter did not exist. It could not be a seal of a spiritual covenant between them and God which had not been entered into. I do not stop to consider the question of whether or not circumcision is to be accounted, even in such a case, the seal to such individuals of the outward blessings promised to them, as Jews, by God, as the rightful King of Israel as a nation; but, as a seal of a spiritual covenant, it of course could not be a seal at all to those who were not parties to the covenant,—while it was a seal, according to the explicit assertion of the apostle, to those who were. The very express statement of Paul cannot be evaded, but fully bears out the assertion that the Sacraments of the Jewish Church were not signs alone, but seals of a spiritual covenant to those who were really parties to the covenant. "Abraham received the sign of circumcision, a *seal* of the righteousness of the faith which he *had*."

[^19]: Ibid. p. 96.

[^20]: Rom. ii. 28, 29.

[^21]: Rom. iv. 11.

[^22]: Halley, p. 100.

2*d*, Dr. Halley alleges that the Sacraments, if they are considered as the cause or the means, or even the seals of spiritual and saving grace, would be opposed to the great Protestant doctrine of justification by faith without works. Now it is readily admitted, that if Sacraments are regarded as the causes or means of justification, they are utterly inconsistent with the Protestant doctrine of justification by faith alone; and in this point of view the objection is true and unanswerable when directed against some of those theories of the Sacraments which we may be called upon to consider by and by. But it is denied that the objection is true when directed against the theory of the Sacraments which maintains that they are not causes and not means of justification, but seals of it and of other blessings of the new covenant. The Sacraments as seals, not causes of justification, cannot interfere with the doctrine of justification by faith, for this plain reason, that before the seal is added, the justification is completed. The seal implied in the Sacrament presupposes justification, and does not directly or instrumentally cause it; the seal is a voucher given to the believer that he is justified already, and not a means or a cause of procuring justification for him. Justification exists before the seal that attests it is bestowed. The believer has previously been "justified by faith without the works of the law," ere the Sacrament of which he partakes can affix the visible seal to his justification. All this is abundantly obvious; and the objection of Independents, that the doctrine of the Sacraments as personal seals is opposed to the principle of justification by faith, is wholly without foundation. That the Sacraments are a means of grace additional to what the believer possessed before his participation in them, it is not necessary to deny, but rather proper strongly to assert.[^23] In entering into a personal covenant with Christ through particiption in the Sacraments, or in renewing that covenant from time to time, the faith of the believer is called forth and brought into exercise in the very act of participation, and by the aids to faith which the ordinance affords. And in answer to this faith so exercised and elicited, there is an increase of grace given to the worthy recipient above and beyond what he had before. The faith of the believer, called into exercise in partaking of the ordinance and by means of it, is met by the bestowment of corresponding grace. But it is never to be forgotten that the Sacraments presuppose the existence of grace, however they may give to him that already has it more abundantly. They presuppose, and beforehand require, that a man is justified by faith before they give their seal to his justification.

[^23]: ["Das Gläubigste, so zu sagen, am sacramentlichen christlichen Gemeinglauben ist doch wohl dieses: je mehr das Sacrament mit voller Empfänglichkeit genossen wird, desto weniger ist es blosses Zeichen, oder blosses Unterpfand der Lebensmittheilung Christi, desto mehr diese Mittheilung selbst. Das Sacrament ist Leiter, Kanal der Gnade, wie der römische Katechismus sich ausdrückt. Bis auf diesen Punkt wird der Sacramentsbegriff—ich will zugeben unter sehr verschiedenen Bedingungen (from those of the Romanist theory)—durch das in dieser Hinsicht ganz ungetheilte Bekenntniss der Protestanten gesteigert. . . . Der protestantische Begriff des Siegels oder Pfandes ist weit entfernt die *collative* Kraft des Sacraments zu schwächen; er gestattet sogar die mystische Verknüpfung der Elemente des Sacraments mit der *res signata et exhibenda; signa et res significatae sacramentaliter conjunguntur* (*Conf. Helv. post*. xix.). *Bezeichnung, Besiegelung, Darreichung* der Gnade Christi vereinigen sich im Sacramente. (*Decl. Thorun. De Sacr*. 1, 7)."—Nitzsch, *prot. Beant, der Symb. Möhlers*, Hamburg 1835, p. 151 f.]

There is no ground, then, in Scripture, but the very opposite, for asserting that the Sacraments are no more than signs or symbolical actions, as held by Dr. Halley and those whom on this question he represents. The fundamental error involved in the views now adverted to is, the denial of Christ's part in the federal transaction involved in a Sacrament. Independents overlook *His* department of the work in the engagement entered into through means of the act of receiving the Sacraments; and in the absence of the act of Christ giving Himself and all His spiritual blessings to the believer in the ordinance, the act of the recipient is not met by the grace that Christ confers, but is reduced to a mere significant dedication of himself to the Saviour unconnected with any grace at all. Take away Christ from the ordinance as present there, to covenant with the believer, actually giving Himself and His blessings spiritually through means of the outward ordinance, in answer to the faith of the believer giving himself to Christ through the same ordinance, and the Sacrament is evacuated of all spiritual grace; the act of the receiver becomes a mere expressive sign of what he is willing to do in the way of dedicating himself to Christ; but not an actual dedication, accomplished through means of a covenant *then* and *there* renewed, by which the believer becomes Christ's, and Christ becomes the believer's. The principle of the Independents in regard to the Sacraments cuts the Sacrament, as it were, in twain, and puts asunder what God has joined. It leaves to the believer his part in the transaction, in so far as he employs the Sacrament as a sign of his dedication to Christ; but it takes away Christ's part in the transaction, in so far as He meets with the believer and enters into covenant with him,—accepting the believer as His, and giving Himself to the soul in return. Severed from Christ in the ordinance, and from the covenant with His people into which Christ there enters, the act of the recipient can be no more than an expressive sign, or convenient profession of faith, unconnected with true and proper sacramental grace.

### Effectual to impart justifying and saving grace directly

The Sacraments of the New Testament are regarded by another party as in themselves, and by reason of the virtue that belongs to them, and not through the instrumentality of the faith or the Spirit in the heart of the recipient, effectual to impart justifying and saving grace directly, in all cases where it is not resisted by an unworthy reception of the ordinance. This general opinion may be held under various modifications; but all of them are opposed to the doctrine I have already laid down, that the Sacraments are seals of a justifying and saving grace already enjoyed by the recipient, and not intended for the conversion of sinners; and that they become means of grace only in so far as the Spirit of God, by the aid of the ordinance, calls forth the faith of the recipient, and no further.

The doctrine of the efficacy of Sacraments, directly and immediately of themselves, and not indirectly and mediately through the faith of the receiver, and through the Spirit in the receiver, is advocated in its extreme and unmodified form by the Church of Rome. According to that Church, these ordinances, as outward and material rites, become, after certain words of institution pronounced by the priest, possessed of a sacramental virtue, which is conveyed infallibly to the soul of the person who receives them, on *two* conditions, which are necessary to justifying and spiritual grace being really imparted. *First*, on the side of the priest who pronounces the words of institution, there is required, as a condition of the supernatural grace being imparted, that he have the intention to make the Sacrament and confer it; for without this, the outward matter of the ordinance would remain mere matter, and have no sacramental character or virtue. And *second*, on the side of the recipient of the ordinance, it is required that he be free from any of those sins which, in the language of Popery, are called "mortal," and which, when contracted and not removed, would resist the operation of the sacramental virtue, and prevent his soul receiving spiritual grace. But when these two conditions are present,—when the priest intends to consecrate and dispense the ordinance, and the recipient is not barred from the reception of its virtue by mortal sin,—such is the efficacy of the Sacrament in itself, and directly, that it infallibly communicates to the partaker of it justifying and saving grace. The doctrine of the Church of Rome is very distinctly brought out in the canons of the Council of Trent, and also in her Catechism. "If any," says the 11th canon concerning the Sacraments in general, "if any shall say that there is not required in the ministers, when they make and confer the Sacraments, at least the intention of doing what the Church does, let him be accursed." "If any shall say that the Sacraments of the New Law do not contain the grace of which they are the signs, or that they do not confer that grace on those who place no obstacle in the way, as if they were only outward signs of grace or justification already received by faith, and certain badges of the Christian profession, by which believers are distinguished from infidels, let him be accursed." "If any shall say that grace is not conferred by the Sacraments of the New Law, *ex opere operato*, but that faith in the Divine promise alone avails to secure grace, let him be accursed."[^24] According to this doctrine, then, Sacraments impart grace, not through the channel of the faith of the receiver, and not in dependence in any way on his spiritual act, but immediately and directly from themselves, "*ex opere operato*." This last expression is to be interpreted in connection with the distinction drawn by the Church of Rome between the Sacraments of the Old and New Testament Churches. The Sacraments of the Gospel Church are superior in efficacy to those under the law, in the Popish theory, because the former, or the New Testament Sacraments, work grace independently of the spiritual disposition or act of the recipient; whereas the latter, or Old Testament Sacraments, were dependent on the spiritual disposition or act of the receiver of them. The "*opus operatum*" of the New Testament Sacraments, or the virtue they have by their own act, apart from the spiritual state of the recipient, is contrasted with the "*opus operantis*" in the Old Testament Sacraments, or the virtue which they had, not in themselves, or in their own operation, but only in connection with the spiritual act of the partaker. According to the proper theory of the Church of Rome, the Sacraments of the New Testament impart grace *ex opere operato*, or from their own intrinsic virtue and direct act on the soul of him who receives them.[^25]

[^24]: *Concil. Trident. Canones et Decreta*, Sess. vii. *De Sacr. in Gen.*, Can. vi. viii. xi. [Compare Möhler's statement of the Roman Catholic theory of the Sacraments (*Symb*. 6te Aufl. pp. 253-258). It is worthy of remark, that that acute and dexterous controversialist, in his own exposition of the doctrine, passes over in utter silence the very remarkable and important element of the priest's intention, as defined at Trent,—the sole reference to it being in a quotation from Bellarmine given in a note (p. 256). Nitzsch's remarks on the significance of the point thus ignored, are worth quoting: "The demand of an *intention* on the part of the priest in order to the Sacrament being savingly effectual, or effectual at all, met opposition among the Romish theologians, both at and before the Council of Trent. At one time the danger was pleaded incurred by the baptized or the absolved, who might now so easily miss obtaining grace, or be left in uncertainty about it; at another, the much greater concession already made, that unbelief, or even mortal sin on the part of the priest, did not destroy the efficacy of the priestly act. On these grounds, the Council saw themselves compelled to restrict the demand as much as possible; it asserted itself, notwithstanding. Sess. vii. Can. 11: 'Si quis dixerit in ministris, dum Sacramenta conficiunt et conferunt, non requiri intentionem saltem faciendi quod facit Ecclesia, anathema sit,' with good reason, as is easily to be seen. For if, as Can. x. decided, the private Christian cannot make or confer most of the Sacraments,—if the supernatural qualification of the priest, although a '*gratia gratis data*,' and not '*gratum faciens*,' still was of the essence of the sacramental dispensation,—while, on the other hand, no '*bonus motus*' of the recipient was necessary for the reception of the grace, nay, in the case of private mass, no recipient at all, in the case of infant Baptism, no conscious recipient, was needed,—then, should there be an *entire* absence of harmony between the mental state of the priest and the design of the transaction, there would be absolutely nothing left but the bare, mechanical, accidental, external act; and from this hardly a single believer would have expected any blessing whatsoever. The worth of the words of institution and promise, as appropriated by faith, had already been sacrificed to the worth of the '*opus;*' so had the dignity of the congregation to the dignity of the priest: hence arose great perils and perplexities, if now, after all, the worth of the words should be allowed to stand without moral desert on the part of the priest. The morally indifferent supernatural qualification of the priest must therefore now receive at least a psychological quickening, and the co-operation of the mental state of the priest be thus brought in to give the requisite support to a transaction otherwise bereft of all substance and security. They resigned themselves, accordingly, to the lesser perplexity. The doctrine of the '*intentio ministri*' is a reinforcement to the doctrine of the '*opus operatum*,' which yields at the same time various advantages of another sort; and the latter dogma is again explained and supported by the notion of the 'not interposed hindrance.'" *Prot. Beant*. Hamburg 1835, p. 154. Gerhard, *Loci*, xviii. 31-38, ed. Preuss. tom. iv. pp. 151-158.]

[^25]: The statement that Papists hold the Sacraments to be efficacious of themselves, apart from the spiritual condition of the recipient, is often met—especially by English Romanists—with a flat denial. And on this ground. They hold that many elements are, in point of fact, present in every case in which the Sacraments are efficacious; some of these elements are connected with the state of the recipient,—such as a desire to receive the ordinance,—and others with the working of God. Thus Bellarmine objects to Calvin's stating the point in debate to be, not as to grace being conferred in the Sacraments, but only "whether God works in them by His own proper, and, so to speak, intrinsic virtue, or whether He resigns His place to the external signs."—*Inst*. lib. iv. c. xiv. 17. (See next note.) Any Romanist, however, who has the slightest regard for the authoritative declarations of his Church, can be fixed down conclusively to this position, that, whatever other elements may, in point of fact, be present, the immediate, efficient, instrumental cause of the grace invariably conveyed to all "qui non ponunt obicem" is "the outward action called a Sacrament," and nothing else. See Turrettin's masterly treatment of this point, *Opera*, loc. xix. Qu. viii. 2-6. Cunningham, *Works*, vol. iii. pp. 124-139. Hodge, *Princeton Essays and Reviews*, New York 1857, pp. 370 f., 388.

This doctrine of the inherent power of Sacraments in themselves to impart grace, held by the Church of Rome, is also the system maintained, although with some important modifications, by another party beyond the pale of that Church, the representatives of which, at the present day, are to be found in the High Churchmen of the English Establishment. The doctrine of the High Church party in the English Establishment in regard to the Sacraments differs indeed in *two* important particulars from the full and unmodified development of it found in the Popish system; but in other respects it is substantially the same,—equally implying the inherent power of Sacraments to impart grace, not through the spiritual act of the recipient, but apart from and independently of it. The advocates of High Church principles in the Church of England generally—although there is a numerous and increasing section of them who in this respect approximate more nearly to Rome—generally reject the Popish doctrines,—*first*, of the *opus operatum*, and *second*, of the necessity for the intention of the priest in the Sacrament. They deny that the Sacraments have any immediate physical influence upon the soul, by the very act of outwardly participating in them,—such as is implied in the *opus operatum* of the Church of Rome; and they deny, further, that the intention of the priest to make and confer the Sacrament is a necessary condition of it, without which it could impart no grace. These two elements in the Popish theory of sacramental ordinances are rejected, generally speaking, by the High Church disciples of the English Establishment, although instances are not awanting—and they seem to be multiplying of late—of both these monstrous pretensions being, in a certain sense, maintained by them. But they agree with the Romish Church in the grand and fundamental principle which belongs to its doctrine of the Sacraments,—namely, that they communicate grace from the sacramental virtue that resides in themselves,—or, as some prefer to put it, that invariably accompanies them by Christ's appointment,[^26]—and by their own immediate influence on the soul, and not instrumentally by the operation of the Spirit of God on the worthy recipient and through the medium of his faith. This is the characteristic principle that is common both to the Popish and the High Church theories of Sacraments. Both these parties hold that there is something in or connected with the ordinance which directly and immediately does the work of grace upon the soul; and not merely indirectly and mediately through the Spirit of God working on the soul, and the faith of the soul working in return. The Church of Rome ascribes this efficacy of the ordinances to the *opus operatum* of the Sacraments, and the act and intention of the priest in consecrating them. The High Churchmen of the English Establishment usually reject both of these doctrines as laid down by the Council of Trent, and ascribe this efficacy of the ordinances to the deposit of spiritual grace which Christ has communicated to the Church, and connected with the Sacraments, and given them the power to impart. But the High Churchmen of Rome and the High Churchmen of England agree equally in this, that there are in the Sacraments an efficacy and power to impart grace of themselves, directly and immediately, to the soul of the recipient; and that they are not merely aids or instruments for bringing the recipient into direct and immediate communication with Christ to receive grace from Him.[^27]

[^26]: In, cum, or sub Sacramento. ["It is to be observed," says Bellarmine, "that the dispute is not about the *mode* in which Sacraments are causes of justification, *i.e*. whether the effect is produced by physical or moral means; and again, if the influence be of a physical sort, whether it be by some inherent quality, or by the simple will of God; for these points do not belong to the question of faith; but only in general, whether the Sacraments are true and proper causes of justification; so that it truly follows, from a man's being baptized, that he is justified."—*Disputationes*, tom. iii. lib. ii. cap. i.]

[^27]: [Goode, *Nature of Christ's Presence in the Eucharist*, Lond. 1856, vol. i. pp. vi. 11-55. Cunningham, *Works*, vol. i. pp. 233-237.]

Although both the Canons and Catechism of the Council of Trent lay down, to all appearance, expressly and undeniably the doctrine that there is a physical virtue in Sacraments, whereby they operate upon the recipient, yet there are not awanting doctors of the Romish Church who are anxious to soften down the dogma of the *opus operatum*, and to explain it in the sense of a moral and spiritual, and not a physical virtue, residing in the ordinance. And in this modified form of it, the Romish doctrine of the Sacraments—apart from the necessity of the priest's intention—approximates very closely to the High Church theory entertained by many in the Church of England. That theory maintains the doctrine of not a physical but a spiritual virtue deposited and residing in the Sacrament, which operates universally, not through the faith or spiritual act of the recipient, but directly and immediately through the act of participation in the outward ordinance. This, in fact, is no more than part of the general doctrine that the Church is the grand storehouse of grace to man, and not Christ Himself; and that it is by communication with the Church, and not by direct communication with Christ, that the soul is made partaker of that grace. The Sacraments, as the chief medium through which the Church communicates of its stores of spiritual blessings, are the efficient instruments for imparting grace directly to the recipient.

Now, there is one preliminary remark which, in proceeding to estimate the value and truth of such principles in regard to the Sacraments, it is necessary to bear in mind. It is not denied, but, on the contrary, strongly maintained and asserted, that the Sacraments are means of grace. To the believer who uses them aright, they are made the means of conveying spiritual blessings. In regard to this, there is no controversy between the opponents and the advocates of High Church views of the Sacraments, whether Popish or Tractarian. But the question in dispute is, whether the Sacraments become effectual, from a virtue in themselves, or in the priest that consecrates them, or only by the work or the Spirit and the faith of the recipient? That the faith of the believer is called forth and exercised in the ordinance, and that through this faith he receives grace additional to what he enjoyed before, we do not dispute, but, on the contrary, strenuously maintain. That the spiritual act of the believer in the ordinance, when in faith he gives himself to his Saviour, is met by the spiritual act of Christ in the ordinance, when in return He gives Himself and His grace to the believer, is a doctrine at all times to be asserted and vindicated. That the faith of the recipient, in the act of committing and engaging himself to Christ, through means of the ordinance, is a faith unto which Christ is given in return, we would constantly affirm; and in this sense, and in this way, the Sacraments become means or channels or instruments whereby grace is given and conveyed. But they are no means of grace except through the faith of the recipient, and in consequence of his own spiritual state and act. There is no inherent power in the ordinance itself to confer blessing, apart from the faith of the participator, and except through the channel of that faith. There is no deposit of power—whether, with the Church of Rome, we deem it physical and *ex opere operato*, or whether, with Tractarians and High Churchmen, we call it spiritual—in the Sacraments themselves to influence the mind of him who receives them. They have no virtue of themselves, apart from the work of Christ through His Spirit on the one side, and the spiritual act of the recipient through his faith on the other side. In the language of Amesius, in his admirable reply to Bellarmine, Sacraments have no power "efficere gratiam immediate, sed mediante Spiritu Dei et fide."[^28]

[^28]: Amesius, *Bellarm. Enerv*. Amsterdam 1658, tom. iii. lib. i. cap. v. p. 22. "In the following sentences of the *Declaration of Thorn*," observes Nitzsch, "all Protestants agree: 'Sacraments are outward and visible signs, seals, and testimonials of the Divine will, instituted by God Himself, by the combination of Word and element, in order to seal and exhibit, through means of these signs, the invisible grace which is promised in the Word of the covenant. It is obvious that we by no means make them bare signs, empty and inefficacious, or mere badges of outward profession, since, besides their mystical significance, according to the Divine institution, we attribute to the Sacraments a sure sealing of God's promises, and at the same time a true and infallible exhibition of the things promised, in the way suited and proper to them, to be received by a living faith.'" (Niemeyer, p. 680.) *Prot. Beant. der Symb. Möhler's*, Hamburg 1835, p. 175. Bruce, *Serm. on the Sacr*. Wodrow Soc. ed. Edin. 1843, p. 10 f. Calvin, *Antidote to Council of Trent*, Sess. vii. Can. ii. iv.-vi. *Tracts*, vol. iii. Calvin Transl. Soc. Edin. 1851, pp. 172-175.]

Has the Church, then, ordinances for its administration and use which, either by the original appointment of Christ, or by deposit of grace from Christ, have in themselves virtue to impart spiritual blessing through the administration of them alone? Or has the Church ordinances for its administration and use which have no virtue in themselves to communicate grace, except in connection with the faith of the receiver, and the blessing imparted by the Spirit? Are the Sacraments of the New Testament themselves a quickening power in the soul, apart from the faith or spiritual act of the participator,—the original deposit of grace committed to them being still retained, and still communicable through their administration, and that alone? Or are these Sacraments effectual to impart grace only in connection with the faith and spiritual disposition of the recipient,—there being necessary to their efficacy, both the act of the believer, in the use of them, giving himself to Christ, and the act of Christ, through the same ordinance, giving Himself to the believer. It matters little whether, as with the Popish Church, the Sacraments are invested with a *physical* virtue, in consequence of which they impart grace; or whether, as with the High Churchmen of other denominations, they are invested with a *spiritual* virtue in consequence of which they impart grace,—if in both cases the grace is given by the Sacrament itself, and not given through the Spirit and the faith in the heart of the recipient. It matters little whether a physical or a spiritual explanation is given of sacramental efficacy, if it be efficacy exerted apart from Christ in the ordinance giving Himself to the believer, and experienced apart from the believer in the ordinance giving himself to Christ. Whatever be the efficacy and virtue, physical or moral, if it is independent of and separate from the faith of the recipient covenanting in the ordinance with Christ, and the act in answer to that faith of Christ covenanting with the recipient, it is not the sacramental grace which the Scripture recognises. It becomes, when thus separated and drawn apart, a mere charm, a trick of magic, whether physical or spiritual, utterly unknown to the Gospel economy. Let us endeavour to apply to this theory those tests which may serve to try its merits and its truth. There are four different tests by which we may try the merits of this sacramental theory, whether held in its extreme form by Papists, or in its more modified form by High Churchmen of other communions.

1*st*, Tested by Scripture, which constitutes the rule for the exercise of Church power, there is no warrant for asserting that there is an inherent and independent virtue in Sacraments to impart justifying or saving grace.

The truth of this general proposition may be established by a very wide and ample deduction of evidence from Scripture. It is impossible for us to do more than advert to the leading heads of proof in connection with this question. *In the first place*, those multiplied and various declarations of Scripture, which state that we are justified by faith alone without works on our part, very distinctly prove that the Sacraments cannot have an independent and inherent power in themselves of conveying justifying and saving grace. Such passages expressly assert that faith is the immediate instrumental cause of justification. They are inconsistent, therefore, with the theory that the Sacraments directly and immediately of themselves impart grace, although they are quite consistent with the doctrine that the Sacraments indirectly, and through the faith of the worthy receiver, may impart grace. *In the second place*, the doctrine that the Sacraments have an inherent virtue to confer grace, is opposed to the whole tenor of Scripture, which sets forth Christ as the one and the immediate object of faith and hope to the believer, in the matter of his justification and salvation. The Word of God, from its commencement to its close, clearly and constantly and invariably points to Christ, and to nothing but Christ, as the only source to which a sinner must look for forgiveness and acceptance with God. The theory of the Sacraments held by High Churchmen presents another and a different object for his faith, and teaches him to rest in an outward observance as sufficient. It is part of that most destructive system which places the Church and the ordinances of the Church between the sinner and his Saviour. *In the third place*, the very express testimony of the Apostle Paul, in regard to the insufficiency of the Sacraments under the Old Testament Church to communicate grace of themselves, is an argument equally effectual to show that the New Testament Sacraments are insufficient likewise. Abraham was not justified by circumcision, but by the faith of which his circumcision was the seal.[^29] *In the fourth place*, the statements of Scripture which at first sight might be construed as if they ascribed a gracious influence to the Sacraments of the New Testament in themselves, and which seem to connect saving benefits with the observance of them, are not stronger or more numerous, but less so, than those which ascribe justifying and saving blessings to the ordinance of the Word, or truth received by the reader or hearer of it. We know that the Word or the truth justifies, not of itself, but through the faith of him that receives it; and that, apart from this faith, it has no virtue or power of a gracious kind at all. In the same manner, Sacraments impart grace, not of themselves, but through the faith of those who receive them; and, apart from that faith, they have no life or blessing whatsoever. *In the fifth place*, the theory of an inherent virtue or power in the administration of the outward ordinance is utterly opposed to those numerous passages of Scripture which assert that the power of the Gospel is altogether of a spiritual kind, and is in no respect akin to a mere external and material influence, as if such could impart a supernatural grace. It is "not meat and drink, but righteousness, and peace, and joy in the Holy Ghost." And instead of pointing to any outward source of power or efficacy, and exclaiming, "Lo here, or Lo there!" the Christian has been taught to think that "the kingdom of God" has its source and presence "within him."[^30] The theory which ascribes to the Sacraments an infallible virtue which, unless counteracted by some obstacle, such as infidelity or open vice, must operate to impart grace, is inconsistent with those numerous statements of Scripture which represent the Gospel as a spiritual power, adapted to the spiritual nature of man.[^31]

[^29]: Rom. ii. 25-29, iii. 20, 30, iv. 3-11; Heb. ix. 11 f., x. 1-11. [Comp. the Apology for the Confession of Augsburg, vii. 18, p. 203, in Hase, *Libri Symbolici Eccles. Evang*. Lipsiae 1827.]

[^30]: Rom. xiv. 17; Luke xvii. 21.

[^31]: Gillespie, *Aaron's Rod Blossoming*, B. iii. chap. xii.-xiv.

In estimating the bearing of Scripture testimony on this question, there is one consideration of a general kind which it is of great importance to the argument to bear in mind. In every theory of the Sacraments that can be held,—from the lowest to the highest, from the Socinian up to the Popish,—the Sacraments are regarded as at least signs of spiritual things, representing and exhibiting the blessing in outward resemblance. The union thus established, according to any theory that can be held of them, between the sign and the thing signified by it, has introduced into Scripture a kind of phraseology which at first sight appears to give some sanction to the High Church system in regard to sacramental ordinances. There is often an exchange of names between the sign and the thing signified in Scripture, in consequence of which what may be predicated of the one is often asserted of the other, and *vice versâ*. This usage of language, so frequently exemplified in Scripture in connection with this matter, is a usage found commonly in other writings and in regard to other matters, and gives rise to no sort of misapprehension in our interpretation of it. It is the great foundation indeed of all figurative language.[^32] Thus, when Christ is said to be "the Passover sacrificed for us," there is an exchange of this kind, in which the name of the sign is given to the thing signified; and when Christ says of the bread, "This is my body," there is an exchange in the opposite way, and the name of the thing signified is attributed to the sign. And in perfect accordance with this usage of language, there are several passages in Scripture in which the mere outward observance in the case of the New Testament Sacraments, the external sign, has a virtue attributed to it which in reality belongs, not to the sign, but to the grace represented in the observance, or to the thing signified. Thus, for example, "*Baptism*" is said in one passage "*to save us*;" although, from the further explanation contained in the passage itself, it is plain that it is not the outward sign but the thing signified that is spoken of under the name of the sign; for the apostle adds immediately, "not the putting away of the filth of the flesh, but the answer of a good conscience towards God."[^33] In the same manner the Apostle Paul speaks of "the cup of blessing" as "the communion of the blood of Christ,"[^34]—language in which that is predicated of the sign which is truly predicated only of the thing signified. In short, the sacramental union between the outward sign and the inward grace gives occasion to not a few examples in Scripture in which what is true of the one only, or the inward grace, is attributed to the other, or the outward sign. Almost the whole plausibility of the argument from Scripture in favour of the High Church theory of the Sacraments comes from this source; and it is completely removed when the familiar canon of criticism, applicable to Scripture in common with other writings, is attended to,—namely, that what truly belongs to the thing signified is often predicated figuratively of the sign, and so ought to be interpreted and understood.[^35]

[^32]: ["Omnia significantia videntur quodam modo earum rerum quas significant sustinere personas: sicut dictum est ab Apostolo, 'Petra erat Christus,' quoniam petra illa, de qua hoc dictum est, significabat utique Christum."—Aug. *De Civitate Dei*, lib. xviii. cap. 48.]

[^33]: 1 Pet. iii. 21.

[^34]: 1 Cor. x. 16.

[^35]: [Westminst. Conf. chap. xxvii. 2, xxix. 5. Goode, *Nature of Christ's Presence in the Eucharist*, Lond. 1856, vol. i. pp. 241-250, 598.]

2*d*, The theory of an inherent power, physical or spiritual, in the Sacraments, is inconsistent with the supreme authority of Christ, from whom all Church power is derived.

The doctrine that would deposit in sacramental ordinances a grace communicable to the participator, apart from his communion with Christ, directly and immediately, is inconsistent with the office and right of Christ to hold in His own hand all blessing, and to dispense from His own hand, not mediately through another, but at once from Himself, the grace which His people receive. Such a theory takes the administration of grace out of the hands of Christ, ever present to dispense it, and transfers it to a priest standing in His room. There can be no participation in heavenly blessing except what comes from direct communication with Christ on the part of the soul that receives it; and it is a dishonour to Him, who is the ever-living and ever-present administrator of all grace to His people, to put the mute and conscious ordinance in the place of Christ, and to transfer the dependence of the soul for spiritual blessing from the Divine Head in heaven to the outward ministry of Sacraments on earth. That Christ *might* by His original appointment have made the Sacraments the receptacle of a physical influence, fitted and able to work a supernatural blessing on the soul, it would perhaps be presumptuous to deny. That Christ *might* at the first institution of the ordinances have made them a reservoir or storehouse of grace enough for all ages of the Church, and imparted to them a spiritual blessing out of which every subsequent generation of His people might draw their supply, we need not be anxious to dispute. Or that Christ, without communicating at the beginning to Sacraments a store either of physical or spiritual grace sufficient for all generations, might have tied Himself up to the indiscriminate and invariable communication of His Spirit along with the administration of outward Sacraments, and bound Himself down, without any choice or discretion, to link spiritual grace to material rites, apart from the faith of the person observing them,—this, too, is perhaps a *possible* imagination. But had Christ, as the Head of ordinances in His Church, done either the one or the other of these things, He must to that extent have divested Himself of His office as Mediator, or resigned the exercise of it; He must in so far have abdicated His functions as the sole and living and ever-present administrator of grace to His Church; and been shut out from that exclusive and supreme agency which He maintains as the dispenser as well as author of every blessing by which the soul is to be saved.

3*d*, The theory of the Sacraments which ascribes to them an independent virtue or power, is inconsistent with the spiritual liberties of Christ's people.

Such a system brings the soul itself into bondage. It keeps the spirit, which Christ has Himself redeemed, waiting upon man for the communication of the blessings of its redemption; it makes the soul which Christ has ransomed dependent for its freedom on the ministry of a fellow-creature. There cannot be a worse or more abject thraldom than that which subordinates the flock of the Saviour's purchase to any one but Himself, and causes them to hang upon the intention entertained or not entertained by a priest for the enjoyment or forfeiture of spiritual blessing. But even apart from the monstrous doctrine of the Romish Church as to the intention of the priest being necessary to the efficacy of the ordinance, the sacramental theory we have been considering, whether Popish or Tractarian, is inconsistent with the spiritual freedom of those whom Christ has redeemed. That freedom consists in subjection to and dependence on Christ, and none but Christ,—in being emancipated from all dependence on any other except their Saviour,—in being kept waiting, not at the footstool of man for saving blessings, but at the footstool of Christ,—and in being taught to look for all the grace they need day by day, not to the ministry of man's hand, but to the hand of Christ. Spiritual freedom for the believer is bound up with a dependence on Christ immediately and directly, and on Him alone, for every blessing that he needs.[^36]

[^36]: [Goode, *Letter to a Lay Friend*, Lond. 1845, pp. 18-24. Litton, *Church of Christ*, Lond. 1851, pp. 11-13, 202-232, 240 f.]

4*th*, The sacramental theory we have been considering is inconsistent with the spirituality of the Church, and of the power exercised by the Church for the spiritual good of men.

When, according to that theory, the Sacraments become the instruments of justification and the source of faith, instead of the seal of a justification already possessed, and the exercise and aid of a faith already in existence,—when they are made to come between the soul, in its approach to Christ, and Christ Himself, and communion in the external ordinance is substituted for the fellowship of the Spirit, it is a fatal evidence that the Church, which so teaches and so practises her teaching, although she has "begun in the Spirit," has "sought to be made perfect by the flesh."[^37] If the external ordinance be made to occupy that place which belongs to the Spirit, and participation in the ordinance be the substitute for faith, the sacramental theory thus reduced to practice will be but the commencement of worse and deeper degradation. It is but the beginning of a course which, consistently followed, must lead to a religion of form and self-righteousness, of sense and sensuous observances, of carnal ordinances and a ceremonial holiness, of outward satisfaction and penances and merit. There will be the priest and the bloodless but efficacious sacrifice, grace conferred by the tricks of a physical or spiritual magic, a religion that manifests itself outwardly and not inwardly, the holiness of houses, and altars, and sacred wood and stone, but not the holiness of the Spirit; the atonement of Sacraments and penances and creature merits, but not the atonement of the Saviour received by faith; a righteousness of bodily discipline and fleshly mortification, but not the righteousness of God imputed to the believer; a justification made out of pains and merits, of sufferings and works, but not a justification freely given by Divine grace and freely accepted by faith; an outward baptism to regenerate the sinner with water at first,—the food of the communion table, made flesh and blood by the consecration of a priest, to sustain the life so begun, and the anointing with oil at last to prepare the soul for the burial. Such are the inevitable fruits of the sacramental theory, consistently carried out in the Church of Christ, making the very temple of God to be the habitation of every carnal and unclean thing.[^38]

[^37]: Gal. iii. 3.

[^38]: Bellarm. *Disputationes*, tom. iii. lib. ii. cap. i.-xxii. Perrone, *Praelectiones Theologicae*, Parisiis 1842, tom. ii. pp. 5-66. Amesius, *Bellarm. Enerv*. tom, iii. lib. i. cap. i.-v. Turrettin, *Opera*, tom. iii. loc. xix. qu. i.-ix. Cunningham, *Works*, vol. iii. pp, 121-133. [Bruce, *Sermons on the Sacraments*, Wodrow Soc. ed. Edin. 1843, pp. 11-33. Newman, *Lectures on Justification*, pp. 316, etc.; Tract No. 90, 2d ed. p. 13. Wilberforce, *Doctrine of the Holy Eucharist*, 3d ed. Lond. 1854, pp. 17-38, 97-130. Goode, *Doctrine of the Church of England as to the Effects of Baptism in the case of Infants*, 2d ed. Lond. 1850, pp. 3-10. *Vind. of the 'Defence of the XXXIX.Art.'* etc., 2d ed. p. 38 f. *Unpublished Letter of Martyr to Bullinger*, Lond. 1850, pp. 11-13. Martensen, *Dogmatik*, 4te Aufl. Kiel 1858, pp. 361, 364. Matthes, *Comparative Symbolik*, Leipzig 1854, pp. 492-510. Thomasius, *Dogmatik*, 3ter Theil, 2te Abth. Erlangen 1861, pp. 113-135.]
