## Unscriptural or Defective Views of the Sacraments

The principles which I have laid down in regard to the nature of Sacraments, and in regard to the difference between them and ordinances not sacramental, stand opposed to the views of two parties holding extreme positions on either side of this question. There is one party who deny the grand and characteristic distinction between sacramental and other ordinances already enunciated, and hold that the Sacraments have no virtue except as badges of a Christian profession, and signs of spiritual truths. There is another party holding opinions on the subject admitting of various modifications, but agreeing in this, that they ascribe a high spiritual efficacy to the Sacraments apart from the faith or spiritual act of the receiver. By the first party the views of the Sacraments already stated by me are held to be erroneous in the way of attributing to them a greater virtue than actually belongs to them. By the second party these views are regarded as defective in the way of ascribing to Sacraments a less virtue than really belongs to them. Let us endeavour briefly and generally to estimate the merits and truth of the principles adopted by these two parties,—reserving until a future stage in our discussions the more particular examination of their theories, in their application to the Sacraments of the New Testament individually.

### [Signs, and no more than signs]

The Sacraments of the New Testament are regarded by one party as signs, and no more than signs, of spiritual things,—symbolical actions fitted to represent, and impress upon the minds of men, Gospel truths. The Socinian party have made this doctrine peculiarly their own. According to their views, a federal transaction between the believer and Christ founded on His atonement is no part of the Gospel system at all; and hence the Sacraments of the New Testament can be no seals appointed and designed to ratify such a covenant. The Socinian doctrine concerning the nature of the Sacraments allows to them no more than a twofold object and design. They are not essentially distinct from other ordinances, as set apart by themselves to be the seals of the one great covenant between the believer and Christ, at his entrance into the Church at first, and from time to time afterwards, as occasion justifies or demands. But in the first place, they are signs in which something external and material is used to express what is spiritual and invisible,—the only virtue belonging to them being what they are naturally calculated to effect, as memorials, or illustrations, or exhibitions of the important facts and truths of the Gospel; and in the second place, the Sacraments are solemn pledges of discipleship on the part of those who receive them, discriminating them from other men, and forming a public profession of or testimony to their faith as Christians. These are the two grand objects, which, according to the Socinian view, the Sacraments were intended to serve; and such, according to their theory, is the nature of the ordinance.

The same system in substance, making, as it does, Sacraments entirely or essentially teaching and symbolical signs, has been adopted by many who disown the tenets of Socinianism in regard to the Gospel system generally. The theory of the Sacraments now described has been and is held by not a few in the Church of England of somewhat latitudinarian views,—the representative of such, as a class, being Bishop Hoadly. It is avowed and advocated in the present day by a very large proportion of the Independent body, who count the Sacraments to be no more than symbolical institutions, and who are ably represented by Dr.\ Halley in his work, entitled, *An Inquiry into the Nature of the Symbolic Institutions of the Christian Religion, usually called the Sacraments*. The single difference between the Socinian doctrine, as maintained by Socinians in the present day, and the Independent doctrine, as maintained by Dr.\ Halley and others, is probably this, that Socinians limit the efficacy of the Sacraments to the natural or moral power that belongs to them as signs of Gospel truth, while Independents may admit that beyond the natural and moral power of the ordinance, as symbolical of truth, the Spirit of God makes use of them in representing truth to the mind. Let Dr.\ Halley speak his own views as they are generally held by English Independents. "The opinion we propose is, that the Sacraments are significant rites,—emblems of Divine truth,—sacred signs of the evangelical doctrine,—designed to illustrate, to enforce, or to commemorate the great and most important truths of the Gospel. Baptism, we believe, is the sign of purification, on being admitted into the kingdom of Christ, but neither the cause nor the seal of it; the Lord's Supper the commemoration of the death of Christ, the symbol of its propitiatory character, but not the assurance of our personal interest in its saving benefits. The truth exhibited in the Sacraments, just as when it is propounded in words, may be the means of the communication of Divine grace; but then the evangelical doctrine and not the Sacrament, the truth and not the symbol, the spirit and not the letter, gives life and sanctity to the recipient, as it may even to a spectator."[^01.02.01] According to this theory, it is the truth signified in the Sacrament—and not, over and above that, the Sacrament itself as a seal—that possesses any spiritual virtue; and that virtue may be, according to Socinians, the natural influence of the truth on the mind,—or, according to Independents, that natural influence, with the addition of the power communicated through the truth by the Spirit.

[^01.02.01]: Halley, *The Sacraments: an Inquiry*, etc. Lond. 1844, vol.\ i. p.\ 94\ f.

Now, in reference to this view of the Sacraments, it is necessary to bear in mind that there is no dispute as to the fact that sacramental ordinances are symbolical,—signs fitted to represent and to teach Gospel truths. Further, there is no dispute as to the fact, acknowledged by some of the advocates of this theory, that in so far as they teach or convey truth to the mind, they may be made the means of the communication of Divine grace, in the same manner very much as when the truth is propounded in words.[^01.02.02] But the point in debate is, whether the Sacraments are not more than signs, and more than merely symbolical representations of truth. We hold that they are. We contend that, in addition to being signs, they are also seals,—the visible vouchers of a federal transaction between Christ and the believer who partakes of His Sacraments,—the outward pledges speaking to the eye and the senses of the completed covenant by which Christ becomes the believer's, and the believer becomes Christ's. And further, we contend that, as seals, they are made a means of grace more powerful and efficacious than simply as signs of truth.

[^01.02.02]: ["[Es geschah in dem Zeitpunkte der Reformation, aber nicht zum ersten Male, dass die hypermystische oder zauberische Vorstellung den entgegengesetzten Fehler, die Behauptung des ]{lang=de}[*signum nudum*]{lang=la}[ oder des blossen Bekenntnisszeichens, hervorrief. Gegen diejenige Kirche, die im Dienste der Verwandlungslehre und des ]{lang=de}[*opus operatum*]{lang=la}[ die symbolische Natur des Sacraments verleugnete und zerstörte, hatte die sogenannte Ketzerei allezeit Recht, zunächst nur wieder das Daseyn des Symbols und die Bedeutung zu behaupten. Diejenige Kirche, die des Sacramentes Wirkung und Wesen vom lebendigen Worte und Glauben, den Sohn vom Geiste losgerissen hatte, durfte einen Gegner nie Lügen strafen oder des Unchristenthums zeihen, der der Gemeinschaft des Erlösers durch die Speise des Wortes als durch die rechte Assimilation mit seinem Leben theilhaft zu werden hoffte, und sich des Sacramentes nur noch als eines Zeichens dieser Gemeinschaft, oder auch dieses Zeichens nicht mehr bediente weil es so sehr vom Wesen abgelenkt und etwa nur habe bei noch nicht ganz befestigter Wirksamkeit des Wortes einem anfänglichen Bedürfnisse dienen sollen.]{lang=de}" (This is still the position of the Quakers as expounded by Barclay in his *Apology*.) "[*Blosse Gebetschristen*, Messalianer und dergleichen, *sind nicht weniger Christen als blosse Sacramentschristen; blosse Symboliker stehen sich nicht schlechter mit der Quelle des Lebens als die Hierurgen die den Leib Christi conficiren.* Diese sind am Ende des verschwindenden Christenthums angelangt, jene stehen am Wiederanfange der Entwickelung.]{lang=de}"—Nitzsch, [*prot. Beant. der Symb. Möhlers*]{lang=de}, Hamburg 1835, p.\ 162.]

The arguments urged by Dr.\ Halley against this additional office and virtue attributed to Sacraments as more than signs, and as the seals of a federal engagement between the worthy recipient and Christ, are the two following, as stated in his own words: "First, The ceremonial institutes of preceding dispensations, the Sacraments of the patriarchal and Jewish Church, correspond only with the view which we take of the Christian Sacraments as sacred signs of Divine truth. Second, The Sacraments considered as the causes or the means, or even the seals of converting or regenerating grace, stand opposed to the great Protestant doctrine of justification by faith without works."[^01.02.03] We shall very briefly examine each of these two objections to the view which we have announced. And we do this all the more readily, as it will afford us the better opportunity of bringing out our own principles in contrast with those embodied in the Independent theory of the Sacraments.

[^01.02.03]: Halley, p.\ 95.

**1st**, Dr.\ Halley alleges, against the ascription to the New Testament Sacraments of the character of seals, that the ceremonial institutes of preceding dispensations, the Sacraments of the patriarchal and Jewish Church, correspond only with the views which he advocates of the Christian Sacraments as exclusively signs of Divine truth. Perhaps there never was a more unfortunate or unfounded assertion. "One passage of St. Paul," says Dr.\ Halley, "will establish this proposition."[^01.02.04] And the single passage which is to bear the weight of the whole argument is the following one from the Epistle to the Romans: "He is not a Jew which is one outwardly; neither is that circumcision which is outward in the flesh. But he is a Jew which is one inwardly; and circumcision is that of the heart, in the spirit, and not in the letter; whose praise is not of men, but of God."[^01.02.05] This is the solitary passage quoted to prove the broad and general assertion, that the Sacraments of the patriarchal and Jewish Church afford no precedent or example of Sacraments as seals, but only of Sacraments as signs. The verses quoted plainly amount to nothing more than a statement of the difference between what the apostle calls circumcision outwardly and circumcision inwardly, the external rite and the internal grace, and a declaration that a man might have the outward rite, and not the inward grace. The apostle does not say, and cannot, except by a violent misapplication of his words, be made to say, that *in the case of the man who has both the outward and inward circumcision*, the external rite may not be the visible seal of the spiritual grace. The very opposite of this the same apostle in the very same Epistle undeniably asserts. In language as plain as he could possibly select or employ, Paul affirms that in the case of Abraham, who had the inward grace, the outward rite of circumcision was a seal to him of that grace. "Abraham," says the apostle, "received the sign of circumcision, a *seal* of the righteousness of the faith which he had yet being uncircumcised."[^01.02.06] And how is it that Dr.\ Halley gets rid of this express assertion of the apostle, standing as it does in explicit contradiction to his general averment that the Sacraments of the Jewish Church were signs and not seals? He admits that to Abraham personally and individually circumcision was a seal, and not merely a sign. But by a strange misapprehension of the doctrine of his opponents, he argues that it could not be a seal of faith to others of Abraham's family or countrymen who had not his faith. "Although," says Dr.\ Halley, "to him circumcision was the seal of faith, it could not have been so to his posterity." "Was it," he asks, "was it, in this sense, a seal of the righteousness which they had, an approval of their faith, to the men of his clan, or to Ishmael, or to the infants of his household, or to any of his posterity in subsequent ages?"[^01.02.07] The answer to such a question is abundantly obvious. If the men of Abraham's clan had not faith, if Ishmael had not faith, circumcision could have been no seal of faith to them. The outward rite could not be a seal of the inward grace, when the latter did not exist. It could not be a seal of a spiritual covenant between them and God which had not been entered into. I do not stop to consider the question of whether or not circumcision is to be accounted, even in such a case, the seal to such individuals of the outward blessings promised to them, as Jews, by God, as the rightful King of Israel as a nation; but, as a seal of a spiritual covenant, it of course could not be a seal at all to those who were not parties to the covenant,—while it was a seal, according to the explicit assertion of the apostle, to those who were. The very express statement of Paul cannot be evaded, but fully bears out the assertion that the Sacraments of the Jewish Church were not signs alone, but seals of a spiritual covenant to those who were really parties to the covenant. "Abraham received the sign of circumcision, a *seal* of the righteousness of the faith which he *had*."

[^01.02.04]: Ibid. p.\ 96.

[^01.02.05]: Rom.\ 2:28–29.

[^01.02.06]: Rom.\ 4:11.

[^01.02.07]: Halley, p.\ 100.

**2d**, Dr.\ Halley alleges that the Sacraments, if they are considered as the cause or the means, or even the seals of spiritual and saving grace, would be opposed to the great Protestant doctrine of justification by faith without works. Now it is readily admitted, that if Sacraments are regarded as the causes or means of justification, they are utterly inconsistent with the Protestant doctrine of justification by faith alone; and in this point of view the objection is true and unanswerable when directed against some of those theories of the Sacraments which we may be called upon to consider by and by. But it is denied that the objection is true when directed against the theory of the Sacraments which maintains that they are not causes and not means of justification, but seals of it and of other blessings of the new covenant. The Sacraments as seals, not causes of justification, cannot interfere with the doctrine of justification by faith, for this plain reason, that before the seal is added, the justification is completed. The seal implied in the Sacrament presupposes justification, and does not directly or instrumentally cause it; the seal is a voucher given to the believer that he is justified already, and not a means or a cause of procuring justification for him. Justification exists before the seal that attests it is bestowed. The believer has previously been "justified by faith without the works of the law," ere the Sacrament of which he partakes can affix the visible seal to his justification. All this is abundantly obvious; and the objection of Independents, that the doctrine of the Sacraments as personal seals is opposed to the principle of justification by faith, is wholly without foundation. That the Sacraments are a means of grace additional to what the believer possessed before his participation in them, it is not necessary to deny, but rather proper strongly to assert.[^01.02.08] In entering into a personal covenant with Christ through participation<!-- original typo:"particiption" --> in the Sacraments, or in renewing that covenant from time to time, the faith of the believer is called forth and brought into exercise in the very act of participation, and by the aids to faith which the ordinance affords. And in answer to this faith so exercised and elicited, there is an increase of grace given to the worthy recipient above and beyond what he had before. The faith of the believer, called into exercise in partaking of the ordinance and by means of it, is met by the bestowment of corresponding grace. But it is never to be forgotten that the Sacraments presuppose the existence of grace, however they may give to him that already has it more abundantly. They presuppose, and beforehand require, that a man is justified by faith before they give their seal to his justification.

[^01.02.08]: ["[Das Gläubigste, so zu sagen, am sacramentlichen christlichen Gemeinglauben ist doch wohl dieses: je mehr das Sacrament mit voller Empfänglichkeit genossen wird, desto weniger ist es blosses Zeichen, oder blosses Unterpfand der Lebensmittheilung Christi, desto mehr diese Mittheilung selbst. Das Sacrament ist Leiter, Kanal der Gnade, wie der römische Katechismus sich ausdrückt. Bis auf diesen Punkt wird der Sacramentsbegriff—ich will zugeben unter sehr verschiedenen Bedingungen ]{lang=de}(from those of the Romanist theory)[—durch das in dieser Hinsicht ganz ungetheilte Bekenntniss der Protestanten gesteigert. .\ .\ . Der protestantische Begriff des Siegels oder Pfandes ist weit entfernt die *collative* Kraft des Sacraments zu schwächen; er gestattet sogar die mystische Verknüpfung der Elemente des Sacraments mit der ]{lang=de}[*res signata et exhibenda; signa et res significatæ sacramentaliter conjunguntur*]{lang=la} ([*Conf. Helv. post.*]{lang=la}\ xix.). [*Bezeichnung*, *Besiegelung*, *Darreichung* der Gnade Christi vereinigen sich im Sacramente.]{lang=de} ([*Decl. Thorun. De Sacr.*]{lang=la} 1,\ 7)."—Nitzsch, *prot. Beant. der Symb. Möhlers*, Hamburg 1835, p.\ 151\ f.]

There is no ground, then, in Scripture, but the very opposite, for asserting that the Sacraments are no more than signs or symbolical actions, as held by Dr.\ Halley and those whom on this question he represents. The fundamental error involved in the views now adverted to is, the denial of Christ's part in the federal transaction involved in a Sacrament. Independents overlook *His* department of the work in the engagement entered into through means of the act of receiving the Sacraments; and in the absence of the act of Christ giving Himself and all His spiritual blessings to the believer in the ordinance, the act of the recipient is not met by the grace that Christ confers, but is reduced to a mere significant dedication of himself to the Saviour unconnected with any grace at all. Take away Christ from the ordinance as present there, to covenant with the believer, actually giving Himself and His blessings spiritually through means of the outward ordinance, in answer to the faith of the believer giving himself to Christ through the same ordinance, and the Sacrament is evacuated of all spiritual grace; the act of the receiver becomes a mere expressive sign of what he is willing to do in the way of dedicating himself to Christ; but not an actual dedication, accomplished through means of a covenant *then* and *there* renewed, by which the believer becomes Christ's, and Christ becomes the believer's. The principle of the Independents in regard to the Sacraments cuts the Sacrament, as it were, in twain, and puts asunder what God has joined. It leaves to the believer his part in the transaction, in so far as he employs the Sacrament as a sign of his dedication to Christ; but it takes away Christ's part in the transaction, in so far as He meets with the believer and enters into covenant with him,—accepting the believer as His, and giving Himself to the soul in return. Severed from Christ in the ordinance, and from the covenant with His people into which Christ there enters, the act of the recipient can be no more than an expressive sign, or convenient profession of faith, unconnected with true and proper sacramental grace.

### [Imparting justifying and saving grace directly]

The Sacraments of the New Testament are regarded by another party as in themselves, and by reason of the virtue that belongs to them, and not through the instrumentality of the faith or the Spirit in the heart of the recipient, effectual to impart justifying and saving grace directly, in all cases where it is not resisted by an unworthy reception of the ordinance. This general opinion may be held under various modifications; but all of them are opposed to the doctrine I have already laid down, that the Sacraments are seals of a justifying and saving grace already enjoyed by the recipient, and not intended for the conversion of sinners; and that they become means of grace only in so far as the Spirit of God, by the aid of the ordinance, calls forth the faith of the recipient, and no further.

The doctrine of the efficacy of Sacraments, directly and immediately of themselves, and not indirectly and mediately through the faith of the receiver, and through the Spirit in the receiver, is advocated in its extreme and unmodified form by the Church of Rome. According to that Church, these ordinances, as outward and material rites, become, after certain words of institution pronounced by the priest, possessed of a sacramental virtue, which is conveyed infallibly to the soul of the person who receives them, on *two* conditions, which are necessary to justifying and spiritual grace being really imparted. *First*, on the side of the priest who pronounces the words of institution, there is required, as a condition of the supernatural grace being imparted, that he have the intention to make the Sacrament and confer it; for without this, the outward matter of the ordinance would remain mere matter, and have no sacramental character or virtue. And *second*, on the side of the recipient of the ordinance, it is required that he be free from any of those sins which, in the language of Popery, are called "mortal," and which, when contracted and not removed, would resist the operation of the sacramental virtue, and prevent his soul receiving spiritual grace. But when these two conditions are present,—when the priest intends to consecrate and dispense the ordinance, and the recipient is not barred from the reception of its virtue by mortal sin,—such is the efficacy of the Sacrament in itself, and directly, that it infallibly communicates to the partaker of it justifying and saving grace. The doctrine of the Church of Rome is very distinctly brought out in the canons of the Council of Trent, and also in her Catechism. "If any," says the 11th canon concerning the Sacraments in general, "if any shall say that there is not required in the ministers, when they make and confer the Sacraments, at least the intention of doing what the Church does, let him be accursed." "If any shall say that the Sacraments of the New Law do not contain the grace of which they are the signs, or that they do not confer that grace on those who place no obstacle in the way, as if they were only outward signs of grace or justification already received by faith, and certain badges of the Christian profession, by which believers are distinguished from infidels, let him be accursed." "If any shall say that grace is not conferred by the Sacraments of the New Law, [*ex opere operato*]{lang=la}, but that faith in the Divine promise alone avails to secure grace, let him be accursed."[^01.02.09] According to this doctrine, then, Sacraments impart grace, not through the channel of the faith of the receiver, and not in dependence in any way on his spiritual act, but immediately and directly from themselves, "[*ex opere operato*]{lang=la}." This last expression is to be interpreted in connection with the distinction drawn by the Church of Rome between the Sacraments of the Old and New Testament Churches. The Sacraments of the Gospel Church are superior in efficacy to those under the law, in the Popish theory, because the former, or the New Testament Sacraments, work grace independently of the spiritual disposition or act of the recipient; whereas the latter, or Old Testament Sacraments, were dependent on the spiritual disposition or act of the receiver of them. The "[*opus operatum*]{lang=la}" of the New Testament Sacraments, or the virtue they have by their own act, apart from the spiritual state of the recipient, is contrasted with the "[*opus operantis*]{lang=la}" in the Old Testament Sacraments, or the virtue which they had, not in themselves, or in their own operation, but only in connection with the spiritual act of the partaker. According to the proper theory of the Church of Rome, the Sacraments of the New Testament impart grace [*ex opere operato*]{lang=la}, or from their own intrinsic virtue and direct act on the soul of him who receives them.[^01.02.10]

[^01.02.09]: [*Concil. Trident. Canones et Decreta*]{lang=la}, Sess.\ vii. [*De Sacr. in Gen.*]{lang=la}, Can.\ vi. viii. xi. [Compare Möhler's statement of the Roman Catholic theory of the Sacraments ([*Symb.* 6te Aufl. pp.\ 253–258]{lang=de}). It is worthy of remark, that that acute and dexterous controversialist, in his own exposition of the doctrine, passes over in utter silence the very remarkable and important element of the priest's intention, as defined at Trent,—the sole reference to it being in a quotation from Bellarmine given in a note (p.\ 256). Nitzsch's remarks on the significance of the point thus ignored, are worth quoting: "The demand of an *intention* on the part of the priest in order to the Sacrament being savingly effectual, or effectual at all, met opposition among the Romish theologians, both at and before the Council of Trent. At one time the danger was pleaded incurred by the baptized or the absolved, who might now so easily miss obtaining grace, or be left in uncertainty about it; at another, the much greater concession already made, that unbelief, or even mortal sin on the part of the priest, did not destroy the efficacy of the priestly act. On these grounds, the Council saw themselves compelled to restrict the demand as much as possible; it asserted itself, notwithstanding. Sess.\ vii. Can.\ 11: '[Si quis dixerit in ministris, dum Sacramenta conficiunt et conferunt, non requiri intentionem saltem faciendi quod facit Ecclesia, anathema sit]{lang=la},' with good reason, as is easily to be seen. For if, as Can.\ x. decided, the private Christian cannot make or confer most of the Sacraments,—if the supernatural qualification of the priest, although a '[*gratia gratis data*]{lang=la},' and not '[*gratum faciens*]{lang=la},' still was of the essence of the sacramental dispensation,—while, on the other hand, no '[*bonus motus*]{lang=la}' of the recipient was necessary for the reception of the grace, nay, in the case of private mass, no recipient at all, in the case of infant Baptism, no conscious recipient, was needed,—then, should there be an *entire* absence of harmony between the mental state of the priest and the design of the transaction, there would be absolutely nothing left but the bare, mechanical, accidental, external act; and from this hardly a single believer would have expected any blessing whatsoever. The worth of the words of institution and promise, as appropriated by faith, had already been sacrificed to the worth of the '[*opus*]{lang=la};<!-- removed italics from semicolon -->' so had the dignity of the congregation to the dignity of the priest: hence arose great perils and perplexities, if now, after all, the worth of the words should be allowed to stand without moral desert on the part of the priest. The morally indifferent supernatural qualification of the priest must therefore now receive at least a psychological quickening, and the co-operation of the mental state of the priest be thus brought in to give the requisite support to a transaction otherwise bereft of all substance and security. They resigned themselves, accordingly, to the lesser perplexity. The doctrine of the '[*intentio ministri*]{lang=la}' is a reinforcement to the doctrine of the '[*opus operatum*]{lang=la},' which yields at the same time various advantages of another sort; and the latter dogma is again explained and supported by the notion of the 'not interposed hindrance.'" [*Prot. Beant.*]{lang=de} Hamburg 1835, p.\ 154. Gerhard, [*Loci*]{lang=la}, xviii.\ 31–38, ed. Preuss. tom.\ iv. pp.\ 151–158.]

[^01.02.10]: The statement that Papists hold the Sacraments to be efficacious of themselves, apart from the spiritual condition of the recipient, is often met—especially by English Romanists—with a flat denial. And on this ground. They hold that many elements are, in point of fact, present in every case in which the Sacraments are efficacious; some of these elements are connected with the state of the recipient,—such as a desire to receive the ordinance,—and others with the working of God. Thus Bellarmine objects to Calvin's stating the point in debate to be, not as to grace being conferred in the Sacraments, but only "whether God works in them by His own proper, and, so to speak, intrinsic virtue, or whether He resigns His place to the external signs."—*Inst.* lib.\ iv. c.\ xiv.\ 17. (See next note.) Any Romanist, however, who has the slightest regard for the authoritative declarations of his Church, can be fixed down conclusively to this position, that, whatever other elements may, in point of fact, be present, the immediate, efficient, instrumental cause of the grace invariably conveyed to all "[qui non ponunt obicem]{lang=la}" is "the outward action called a Sacrament," and nothing else. See Turrettin's masterly treatment of this point, [*Opera*]{lang=la}, loc.\ xix. Qu.\ viii. 2–6. Cunningham, *Works*, vol.\ iii. pp.\ 124–139. Hodge, *Princeton Essays and Reviews*, New York 1857, pp.\ 370\ f., 388.

This doctrine of the inherent power of Sacraments in themselves to impart grace, held by the Church of Rome, is also the system maintained, although with some important modifications, by another party beyond the pale of that Church, the representatives of which, at the present day, are to be found in the High Churchmen of the English Establishment. The doctrine of the High Church party in the English Establishment in regard to the Sacraments differs indeed in *two* important particulars from the full and unmodified development of it found in the Popish system; but in other respects it is substantially the same,—equally implying the inherent power of Sacraments to impart grace, not through the spiritual act of the recipient, but apart from and independently of it. The advocates of High Church principles in the Church of England generally—although there is a numerous and increasing section of them who in this respect approximate more nearly to Rome—generally reject the Popish doctrines,—*first*, of the [*opus operatum*]{lang=la}, and *second*, of the necessity for the intention of the priest in the Sacrament. They deny that the Sacraments have any immediate physical influence upon the soul, by the very act of outwardly participating in them,—such as is implied in the [*opus operatum*]{lang=la} of the Church of Rome; and they deny, further, that the intention of the priest to make and confer the Sacrament is a necessary condition of it, without which it could impart no grace. These two elements in the Popish theory of sacramental ordinances are rejected, generally speaking, by the High Church disciples of the English Establishment, although instances are not awanting—and they seem to be multiplying of late—of both these monstrous pretensions being, in a certain sense, maintained by them. But they agree with the Romish Church in the grand and fundamental principle which belongs to its doctrine of the Sacraments,—namely, that they communicate grace from the sacramental virtue that resides in themselves,—or, as some prefer to put it, that invariably accompanies them by Christ's appointment,[^01.02.11]—and by their own immediate influence on the soul, and not instrumentally by the operation of the Spirit of God on the worthy recipient and through the medium of his faith. This is the characteristic principle that is common both to the Popish and the High Church theories of Sacraments. Both these parties hold that there is something in or connected with the ordinance which directly and immediately does the work of grace upon the soul; and not merely indirectly and mediately through the Spirit of God working on the soul, and the faith of the soul working in return. The Church of Rome ascribes this efficacy of the ordinances to the [*opus operatum*]{lang=la} of the Sacraments, and the act and intention of the priest in consecrating them. The High Churchmen of the English Establishment usually reject both of these doctrines as laid down by the Council of Trent, and ascribe this efficacy of the ordinances to the deposit of spiritual grace which Christ has communicated to the Church, and connected with the Sacraments, and given them the power to impart. But the High Churchmen of Rome and the High Churchmen of England agree equally in this, that there are in the Sacraments an efficacy and power to impart grace of themselves, directly and immediately, to the soul of the recipient; and that they are not merely aids or instruments for bringing the recipient into direct and immediate communication with Christ to receive grace from Him.[^01.02.12]

[^01.02.11]: In, [cum]{lang=la}, or [sub Sacramento]{lang=la}. ["It is to be observed," says Bellarmine, "that the dispute is not about the *mode* in which Sacraments are causes of justification, *i.e.* whether the effect is produced by physical or moral means; and again, if the influence be of a physical sort, whether it be by some inherent quality, or by the simple will of God; for these points do not belong to the question of faith; but only in general, whether the Sacraments are true and proper causes of justification; so that it truly follows, from a man's being baptized, that he is justified."—[*Disputationes*]{lang=la}, tom.\ iii. lib.\ ii. cap.\ i.]

[^01.02.12]: [Goode, *Nature of Christ's Presence in the Eucharist*, Lond. 1856, vol.\ i. pp.\ vi. 11–55. Cunningham, *Works*, vol.\ i. pp.\ 233–237.]

Although both the Canons and Catechism of the Council of Trent lay down, to all appearance, expressly and undeniably the doctrine that there is a physical virtue in Sacraments, whereby they operate upon the recipient, yet there are not awanting doctors of the Romish Church who are anxious to soften down the dogma of the [*opus operatum*]{lang=la}, and to explain it in the sense of a moral and spiritual, and not a physical virtue, residing in the ordinance. And in this modified form of it, the Romish doctrine of the Sacraments—apart from the necessity of the priest's intention—approximates very closely to the High Church theory entertained by many in the Church of England. That theory maintains the doctrine of not a physical but a spiritual virtue deposited and residing in the Sacrament, which operates universally, not through the faith or spiritual act of the recipient, but directly and immediately through the act of participation in the outward ordinance. This, in fact, is no more than part of the general doctrine that the Church is the grand storehouse of grace to man, and not Christ Himself; and that it is by communication with the Church, and not by direct communication with Christ, that the soul is made partaker of that grace. The Sacraments, as the chief medium through which the Church communicates of its stores of spiritual blessings, are the efficient instruments for imparting grace directly to the recipient.

Now, there is one preliminary remark which, in proceeding to estimate the value and truth of such principles in regard to the Sacraments, it is necessary to bear in mind. It is not denied, but, on the contrary, strongly maintained and asserted, that the Sacraments are means of grace. To the believer who uses them aright, they are made the means of conveying spiritual blessings. In regard to this, there is no controversy between the opponents and the advocates of High Church views of the Sacraments, whether Popish or Tractarian. But the question in dispute is, whether the Sacraments become effectual, from a virtue in themselves, or in the priest that consecrates them, or only by the work of the Spirit and the faith of the recipient? That the faith of the believer is called forth and exercised in the ordinance, and that through this faith he receives grace additional to what he enjoyed before, we do not dispute, but, on the contrary, strenuously maintain. That the spiritual act of the believer in the ordinance, when in faith he gives himself to his Saviour, is met by the spiritual act of Christ in the ordinance, when in return He gives Himself and His grace to the believer, is a doctrine at all times to be asserted and vindicated. That the faith of the recipient, in the act of committing and engaging himself to Christ, through means of the ordinance, is a faith unto which Christ is given in return, we would constantly affirm; and in this sense, and in this way, the Sacraments become means or channels or instruments whereby grace is given and conveyed. But they are no means of grace except through the faith of the recipient, and in consequence of his own spiritual state and act. There is no inherent power in the ordinance itself to confer blessing, apart from the faith of the participator, and except through the channel of that faith. There is no deposit of power—whether, with the Church of Rome, we deem it physical and [*ex opere operato*]{lang=la}, or whether, with Tractarians and High Churchmen, we call it spiritual—in the Sacraments themselves to influence the mind of him who receives them. They have no virtue of themselves, apart from the work of Christ through His Spirit on the one side, and the spiritual act of the recipient through his faith on the other side. In the language of Amesius, in his admirable reply to Bellarmine, Sacraments have no power "[efficere gratiam immediate, sed mediante Spiritu Dei et fide]{lang=la}."[^01.02.13]

[^01.02.13]: Amesius, *Bellarm. Enerv.* Amsterdam 1658, tom.\ iii. lib.\ i. cap.\ v. p.\ 22. "In the following sentences of the *Declaration of Thorn*," observes Nitzsch, "all Protestants agree: 'Sacraments are outward and visible signs, seals, and testimonials of the Divine will, instituted by God Himself, by the combination of Word and element, in order to seal and exhibit, through means of these signs, the invisible grace which is promised in the Word of the covenant. It is obvious that we by no means make them bare signs, empty and inefficacious, or mere badges of outward profession, since, besides their mystical significance, according to the Divine institution, we attribute to the Sacraments a sure sealing of God's promises, and at the same time a true and infallible exhibition of the things promised, in the way suited and proper to them, to be received by a living faith.'" (Niemeyer, p.\ 680.) [*Prot. Beant. der Symb. Möhler's*]{lang=de}, Hamburg 1835, p.\ 175. Bruce, *Serm. on the Sacr.* Wodrow Soc. ed. Edin. 1843, p.\ 10\ f. Calvin, *Antidote to Council of Trent*, Sess.\ vii. Can.\ ii. iv.–vi. *Tracts*, vol.\ iii. Calvin Transl. Soc. Edin. 1851, pp.\ 172–175.]

Has the Church, then, ordinances for its administration and use which, either by the original appointment of Christ, or by deposit of grace from Christ, have in themselves virtue to impart spiritual blessing through the administration of them alone? Or has the Church ordinances for its administration and use which have no virtue in themselves to communicate grace, except in connection with the faith of the receiver, and the blessing imparted by the Spirit? Are the Sacraments of the New Testament themselves a quickening power in the soul, apart from the faith or spiritual act of the participator,—the original deposit of grace committed to them being still retained, and still communicable through their administration, and that alone? Or are these Sacraments effectual to impart grace only in connection with the faith and spiritual disposition of the recipient,—there being necessary to their efficacy, both the act of the believer, in the use of them, giving himself to Christ, and the act of Christ, through the same ordinance, giving Himself to the believer. It matters little whether, as with the Popish Church, the Sacraments are invested with a *physical* virtue, in consequence of which they impart grace; or whether, as with the High Churchmen of other denominations, they are invested with a *spiritual* virtue in consequence of which they impart grace,—if in both cases the grace is given by the Sacrament itself, and not given through the Spirit and the faith in the heart of the recipient. It matters little whether a physical or a spiritual explanation is given of sacramental efficacy, if it be efficacy exerted apart from Christ in the ordinance giving Himself to the believer, and experienced apart from the believer in the ordinance giving himself to Christ. Whatever be the efficacy and virtue, physical or moral, if it is independent of and separate from the faith of the recipient covenanting in the ordinance with Christ, and the act in answer to that faith of Christ covenanting with the recipient, it is not the sacramental grace which the Scripture recognises. It becomes, when thus separated and drawn apart, a mere charm, a trick of magic, whether physical or spiritual, utterly unknown to the Gospel economy. Let us endeavour to apply to this theory those tests which may serve to try its merits and its truth. There are four different tests by which we may try the merits of this sacramental theory, whether held in its extreme form by Papists, or in its more modified form by High Churchmen of other communions.

**1st**, Tested by Scripture, which constitutes the rule for the exercise of Church power, there is no warrant for asserting that there is an inherent and independent virtue in Sacraments to impart justifying or saving grace.

The truth of this general proposition may be established by a very wide and ample deduction of evidence from Scripture. It is impossible for us to do more than advert to the leading heads of proof in connection with this question. *In the first place*, those multiplied and various declarations of Scripture, which state that we are justified by faith alone without works on our part, very distinctly prove that the Sacraments cannot have an independent and inherent power in themselves of conveying justifying and saving grace. Such passages expressly assert that faith is the immediate instrumental cause of justification. They are inconsistent, therefore, with the theory that the Sacraments directly and immediately of themselves impart grace, although they are quite consistent with the doctrine that the Sacraments indirectly, and through the faith of the worthy receiver, may impart grace. *In the second place*, the doctrine that the Sacraments have an inherent virtue to confer grace, is opposed to the whole tenor of Scripture, which sets forth Christ as the one and the immediate object of faith and hope to the believer, in the matter of his justification and salvation. The Word of God, from its commencement to its close, clearly and constantly and invariably points to Christ, and to nothing but Christ, as the only source to which a sinner must look for forgiveness and acceptance with God. The theory of the Sacraments held by High Churchmen presents another and a different object for his faith, and teaches him to rest in an outward observance as sufficient. It is part of that most destructive system which places the Church and the ordinances of the Church between the sinner and his Saviour. *In the third place*, the very express testimony of the Apostle Paul, in regard to the insufficiency of the Sacraments under the Old Testament Church to communicate grace of themselves, is an argument equally effectual to show that the New Testament Sacraments are insufficient likewise. Abraham was not justified by circumcision, but by the faith of which his circumcision was the seal.[^01.02.14] *In the fourth place*, the statements of Scripture which at first sight might be construed as if they ascribed a gracious influence to the Sacraments of the New Testament in themselves, and which seem to connect saving benefits with the observance of them, are not stronger or more numerous, but less so, than those which ascribe justifying and saving blessings to the ordinance of the Word, or truth received by the reader or hearer of it. We know that the Word or the truth justifies, not of itself, but through the faith of him that receives it; and that, apart from this faith, it has no virtue or power of a gracious kind at all. In the same manner, Sacraments impart grace, not of themselves, but through the faith of those who receive them; and, apart from that faith, they have no life or blessing whatsoever. *In the fifth place*, the theory of an inherent virtue or power in the administration of the outward ordinance is utterly opposed to those numerous passages of Scripture which assert that the power of the Gospel is altogether of a spiritual kind, and is in no respect akin to a mere external and material influence, as if such could impart a supernatural grace. It is "not meat and drink, but righteousness, and peace, and joy in the Holy Ghost." And instead of pointing to any outward source of power or efficacy, and exclaiming, "Lo here, or Lo there!" the Christian has been taught to think that "the kingdom of God" has its source and presence "within him."[^01.02.15] The theory which ascribes to the Sacraments an infallible virtue which, unless counteracted by some obstacle, such as infidelity or open vice, must operate to impart grace, is inconsistent with those numerous statements of Scripture which represent the Gospel as a spiritual power, adapted to the spiritual nature of man.[^01.02.16]

[^01.02.14]: Rom.\ 2:25–29; 3:20, 30; 4:3–11; Heb.\ 9:11–12; 10:1–11. [Comp. the Apology for the Confession of Augsburg, vii. 18, p.\ 203, in Hase, [*Libri Symbolici Eccles. Evang.* Lipsiæ]{lang=la} 1827.]

[^01.02.15]: Rom.\ 14:17; Luke\ 17:21.

[^01.02.16]: Gillespie, *Aaron's Rod Blossoming*, B.\ iii. chap.\ xii.–xiv.

In estimating the bearing of Scripture testimony on this question, there is one consideration of a general kind which it is of great importance to the argument to bear in mind. In every theory of the Sacraments that can be held,—from the lowest to the highest, from the Socinian up to the Popish,—the Sacraments are regarded as at least signs of spiritual things, representing and exhibiting the blessing in outward resemblance. The union thus established, according to any theory that can be held of them, between the sign and the thing signified by it, has introduced into Scripture a kind of phraseology which at first sight appears to give some sanction to the High Church system in regard to sacramental ordinances. There is often an exchange of names between the sign and the thing signified in Scripture, in consequence of which what may be predicated of the one is often asserted of the other, and [*vice versâ*]{lang=la}. This usage of language, so frequently exemplified in Scripture in connection with this matter, is a usage found commonly in other writings and in regard to other matters, and gives rise to no sort of misapprehension in our interpretation of it. It is the great foundation indeed of all figurative language.[^01.02.17] Thus, when Christ is said to be "the Passover sacrificed for us," there is an exchange of this kind, in which the name of the sign is given to the thing signified; and when Christ says of the bread, "This is my body," there is an exchange in the opposite way, and the name of the thing signified is attributed to the sign. And in perfect accordance with this usage of language, there are several passages in Scripture in which the mere outward observance in the case of the New Testament Sacraments, the external sign, has a virtue attributed to it which in reality belongs, not to the sign, but to the grace represented in the observance, or to the thing signified. Thus, for example, "*Baptism*" is said in one passage "*to save us*;<!-- removed italics from semicolon -->" although, from the further explanation contained in the passage itself, it is plain that it is not the outward sign but the thing signified that is spoken of under the name of the sign; for the apostle adds immediately, "not the putting away of the filth of the flesh, but the answer of a good conscience towards God."[^01.02.18] In the same manner the Apostle Paul speaks of "the cup of blessing" as "the communion of the blood of Christ,"[^01.02.19]—language in which that is predicated of the sign which is truly predicated only of the thing signified. In short, the sacramental union between the outward sign and the inward grace gives occasion to not a few examples in Scripture in which what is true of the one only, or the inward grace, is attributed to the other, or the outward sign. Almost the whole plausibility of the argument from Scripture in favour of the High Church theory of the Sacraments comes from this source; and it is completely removed when the familiar canon of criticism, applicable to Scripture in common with other writings, is attended to,—namely, that what truly belongs to the thing signified is often predicated figuratively of the sign, and so ought to be interpreted and understood.[^01.02.20]

[^01.02.17]: ["[Omnia significantia videntur quodam modo earum rerum quas significant sustinere personas: sicut dictum est ab Apostolo, 'Petra erat Christus,' quoniam petra illa, de qua hoc dictum est, significabat utique Christum.]{lang=la}"—Aug. [*De Civitate Dei*]{lang=la}, lib.\ xviii. cap.\ 48.]

[^01.02.18]: 1\ Pet. 3:21.

[^01.02.19]: 1\ Cor. 10:16.

[^01.02.20]: [Westminst. Conf. chap.\ xxvii.\ 2, xxix.\ 5. Goode, *Nature of Christ's Presence in the Eucharist*, Lond. 1856, vol.\ i. pp.\ 241–250,\ 598.]

**2d**, The theory of an inherent power, physical or spiritual, in the Sacraments, is inconsistent with the supreme authority of Christ, from whom all Church power is derived.

The doctrine that would deposit in sacramental ordinances a grace communicable to the participator, apart from his communion with Christ, directly and immediately, is inconsistent with the office and right of Christ to hold in His own hand all blessing, and to dispense from His own hand, not mediately through another, but at once from Himself, the grace which His people receive. Such a theory takes the administration of grace out of the hands of Christ, ever present to dispense it, and transfers it to a priest standing in His room. There can be no participation in heavenly blessing except what comes from direct communication with Christ on the part of the soul that receives it; and it is a dishonour to Him, who is the ever-living and ever-present administrator of all grace to His people, to put the mute and conscious ordinance in the place of Christ, and to transfer the dependence of the soul for spiritual blessing from the Divine Head in heaven to the outward ministry of Sacraments on earth. That Christ *might* by His original appointment have made the Sacraments the receptacle of a physical influence, fitted and able to work a supernatural blessing on the soul, it would perhaps be presumptuous to deny. That Christ *might* at the first institution of the ordinances have made them a reservoir or storehouse of grace enough for all ages of the Church, and imparted to them a spiritual blessing out of which every subsequent generation of His people might draw their supply, we need not be anxious to dispute. Or that Christ, without communicating at the beginning to Sacraments a store either of physical or spiritual grace sufficient for all generations, might have tied Himself up to the indiscriminate and invariable communication of His Spirit along with the administration of outward Sacraments, and bound Himself down, without any choice or discretion, to link spiritual grace to material rites, apart from the faith of the person observing them,—this, too, is perhaps a *possible* imagination. But had Christ, as the Head of ordinances in His Church, done either the one or the other of these things, He must to that extent have divested Himself of His office as Mediator, or resigned the exercise of it; He must in so far have abdicated His functions as the sole and living and ever-present administrator of grace to His Church; and been shut out from that exclusive and supreme agency which He maintains as the dispenser as well as author of every blessing by which the soul is to be saved.

**3d**, The theory of the Sacraments which ascribes to them an independent virtue or power, is inconsistent with the spiritual liberties of Christ's people.

Such a system brings the soul itself into bondage. It keeps the spirit, which Christ has Himself redeemed, waiting upon man for the communication of the blessings of its redemption; it makes the soul which Christ has ransomed dependent for its freedom on the ministry of a fellow-creature. There cannot be a worse or more abject thraldom than that which subordinates the flock of the Saviour's purchase to any one but Himself, and causes them to hang upon the intention entertained or not entertained by a priest for the enjoyment or forfeiture of spiritual blessing. But even apart from the monstrous doctrine of the Romish Church as to the intention of the priest being necessary to the efficacy of the ordinance, the sacramental theory we have been considering, whether Popish or Tractarian, is inconsistent with the spiritual freedom of those whom Christ has redeemed. That freedom consists in subjection to and dependence on Christ, and none but Christ,—in being emancipated from all dependence on any other except their Saviour,—in being kept waiting, not at the footstool of man for saving blessings, but at the footstool of Christ,—and in being taught to look for all the grace they need day by day, not to the ministry of man's hand, but to the hand of Christ. Spiritual freedom for the believer is bound up with a dependence on Christ immediately and directly, and on Him alone, for every blessing that he needs.[^01.02.21]

[^01.02.21]: [Goode, *Letter to a Lay Friend*, Lond. 1845, pp.\ 18–24. Litton, *Church of Christ*, Lond. 1851, pp.\ 11–13, 202–232, 240\ f.]

**4th**, The sacramental theory we have been considering is inconsistent with the spirituality of the Church, and of the power exercised by the Church for the spiritual good of men.

When, according to that theory, the Sacraments become the instruments of justification and the source of faith, instead of the seal of a justification already possessed, and the exercise and aid of a faith already in existence,—when they are made to come between the soul, in its approach to Christ, and Christ Himself, and communion in the external ordinance is substituted for the fellowship of the Spirit, it is a fatal evidence that the Church, which so teaches and so practises her teaching, although she has "begun in the Spirit," has "sought to be made perfect by the flesh."[^01.02.22] If the external ordinance be made to occupy that place which belongs to the Spirit, and participation in the ordinance be the substitute for faith, the sacramental theory thus reduced to practice will be but the commencement of worse and deeper degradation. It is but the beginning of a course which, consistently followed, must lead to a religion of form and self-righteousness, of sense and sensuous observances, of carnal ordinances and a ceremonial holiness, of outward satisfaction and penances and merit. There will be the priest and the bloodless but efficacious sacrifice, grace conferred by the tricks of a physical or spiritual magic, a religion that manifests itself outwardly and not inwardly, the holiness of houses, and altars, and sacred wood and stone, but not the holiness of the Spirit; the atonement of Sacraments and penances and creature merits, but not the atonement of the Saviour received by faith; a righteousness of bodily discipline and fleshly mortification, but not the righteousness of God imputed to the believer; a justification made out of pains and merits, of sufferings and works, but not a justification freely given by Divine grace and freely accepted by faith; an outward baptism to regenerate the sinner with water at first,—the food of the communion table, made flesh and blood by the consecration of a priest, to sustain the life so begun, and the anointing with oil at last to prepare the soul for the burial. Such are the inevitable fruits of the sacramental theory, consistently carried out in the Church of Christ, making the very temple of God to be the habitation of every carnal and unclean thing.[^01.02.23]

[^01.02.22]: Gal.\ 3:3.

[^01.02.23]: Bellarm. [*Disputationes*]{lang=la}, tom.\ iii. lib.\ ii. cap.\ i.–xxii. Perrone, [*Prælectiones Theologicæ*]{lang=la}, [Parisiis]{lang=la} 1842, tom.\ ii. pp.\ 5–66. Amesius, *Bellarm. Enerv*. tom.\ iii. lib.\ i. cap.\ i.–v. Turrettin, [*Opera*]{lang=la}, tom.\ iii. loc.\ xix. qu.\ i.–ix. Cunningham, *Works*, vol.\ iii. pp.<!-- typo: original="," -->\ 121–133. [Bruce, *Sermons on the Sacraments*, Wodrow Soc. ed. Edin. 1843, pp.\ 11–33. Newman, *Lectures on Justification*, pp.\ 316, etc.; Tract No.\ 90, 2d\ ed. p.\ 13. Wilberforce, *Doctrine of the Holy Eucharist*, 3d\ ed. Lond. 1854, pp.\ 17–38, 97–130. Goode, *Doctrine of the Church of England as to the Effects of Baptism in the case of Infants*, 2d\ ed. Lond. 1850, pp.\ 3–10. *Vind. of the 'Defence of the XXXIX. Art.'* etc., 2d\ ed. p.\ 38\ f. *Unpublished Letter of Martyr to Bullinger*, Lond. 1850, pp.\ 11–13. Martensen, [*Dogmatik*, 4te Aufl. Kiel]{lang=de} 1858, pp.\ 361, 364. Matthes, [*Comparative Symbolik*]{lang=de}, Leipzig 1854, pp.\ 492–510. Thomasius, [*Dogmatik*, 3ter Theil, 2te Abth. Erlangen]{lang=de} 1861, pp.\ 113–135.]
