\sectionmark{Nature and Efficacy of the Sacraments}

## Nature and Efficacy of the Sacraments of the New Testament, and Difference between Them and Non-sacramental Ordinances

\sectionmark{Nature and Efficacy of the Sacraments}

### [Divine institutions]

The Sacraments of the New Testament are Divine institutions appointed by Christ.

It is the positive institution by Christ that sets these ordinances apart to the religious purpose for which they are intended, that makes them significant of spiritual things, and connects them with the virtue or blessing which they are made instrumental to impart. An express Divine appointment is necessary to constitute a Sacrament. In this respect they are similar to the other ordinances which form part of Church worship. Like them, they can claim Divine authority for their institution; and without this authority they would not be Sacraments at all. No observance not ordained by God can properly form any part of His service; far less can any observance not instituted by Him become a sign of His spiritual grace, or a pledge of a blessing which it depends upon His pleasure to give or to withhold. Hence, that any outward institution may answer to our idea of a Sacrament, it must be a positive appointment of God, and made both a sign and a pledge of spiritual blessings, in consequence of His promise and command. Without this, it would be a mere human ordinance, not only destitute of all real religious significance and efficacy, but profanely mimicking the form and character of a Divine ordinance in the Church. This is the first element that goes to make up a Sacrament, and which it has in common with all other ordinances, really forming a lawful or proper part of Divine worship,—namely, that it be of positive appointment by Christ.

### [Sensible signs of spiritual blessings]

The Sacraments of the New Testament are sensible signs of spiritual blessings, teaching and representing by outward actions Gospel truths.

The word or promise of God is an appeal to the understanding only; the Sacraments, embodying the same word or promise in outward and sensible signs, form a twofold appeal, *first*, to the senses, and *secondly*, to the understanding. There is Christ in the Word preached; and in the preaching of the Word, Christ is presented directly to the understanding and heart, and the truth addressed singly to the spiritual nature of man. But Christ is also in the Sacrament administered; and, in the administration of the Sacrament, over and above the same truth taught to the understanding and spiritual nature of man, there is the truth taught to the senses, and impressed by sensible signs upon them. There is a striking similarity between the method God has employed in the Sacraments of the New Testament to embody the Word and promises of Christ, and of a *past* salvation, to the view of His people since His departure, and the method that He employed before Christ's coming to embody the Word and promises of a *future* salvation. Under the Old Testament Church, there were, from the very first, two lines of promise and prediction,—both pointing forward to the coming of the Redeemer, running parallel with each other, and throwing mutual light upon each other's announcements. There was the line of promise embodied in verbal revelation, and there was the line of promise embodied in outward representation or type.

These two revelations ran parallel with each other since the first hour that a revelation was given to man in Paradise concerning the future coming of a Saviour. At that time there was a promise embodied in words, that "the woman's seed should bruise the serpent's head, while His own heel was to be bruised;" and side by side with that verbal announcement, there was the same promise embodied in type through means of the ordinance of sacrifice then appointed. There was Christ in the word of promise, and Christ in the sign of promise. When the promise was renewed to Noah, the second father of the human family, we have again the revelation by word, and the revelation by sensible sign; the covenant was repeated in another form, and the bow was set in the cloud as the outward representation of it. Once more: when Abraham was selected by God to be the depositary of a new development of the promise, we have again that promise embodied in words, and also in outward action; we have the special covenant with Abraham revealed in words, and revealed side by side with the word in the external sign of circumcision; and—to mention no further examples of a practice which must be familiar to every reader of the Old Testament—the whole of the Jewish economy was an exemplification of the two parallel lines that run through every economy of God,—the promise in word and the promise in sign revealed together, and throwing mutual light on each other. The typology of the Old Testament shows us God embodying His promises in signs; the revelation of the Old Testament shows us God embodying the same promises in words; and the Sacraments of the New Testament afford, under the Gospel economy, an exemplification of the same great principle.

The connection between the outward action in the Sacraments and the spiritual blessings to which they stand related is not a mere arbitrary one, arising from positive institution: there is a natural analogy or resemblance between the external signs and the things represented; so that, in the Sacraments of the New Testament, as in the types of the Old, our senses are made to minister to our spiritual advantage, and the outward action becomes the image of inward grace. In the Word, Christ is impressed on the understanding; in the Sacraments, Christ is impressed both on the understanding and the senses. They become teaching signs, fitted and designed to address to the believer the very same truths as are addressed to him in the Word; but having this peculiarity, that they speak at the same time and alike to the outward senses and to the inward thought. In this respect the Sacraments differ from other ordinances of the New Testament Church. Prayer and preaching and praise are ordinances that address themselves to the intellectual and spiritual nature of man alone. They are the expressions and utterances of his intellectual and spiritual being in holding intercourse with God; or they are the means fitted to speak to that nature, and that only, in impressing Divine truth upon men. But in those significant and teaching signs, which we call the Sacraments, Christ is embodied in the ordinance in such a manner as to appeal to the twofold being of man, as made up of body and soul, to minister both to the senses and the understanding; and to speak at once to the outward and inward nature of the believer. In addition to Christ in the Word, we have Christ also in the sign, taught as really in the latter way as in the former, and taught with the advantage of being submitted to the eye, and pictured to the outward senses. This, then, is one important difference between the sacramental ordinances of the New Testament Church and those which are not sacramental.

### [Federal acts sealing the covenant]

The Sacraments of the New Testament are federal acts affording a seal or confirmation of the covenant between God and His people.

This is the main and primary characteristic of sacramental ordinances. They constitute a formal testimony to an engagement entered into by two parties through means, not of words, but of speaking and significant actions,—these actions being the visible witnesses to the engagement, and the outward confirmations of its validity. In other words, they become, according to the expression of the apostle in his Epistle to the Romans, when speaking of one of the Sacraments of the Old Testament, visible "*seals*" of the covenant, and of the blessings contained in it.[^01.01.01]

[^01.01.01]: Rom. 4:11.

There are not a few examples to be found in the Old Testament Scriptures of covenants between man and man ratified by some outward monument, framed or chosen to attest and confirm the transaction. When Jacob parted from his father-in-law Laban, they made a covenant together, and raised a heap of stones and a pillar, to be a memorial of the transaction, and to serve as a witness on both sides to attest their fidelity to the terms of the covenant. "This heap be a witness, and this pillar be a witness, that I will not pass over this heap to thee, and that thou shalt not pass over this heap and this pillar to me, for harm."[^01.01.02] The outward monument or memorial of the covenant entered into between Jacob and Laban was a witness of the engagement, serving to bind the obligation of it more strongly on both parties, and to ratify and confirm, in a formal and significant manner, its validity. And what we find in patriarchal times, we also find, in one shape or other, in every stage of society, some outward sign or significant action being made use of between men to confirm and attest their plighted faith. In addition to the spoken promise or oath, there has been—if not the stone of the times of Jacob—at least the formal signature and solemn deed, and seal attached to the deed, to remain after the verbal engagement, as the witness and ratification of the transaction. Such outward monuments or significant solemnities are intended for the satisfaction of both parties, and to give additional certainty and confirmation to the agreement. And the practice in this respect, which has obtained universally among men, we find to be made use of also by God. There are repeated examples in the Old Testament Scriptures of God ratifying His engagements or covenants with men by means of appropriate signs or solemnities, and making use of these solemnities for the very same purpose that a signed and sealed deed is employed for in the present day, when it attests or confirms a previous engagement, and gives additional security to both parties for the fulfilment of it. That in such a sense the rainbow in the cloud was employed by God, when it became the sign of His covenant with Noah, is very expressly stated by Himself: "And the bow shall be in the cloud; and I will look upon it, that I may remember the everlasting covenant between God and every living creature of all flesh that is upon the earth. And God said unto Noah, This is the token of the covenant, which I have established between me and all flesh that is upon the earth."[^01.01.03] In this point of view the bow was a seal, giving validity and additional security to the covenant then made, and serving as a standing witness for the truth of it. In a precisely similar manner, the rite of circumcision was appointed to Abraham for a voucher of the covenant between God and him. The terms of the institution of the rite would themselves lead us to this conclusion, even had they not been interpreted by the inspired commentary of the Apostle Paul in that sense. "And, God said unto Abraham, Thou shalt keep my covenant therefore, thou, and thy seed after thee in their generations. This is my covenant, which ye shall keep, between me and you, and thy seed after thee. Every man-child among you shall be circumcised. And ye shall circumcise the flesh of your foreskin; and it shall be a *token of the covenant* betwixt me and you." And in reference to this transaction, the Apostle Paul expressly says of Abraham: "And he received the sign of circumcision, *a seal of the righteousness of the faith* which he had yet being uncircumcised."[^01.01.04] The outward act of circumcision, then, was a witness or a seal of the covenant transaction between God and the patriarch, and thus became a voucher to ratify and confirm the validity of it.

[^01.01.02]: Gen. 31:52.
[^01.01.03]: Gen. 9:16–17.
[^01.01.04]: Gen. 17:9–11; Rom. 4:11.

In exact accordance with the practice, universal in one shape or other among men, and expressly sanctioned by the example of God Himself in the Old Testament Church, we affirm that the Sacraments of the New Testament are parts of a federal transaction between the believer and Christ, and visible and outward attestations or vouchers of the covenant entered into between them. In addition to being signs to represent the blessings of the covenant of grace, they are also seals to vouch and ratify and confirm its validity. That the Sacraments of the Christian Church are thus seals of the covenant, appears to be very explicitly asserted, in so far at least as regards the Lord's Supper, in the words of the institution themselves: "*This* cup," said our Lord, "*is the new covenant in my blood, which is shed for you*,"[^01.01.05]—language which seems undoubtedly intended to convey the idea that the element used in the Supper was to be the witness of the new covenant,—a visible seal or security to ratify and vouch for it. No doubt that covenant in itself is sufficiently secure without any such confirmation, resting as it does on the word of God. That word alone, and without any further guarantee, is enough. But in condescension to the weakness of our faith, and adapting Himself to the feelings and customs of men, God has done more than give a promise. He has also given a guarantee for the promise,—has vouchsafed to bestow an outward confirmation of His word in the shape of a visible sign, appealing to our senses, and witnessing to the certainty and truth of the covenant. In the case of the Sacraments, God has proceeded on the same principle as is announced by the Apostle Paul in reference to His oath: "God, willing more abundantly to show unto the heirs of promise the immutability of His counsel, confirmed it by an oath; that by two immutable things, in which it was impossible for God to lie, we might have a strong consolation, who have fled for refuge to lay hold upon the hope set before us."[^01.01.06] The word of promise was itself enough to warrant and demand the belief of God's people. But more than enough was granted: He has not only said it, but also sworn it. By two immutable things—His word and His oath—is the faith of the believer confirmed. The oath is the guarantee for His word. And more than this still: In the visible seal of the Sacraments God would add another and a third witness,—that at the mouth, not of two, but of three witnesses, His covenant may be established. He has not only given us the guarantee of His word, and confirmed that word by an oath, but also added to both the seal of visible ordinances. There is the word preached to declare the truth of the covenant to the unbelieving heart. More than that,—there is the oath sworn to guarantee it. More than that still,—there is the sign administered in order to vouch for all. Christ in the word, unseen but heard, is ours, if we will receive that word with the hearing ear and the understanding heart. Over and above this, Christ, both seen and heard in the Sacrament, is ours, if we will see with the eye or hear with the ear.[^01.01.07]

[^01.01.05]: Luke 22:20.
[^01.01.06]: Heb. 6:17–18.
[^01.01.07]: ["What mister (need) is there that thir Sacraments and seals suld be annexed to the Word? Seeing we get na new thing in the Sacrament but the same thing quhilk we gat in the simple Word, quherefore is the Sacrament appointed to be hung to the Word? It is true certainly, we get na new thing in the Sacrament, nor we get na other thing in the Sacrament nor we gat in the Word; for *quhat mair walde thou crave nor to get the Son of God*, gif thou get Him weil? Thy heart cannot wish nor imagine a greater gift nor to have the Son of God, quha is King of heaven and earth. And therefore I say, quhat new thing walde thou have? For gif thou get Him, thou gettest all things with Him. Quherefore, then, is the Sacrament appointed? Not to get thee a new thing. I say it is appointed to get thee that same thing *better* nor thou gat it in the Word. The Sacrament is appointed that we may get a better grip of Christ nor we gat in the simple Word; that we may possess Christ in our hearts and minds mair fully and largely nor we did of before in the simple Word; that Christ might have a larger space to make residence in our narrow hearts nor we could have by the hearing of the simple Word. And to possess Christ mair fully it is a better thing; for suppose Christ be ae thing in Himself, yet the better grip thou have of Him thou art the surer of His promise."—Bruce<!-- original style:small caps -->, *Sermons on the Sacraments*, Wodrow Soc. ed. Edin. 1843, p.\ 28.]

The Sacraments are the outward and sensible testimony and seal of the covenant, added to the word that declares it. This is the grand peculiarity of sacramental ordinances, separating them by a very marked line from ordinances not sacramental. They are federal acts,—seals and vouchers of the covenant between God and the believer. They presuppose and imply a covenant transaction between the man who partakes of them and God; and they are the attestations to and confirmations of that transaction, pledging God by a visible act to fulfil His share of the covenant, and engaging the individual by the same visible act to perform his part in it. Other ordinances, such as the preaching of the Word, presuppose and attest no such personal engagement or federal transaction between the individual and God. Christ in the Word is preached to all, and all are called upon to receive Him; but there is no personal act on the part of the hearer that singles him out as giving or receiving a voucher of his covenant with his Saviour. But when the same individual partakes of the Sacraments, his own personal deed is an act of covenanting with God; and Christ in the ordinance is made his individually, and he is made Christ's by the very action of partaking of the ordinance. He is singled out by his own voluntary act, if he rightly partakes of the ordinance, as giving a voucher for his engagement with Christ; and Christ Himself gives a voucher of His engagement to the individual; and the visible Sacrament is the seal to the personal and mutual engagement. In this respect, as not only signs but seals of the covenant of grace to the individual who in faith partakes of them, the Sacraments are very markedly distinguished from ordinances not sacramental.

### [Means of grace]

The Sacraments of the New Testament are made means of grace to the individual who rightly partakes of them.

It is carefully to be noted that they presuppose or imply the possession of grace in the case of those who partake of them; but they are also made the means of adding to that grace. They are seals of a covenant already made between the soul and Christ,—attestations of a federal transaction before completed,—confirmations, visible and outward, of engagement between the sinner and his Saviour previously entered into on both sides. They presuppose the existence of grace, else they could not be called seals of it. Just as the signature and seal of some human covenant necessarily presuppose that the covenant exists before they can become vouchers for it, so the seal of God's covenant, affirmed by means of sacramental ordinances, presupposes the existence of that covenant as already subsisting between God and the rightful participator in the ordinance. But although grace exists in the soul before, the Sacraments are made to those who rightly receive them the means of increasing that grace, and communicating yet more of spiritual blessing. They serve to strengthen the faith of those who already believe, and add to the grace of those who previously possessed grace. They become effectual means of imparting saving blessings in addition to those enjoyed before.[^01.01.08] In this respect they are similar to the other ordinances which Christ has appointed in His Church, and which by His power and Spirit are made instrumental in advancing the interests of His people. But from the very peculiarity that attaches to their distinctive character, as seals of a personal covenant between God and the believer, Sacraments may reasonably be supposed to be more effectual than non-sacramental ordinances in imparting spiritual blessings. The spiritual virtue of Sacraments is more and greater than other ordinances, just because, from their very nature, they imply more of a personal dealing between the sinner and his Saviour than non-sacramental ordinances necessarily involve.

[^01.01.08]: ["The Church has always seen in the Sacraments," says Mr. Liddon in his recent very valuable work on the Divinity of our Lord, "not mere outward signs addressed to the taste or imagination, nor even signs, as Calvinism asserts, which are tokens of grace received independently of them, but signs which, through the power of the promise and Word of Christ, effect what they signify." For this very defective statement of the Calvinistic doctrine of the Sacraments the only authority Mr. Liddon gives is a single secondhand quotation from Cartwright. He then proceeds to contrast with this supposed Calvinistic view the words of the 25th Article: "The Sacraments are *effectual* signs of grace and God's goodwill toward us, by which He doth work invisibly in us;" and the definition of the Church Catechism: "A Sacrament is an outward and visible sign of an inward and spiritual grace given unto us, ordained by Christ Himself as a *means whereby* we receive the same, and a pledge to assure us thereof." *Bampton Lectures*, 1866, p.\ 721. A very slight reference to the symbolical books or the leading theologians of some of the Calvinistic Churches would of course have shown that all these phrases have been constantly used by them with respect to the Sacraments. The isolated sentence from Cartwright adduced by Hooker, from whom Mr. Liddon takes it, refers to a particular aspect of a particular Sacrament; it was never designed to be a full definition of the efficacy of these ordinances in a typical case. Moreover, the passage in question is just a translation of Calvin, *Inst.* iv.\ xv.\ 22. It might as well, therefore, have been brought forward as expressive of *his* whole doctrine on the subject. But Mr. Liddon must surely be aware that Calvin constantly speaks of the Sacraments both of the Old and New Testaments as "*effectual* means of grace," "efficacious instruments," "signs in which God *gives* what He holds out to us," etc. ("[non modo salutaria exercitia, et adjumenta pietatis, sed etiam *efficacia gratiæ instrumenta*]{lang=la}." "[*Præstat* igitur vere Deus quicquid signis promittit ac figurat; nec effectu suo carent signa, ut verax et fidelis probetur eorum Author]{lang=la}").—*Comment. in* Gal.\ 5:9, Col.\ 2:17, *Inst.* iv.\ xiv.\ 17, etc. Cf. i. *Conf. Helv.* c.\ 21, ii. c.\ 21. Conf. Gall. Art.\ 37, Catech. Gen. v. etc. Some of the expressions in the Church Catechism, indeed, with respect to Baptism seem to Presbyterians to require at least all the explanation which Dean Goode and others have bestowed upon them. And the passage from Martensen about the "communication of Christ's glorified corporeity" in the Lord's Supper, which Mr. Liddon quotes, seemingly as supplementary of the Catechism, would of course be disapproved of by Calvinists generally, although there are statements in the works of Calvin himself which might perhaps be adduced in its favour. Mr. Liddon concludes by observing that, "though there have been and are believers in our Lord's Divinity who deny the realities of sacramental grace, experience appears to show that their position is only a transitional one." There is "a law of fatal declension," which will ultimately, Mr. Liddon thinks, bring all who do not hold the High Church doctrine of the Sacraments to the Socinian position. "Centuries," however, "may intervene between the premisses and the conclusion;" so that the prediction is a singularly safe one. By a precisely similar process of reasoning, Dr.\ Manning and others are prepared to prove that there is an indissoluble connection between the worship of the virgin and a belief in the Divinity of Christ.—*Engl. and Christend.* p.\ civ. Faber, *Growth in Holiness*, p.\ 72.]

What is the nature and extent of the supernatural grace imparted in Sacraments,—in what manner they work so as to impart spiritual benefit to the soul, it is not possible for us to define. As visible seals of God's promises and covenant, we can understand how they are naturally fitted, in the same way as the vouchers of any human engagement or covenant are naturally fitted, to attest and confirm them. But beyond this, all is unknown. The blessing of Christ and the working of His Spirit in Sacraments we cannot understand, any more than we can understand the operation of the same supernatural causes in respect of other ordinances. They have a virtue in them beyond what reason can discover in them, as naturally fitted to serve the purposes both of signs and seals of spiritual things. They have a blessing to the right receiver of them, not their own to give. "They are made effectual means of salvation, not from any virtue in them, or in him that doth administer them, but only by the blessing of Christ, and the working of His Spirit in them who by faith receive them."[^01.01.09] In this respect their power and virtue are not more and not less mysterious than those of ordinances non-sacramental.

[^01.01.09]: Shorter Catechism, qu.\ 91.

Such are the general conclusions which a consideration of the nature of the Sacraments of the New Testament lead us to acquiesce in. They are Divine institutions appointed by Christ; they are signs and significant representations of spiritual things; they are seals and vouchers of a federal transaction between God and the worthy receiver of Sacraments; they are the means for applying spiritual grace to the soul. To sum up the discussion in the language of the Shorter Catechism: "A Sacrament is an holy ordinance instituted by Christ, wherein by sensible signs Christ and the benefits of the new covenant are represented, sealed, and applied to believers."[^01.01.10]

[^01.01.10]: Shorter Catechism, qu.\ 92. Calvin, *Inst.* lib.\ iv. cap.\ xiv. [*Consensus Tigurinus*]{lang=la} in Niemeyer's [*Collectio Confess.* Lipsiæ]{lang=la} 1840, pp.\ 192–217, translated in Calvin's *Tracts*, Edin. 1849, vol. ii. pp. 205–244. Turrettin, *Opera*, tom. iii. loc. xix. qu. i.–ix. Cunningham, *Works*, vol. i. pp. 225–291, vol.\ ii. pp.\ 201–207, vol.\ iii. pp.\ 121–133. Amesius, *Bellarm. Enerv.* tom.\ iii. lib.\ i. cap.\ i. Willison, *Works*, Hetherington's ed. pp.\ 456\ f. Gillespie, *Aaron's Rod Blossoming*, B.\ iii. chap,\ xii.–xiv. Mastricht, *Theol. Theoretico-Pract.* tom.\ ii. lib.\ vii. cap.\ 3.

Sacraments and non-sacramental ordinances are like each other in two respects; and in two respects they differ. In the first place, sacramental and non-sacramental ordinances agree in this: first, that they are both positive institutions of Christ; and second, that they are both means of grace to believers. Without a Divine warrant and institution, neither non-sacramental ordinances nor Sacraments could have any place in the worship of God as part of His service; and both are therefore Divine appointments. They are both likewise means of grace to believers,—there being a positive promise attached to the right use of them, and that promise being fulfilled in the bestowment of spiritual blessing in connection with their use. This spiritual benefit, linked to the proper use of ordinances, whether sacramental or not, is over and above and quite distinct from the natural or moral influence such ordinances may have to benefit those who employ them. There is a benefit, for example, which the ordinance of preaching the Word is naturally fitted to impart, because the truth preached is adapted to man's moral and intellectual nature, and so naturally fitted to be of advantage to the hearers. In like manner there is a benefit which Sacraments are naturally fitted to impart, because they are symbolical ordinances or teaching signs; and the truths represented or taught by them are, upon the very same principle, naturally fitted to be of advantage to the receiver. But in both cases there is a blessing distinct from and additional to the natural or moral effect of the Word preached or the Sacraments administered. There is the work of the Spirit making use of Word and Sacrament to reach the understanding and the heart, and to convey to the worthy hearer or worthy receiver a spiritual blessing. And this work of the Spirit, over and above the natural effect of the truth received, is a mystery, both in the case of the ordinance of preaching and the ordinance of the Sacraments; and not, I think, a greater mystery in the one case than in the other.

We do not plead for the Sacraments as means of grace, viewed merely as natural actions and ceremonies apart from the truths which they represent, any more than we would plead for the preaching of the Word being a means of grace, viewed as the mere letter of the Word apart from the meaning of the truth which is uttered. The case of *infant* Baptism, which is, as we shall afterwards see, in some respects exceptional, and not to be taken as completely bringing out the full and primary idea of the Sacrament,[^01.01.11] we for the present put aside, postponing it for future consideration. But in the case of adult participation in the Sacraments, we do not plead for these generally as means of grace, when viewed simply as outward acts, and apart from the truths represented, any more than the sound of the Word preached would be a means of grace apart from the intelligent apprehension of it. Through the truths, however, in one case impressed on the hearer by significant words, and in the other case impressed on the participator through significant actions, the Spirit of God *does* operate upon the intellectual and moral nature of man, making both the one ordinance and the other a means of grace. How the Spirit thus operates and imparts of His gracious gifts, we cannot tell in the one instance more than in the other. What is the mode or measure of His communications of a spiritual kind, over and above the natural or outward influence of the truth, we cannot tell. It is His own secret and supernatural work, known and recognised by the believer in the effects wrought on His soul, both in the case of the Word preached and the Sacraments administered, but not to be explained or defined in the manner of working. Let it never be forgotten that there is a mystery not to be explained whenever we get beyond the natural effect of the ordinance, whether sacramental or not, necessarily resulting from the fact that it is an effect of the Spirit, and not of any natural cause. All ordinances, as means of grace, must in that character have something in them mysterious and inexplicable. We cannot rid ourselves of the mysterious by simply ridding ourselves of sacramental ordinances,—as very many in the present day seem to imagine. We can only disconnect all mystery from the ordinances of the Church when we limit their efficacy simply to their natural influence, and deny the influence of the Spirit of God as at all connected with them.

[^01.01.11]: Cunningham, *Works*, vol.\ iii. pp.\ 144–154.

In the second place, Sacraments differ from ordinances not sacramental in the New Testament Church, in these two things: first, they are sensible signs of spiritual truths; and second, they are seals or vouchers of a federal transaction. In respect that they are sensible exhibitions and significant actions, having a definite meaning in them, Sacraments stand out distinctly marked from other ordinances. Speaking generally, sacramental ordinances are spiritual acts of the mind or soul embodying themselves in outward and sensible actions, in so far as regards the part of the receiver in the ordinance. They are outward representations, by means of certain actions on the part of the worthy participator, of the great fact that he gives himself to Christ according to the terms of the covenant of grace. In partaking of the ordinance, he embodies in the sensible actions of the ordinance a spiritual surrender of himself to Christ, in the manner and upon the terms which Christ has appointed. This is the receiver's part in the ordinance. On the other side, Christ, through the person of the administrator of the ordinance, embodies in the actions of it a picture or representation of a spiritual communication of Himself and all the blessings of His grace to the worthy receiver. Christ, in the Sacrament, and by means of its sensible signs, gives Himself and the benefits of the new covenant, spiritually, although under an outward representation, to the believing participator. The outward signs of the Sacrament exhibit, then, a twofold action: the believer giving himself to Christ in covenant, and Christ giving Himself to the believer in the same covenant. There is a spiritual act on the part of the believer embodied in outward representation,—the act, namely, of his surrendering of himself to Christ in the way and on the terms which Christ has appointed; and there is a spiritual act on the part of Christ embodied in outward representation also,—the act, namely, of Christ with all His precious and unspeakable blessings communicating Himself to the soul of the worthy receiver. There is thus a double significance comprehended in the administration and in the participation of the sacramental ordinance, each of them having a definite and intelligible meaning of its own. In the administration of the Sacrament, Christ makes over Himself and all the benefits of His atonement to the believer, and accepts in return the believer as His. In the participation of the Sacrament on the part of the worthy receiver, he makes over himself to Christ; and receives, in return for his own soul, Christ and His covenant blessings. The double action of the administration and participation of the Sacrament is the embodiment in outward sign of a double spiritual act. There is a mutual intercommunication spiritually of Christ and the believer embodied and represented in action,—a covenant interchangeably exhibited in sensible signs, whereby Christ becomes the believer's, and the believer becomes Christ's. In their being signs of spiritual truths, Sacraments differ in a marked manner from non-sacramental ordinances.

Sacraments differ also from other ordinances in this, that they are seals or vouchers of a federal or covenant transaction. This, after all, is the grand and essential distinction between sacramental and non-sacramental ordinances. As a kind of types, as speaking and teaching signs, they are fitted to express, by the help of significant actions cognisable by the senses, the twofold spiritual act of Christ making over Himself and all His blessings to the believer, and of the believer making over himself with all his poverty and sins to Christ. But they are more than signs of a covenant thus entered into between the two parties,—they are seals and vouchers for the covenant, serving to give confirmation and validity to the engagement, as one never to be broken. In the Sacraments there is a twofold seal, as well as a twofold action, represented. There is a seal on the part of Christ, and there is a seal on the part of the believer. In marvellous condescension to our infirmity and unbelief, Christ has been pleased to add to the promise of His covenant an outward and visible voucher for it,—thereby, as it were, binding Himself doubly to the fulfilment of it, and pledging Himself, both by word and by sign, to implement all its terms. And in the worthy receiving of the Sacrament, the believer gives also a visible voucher for his part of the engagement,—thereby placing himself under new and additional obligations to give himself to Christ, and adding the outward seal to ratify the inward pledge of his heart. The covenant is mutual, and the seal is mutual. Without either part of the covenant transaction, the Sacrament would be incomplete. Withdraw Christ from the ordinance as both entering into covenant with the believer and giving him a seal of it,—take away Christ sealed to the soul in the Sacrament,—and the ordinance is reduced to a bare sign of spiritual blessing, having, perhaps, a certain natural effect by signifying truth, but empty and destitute of all spiritual grace. Or withdraw the believer from the ordinance in so far as he really by means of it gives himself to Christ,—take away the spiritual act by which the worthy participator surrenders his soul to the Saviour through his outward participation of the Sacrament,—and the Sacrament is made to be a charm, in which Christ and grace are communicated apart from the spiritual act or state of the receiver. Abstract from the ordinance the act of Christ covenanting with the believer and giving to the soul Himself and His blessings, and the remaining portion of the ordinance may continue,—the believer may still be accounted as giving himself to Christ in the Sacrament; but in the absence of Christ's act there is no spiritual blessing given in return, and the believer's act of participating in the Sacrament becomes a mere sign of adherence to Christ on his part, and nothing more than a sign.[^01.01.12] Again, abstract from the ordinance the act of the believer spiritually covenanting with Christ and giving his soul in faith to the Saviour, and the remaining portion of the ordinance may continue,—Christ may be held as present in the Sacrament giving Himself and His supernatural grace; but in the absence of the receiver's act surrendering his soul in faith to his Saviour, the communication of spiritual grace is degraded to the position of being the result of a charm or talismanic formula,—something effected, [*ex opere operato*]{lang=la}, apart from the spiritual character or faith of the receiver. It is only when the separate spiritual acts of both parties meet and combine in one transaction, that the covenant is real or complete; or that the ordinance, as a seal of the mutual engagement, is a true and proper Sacrament. As the voucher or seal of a real covenant, spiritually entered into between Christ and the believer through the ordinance, a Sacrament differs, in a very marked and important way, from ordinances not sacramental.

[^01.01.12]: ["[Quod omnes fere opinantur, hoc ritu, quem Sacramentum appellant, confirmari saltem fidem nostram, ne id quidem verum censeri debet; cum nec ullo sacro testimonio comprobetur, nec ulla ratio sit cur id fieri possit. Quomodo enim potest nos in fide confirmare id *quod nos ipsi facimus, quodque, licet a Domino institutum, opus tamen nostrum est?*]{lang=la}"—Faustus Socinus, *De Cœnâ Dom. Tract. Brev.* Racovian Catechism, 1609, p.\ 144\ f.]
