## The Modes of Baptism

Before passing altogether from the subject of Baptism, it may be desirable briefly to consider the mode or modes in which the ordinance may lawfully be administered. It may seem, indeed, at first sight, a question of no great importance whether we baptize by sprinkling or by immersion,—the former being the method adopted by almost all Protestant Churches and by Western Christendom generally, the latter prevailing to a great extent in the early centuries, and still practised largely in the East. The almost unanimous opinion of orthodox theologians has always been, that Baptism in the name of the Trinity was equally valid in whichever of the two ways referred to it was administered. The position, however, taken up in our own day by many of the advocates of Baptism by immersion has given to the question an importance not properly belonging to it.[^02.06.01] The Evangelical Baptists in America, for example,—a numerous and energetic denomination,—deny the validity of Baptism by sprinkling, and declare that all persons thus baptized are living in open sin, should not be regarded as members of the Church of Christ, nor be admitted to the Lord's table. Further, they aver that the English authorized version of the Scriptures is false and unfaithful on the subject of Baptism,—purposely so, many of them add. They have issued accordingly a translation of their own with the requisite changes, and consider,—to use the words of a resolution of the Baptist American and Foreign Bible Society,—"That the nations of the earth must now look to the Baptist denomination *alone* for faithful translations of the Word of God."[^02.06.02]

[^02.06.01]: ["How abundant and copious in the faculty of lying and inventing of errors the spirit of Anabaptism was of old,—how much superior in an extremely malignant fruitfulness he hath been to any evil spirit that ever appeared in the Christian Church before him,—we have, I hope, demonstrated in our first two chapters (which contain a formidable catalogue of the errors and heresies prompted by the said spirit). That the younger Anabaptists who now trouble the Church of England are nothing inferior to their fathers in the art of erring, being sure, wherever they are ashamed of any one of their predecessors' tenets, to give us two much worse in the place thereof, we have endeavoured to make appear in our third and fourth chapters. Among the new inventions of the late Anabaptists, there is none which with greater animosity they set on foot than the necessity of dipping over head and ears—than the nullity of affusion and sprinkling in the administration of Baptism. Among the old Anabaptists, or these over sea to this day, so far as I can learn, by their writs, or any relation that has yet come to my ears, the question of dipping and sprinkling came never upon the table. .\ .\ . The question about the necessity of dipping seems to be taken up only the other year by the Anabaptists in England, as a point which alone, as they conceive, is able to carry their desire of exterminating infant Baptism; for they know that parents upon no consideration will be content to hazard the life of their tender infants by plunging them over head and ears in a cold river. Let us, therefore, consider if this sparkle of new light have any derivation from the lamp of the Sanctuary, or the Sun of righteousness,—if it be according to scriptural truth, or any good reason."—Baillie, *Anabaptism*, Lond. 1647, p.\ 163.]

[^02.06.02]: Beecher, *Baptism with ref. to its Import and Modes*, New York 1849, pp.\ 117–120.

Our translators, in point of fact, seeing that they had to frame their version of the Bible in the very heat of a controversy about Baptism, strove carefully to stand neutral on the subject. They simply gave the Greek word an English dress; instead of [βαπτιζω]{lang=el} and [βαπτισμα]{lang=el}, they wrote "baptize" and "baptism," thereby deciding nothing either way.

The real question at issue has been very clearly stated by President Beecher, to whose valuable work on the Mode of Baptism I would refer you for an exceedingly able and exhaustive discussion of this whole subject. "The case," he says, "is this: Christ has enjoined the performance of a duty in the command to baptize. What is the duty enjoined? or, in other words, What does the word '*baptize*,' in which the command is given, mean? One of two things must be true: Either it is, as to mode, *generic*, denoting merely the production of an effect (as purity), so that the command may be fulfilled in many ways; or it is so *specific*, denoting a definite mode, that it can be fulfilled in but one. To illustrate by an analogous case, Christ said: 'Go, teach all nations.' Here the word *go* is so generic as to include all modes of going which any one may choose to adopt. If a man walks, or runs, or rides, or sails, he equally fulfils the command. On the other hand, some king or ruler, for particular reasons, might command motion by a word entirely specific, as, for example, that certain mourners should *walk* in a funeral procession. Now it is plain that such a command could not be fulfilled by riding or by running, for, though these are modes of going, they are not modes of walking, and the command is not to go in general, but specifically to walk. .\ .\ . So likewise, when Christ said, '*baptize*,' He either used a word which had a generic sense, denoting the production of an effect, in any mode, such as 'purify,' 'cleanse;' or a specific sense, denoting a particular mode, such as 'immerse,' 'sprinkle,' 'pour.'"[^02.06.03]

[^02.06.03]: Beecher, p.\ 3. 

Now the scriptural meaning of the term [βαπτιζω]{lang=el}, I believe there is abundant evidence to show, is generic and not specific; it denotes the production of an effect which can be brought about equally well in more ways than one. The adherents of Baptist views, on the other hand, consider that the word is so specific in its signification as to fix down the lawful performance of the duty enjoined to one method only; they hold that "in Baptism the mode is the ordinance; and if the mode is altered, the ordinance is abolished."[^02.06.04]

[^02.06.04]: *Prim. Church Magazine*, Oct. 1844, quoted by Wilson, *Inf. Bapt.* p.\ 4.

The word [βαπτω]{lang=el}, from which [βαπτιζω]{lang=el} is derived, was long maintained by Dr.\ Gale and other advocates of the Baptist theory to have one meaning, and only one, alike in classic, Hellenistic, and ecclesiastical Greek. It meant, they held, to immerse or dip; and it never meant anything else. This view, however, was with good reason abandoned by Dr.\ Carson, probably the ablest defender of the Baptist theory in our own days. It is now very generally admitted by our opponents on this question that [βαπτω]{lang=el} has at least two meanings; *first*, to immerse, and *second*, to dye or colour. The same is true of the Latin "[tingo]{lang=la}," and various similar words in other languages. It will not therefore be thought improbable that the derivative [βαπτιζω]{lang=el} should also have a primary and a secondary meaning. In point of fact, we find that, especially in later Greek, while often denoting to immerse or overwhelm, it means also, in many cases, to wash, sprinkle, cleanse.[^02.06.05] It is natural, however, to suppose that when transferred from common to ecclesiastical use, and applied in Scripture to a religious ordinance which is confessed by all parties to symbolize regeneration or spiritual purification, the meaning of the word might undergo some change. The question therefore comes to be, What is the [*usus loquendi*]{lang=la} of the New Testament as regards the term [βαπτιζω]{lang=el}? Looking, then, to all the passages in which the word occurs, it becomes plain, I think, that the only meaning which will carry us consistently through all of them is that of purification or cleansing. It is perfectly clear that whatever signification of the word we adopt, we must adhere to it throughout. It is quite true that [βαπτιζω]{lang=el} may have, and has, more meanings than one in ordinary Greek; but that is when it is applied to different things, and used under different circumstances. It can have but one meaning when used with respect to one definite appointment or rite, and under the same circumstances. This test can be easily applied to the various interpretations of the word in question. Take, for example, the first passage in the New Testament in which the term baptize occurs, the third chapter of Matthew, and substitute for it first the rendering which I have adopted, and then that of our Baptist brethren. It is not difficult, I think, to see which of the two best suits the whole scope of the passage: "Then went out unto John Jerusalem, and all Judæa, and all the region round about Jordan, and were purified (immersed, or plunged) of him in Jordan, confessing their sins. But when he saw many of the Pharisees and Sadducees come to his purification (immersion, or plunging), he said, .\ .\ . I indeed purify (immerse or plunge) you with water unto repentance: but He that cometh after me is mightier than I, whose shoes I am not worthy to bear: He shall purify (immerse or plunge) you with the Holy Ghost, and with fire. .\ .\ . Then cometh Jesus from Galilee to Jordan unto John, to be purified (immersed or plunged) of him. But John forbade Him, saying, I have need to be purified (immersed or plunged) of Thee, and comest Thou to me? And Jesus answering said unto him, Suffer it to be so now: for thus it becometh us to fulfil all righteousness."[^02.06.06]

[^02.06.05]: Beecher, 40–47, 158–176, 185–202, etc.

[^02.06.06]: Matt.\ 3:5–15.

That such a transition of meaning should have taken place in the case of the word [βαπτιζω]{lang=el}, appears very natural when we consider the historical circumstances connected with it. It is repeatedly used in the Septuagint, and in the works of Jewish writers who employed the Hellenistic or Alexandrian dialect, to denote the ceremonial immersions, washings, and sprinklings with water, blood, or ashes, common among the Jews. These "divers baptisms," as the Apostle Paul calls them,[^02.06.07] were all practised for the sake of purification, legal or ceremonial. The two ideas, of "baptizing" and of "purifying," were therefore constantly associated in the minds of the Jewish people; and nothing seems more natural than that in the course of time the one should pass into the other, and the words come to be used as synonymous. To recur to the history of the kindred word already alluded to: Men dipped objects in liquid in order to impart colour to them; and [βαπτω]{lang=el} came to signify "to dye." The Jews immersed, or washed, or sprinkled, in order to attain purity; and so [βαπτιζω]{lang=el} came to mean "to purify." In Jewish ecclesiastical language, considerably before our Lord's time, [βαπτιζω]{lang=el} seems to have dropped all reference to mode, and to have become a general term for purifying, practically equivalent to [καθαριζω]{lang=el}. A remarkable confirmation of this may be found in the third chapter of John. We are there told that a dispute had arisen between the disciples of John the Baptist and a Jew (as the true reading seems to be; not Jews as in the A.\ V.) "about *purifying*" ([περι καθαρισμου]{lang=el}). Now this dispute, as is shown by the context, was simply about the respective *Baptisms* of John and of Christ. The followers of the former were jealous on their master's behalf of the seemingly rival claims of our Lord, which had apparently been urged against them by this Jew. "They came unto John, and said, Rabbi, He that was with thee beyond Jordan, to whom thou barest witness, behold, the same *baptizeth*, and all men come unto Him."[^02.06.08] The "question about purifying" was just a "question about baptizing;" and the Evangelist uses the words interchangeably, just because in the ecclesiastical language of his day the two meant the same thing.[^02.06.09]

[^02.06.07]: Heb.\ 9:10, [διαφοροι βαπτισμοι]{lang=el}.

[^02.06.08]: John\ 3:23–26.

[^02.06.09]: Beecher, pp.\ 22–25, 213\ ff.

The evidence by which the position which I have laid down on this subject can be still further established and strengthened, is of a cumulative sort, and for the details of it I must refer you to such works as that by Dr.\ Beecher, already referred to.[^02.06.10] With respect to the apostolic practice in this matter, I am disposed to agree with the author last named, that "it is not possible *decisively* to prove the mode used by the Apostles; for if going to rivers, going down to the water and up from it, etc., create a presumption in favour of immersion; so does the Baptism of three thousand on the day of Pentecost in a city where water was scarce, and of the jailor (and his household) in a prison, create a presumption in favour of sprinkling. And if a possibility of immersion can be shown in the latter cases, so can a possibility of sprinkling or pouring be shown in the former. The command being to purify, and the facts being as stated, the decided probability is, that either sprinkling, pouring, or immersion, was allowed, and Christian liberty was everywhere enjoyed. A tendency to formalism led to a misinterpretation of Paul in Rom. 6:3–4, and Col. 2:12; and this gave the ascendency to immersion, which increased (in the postapostolic Church) until it became general, though it was not insisted on as absolutely essential on philological grounds."[^02.06.11]

[^02.06.10]: Ibid. pp.\ 211–224, etc.

[^02.06.11]: Ibid. p.\ 114.

In conclusion, I remark, that many take up what appears to me a wrong ground on this question, in seeking first to prove that the word [βαπτιζω]{lang=el}, in the whole wide field in which it occurs, sometimes means to immerse, sometimes to wash, sometimes to sprinkle or pour; and then drawing from that the inference that we may lawfully baptize in any of these ways. It may be perfectly true that in profane literature the word has several meanings, but it by no means follows from that fact that, when used ecclesiastically, and applied definitely to one thing, it has more meanings than one. As employed to denote a definite religious rite, the term *Baptism* must have but one definite signification. And whatever we hold that to be, we must adhere to it throughout, and in all cases in which the word occurs. The true meaning of Baptism in the New Testament I believe to be purification or cleansing. That purification may be effected either by sprinkling or by immersion, according to the dictates of Christian expediency. The command to baptize is a generic command, which may be carried out in either way with equal lawfulness.[^02.06.12]

[^02.06.12]: Beecher, *Baptism with reference to its Import and Modes*, New York 1849. Williams, *Antipæd. Exam.* vol.\ ii. pp.\ 2–189. Wardlaw, *Dissert. on Inf. Baptism*, 3d\ ed. pp.\ 163–182. Wilson, *Inf. Baptism*, pp.\ 9–186. With respect to the evidence of the Fathers as to the matter of fact of infants being baptized in the early Church in postapostolic times, I may refer to Wall's *History of Inf. Baptism*, 3d\ ed., Lond. 1720, a very complete and reliable work; Williams, vol.\ ii. pp.\ 200–228. Neander was the first theologian of any eminence to maintain, though not very confidently, that infant Baptism was a novelty of the third century. (*Hist.* Torrey's Transl., Edin. 1847, vol.\ i. pp.\ 424–429; *Planting of the Christian Church*, Ryland's Transl., Edin. 1842, vol.\ i. pp.\ 189–194.) He has been followed in this to some extent by Gieseler, by Hagenbach, and others in Germany; and by some English Churchmen. What Neander chiefly builds upon to establish his view of the matter is the well-known statement of Tertullian, which has been usually held, and, I think, with good reason, to prove the very contrary. Tertullian,—speaking, be it observed, of the practice of the Church at the end of the second century and the very beginning of the third,—advises that with respect to several classes Baptism should be deferred: so of unmarried persons and widows; so in particular of infants. He urges this, not on the ground of its being unscriptural or a novelty, but on the ground of reason and expediency. "It would be *more useful* to delay." ([Cunctatio Baptismi utilior est.]{lang=la}) "Why does that innocent age hasten to the remission of sins? Men act more prudently in worldly matters. Why should the Divine heritage be intrusted to those to whom we would not commit the keeping of their earthly goods?" etc.—*De Baptismo*, cap.\ 18. It is surely very plain that we have here just a specimen of that tendency to exaggerated and unscriptural views of the Sacraments which so soon and so fatally prevailed in the Christian Church. When Baptism came to be regarded as a magic charm to wash away guilt whenever it was applied, the idea was a very natural one that the wisest course was to reserve it as long as possible. Hence the frequency of deathbed Baptisms, as in the case of Constantine; and hence Tertullian's argument, that children in "the guiltless age" of infancy had less need of the ordinance than in after years.
