## The Efficacy of Infant Baptism

The efficacy of Baptism in the case of adults may be understood from what has been already said of the nature of the Sacraments in general. Baptism, like the Lord's Supper, is a sign and seal of a federal engagement between the receiver and Christ. It presupposes the existence of justifying and saving grace in the person baptized; and it seals or attests that grace to the soul, in this manner becoming the means of further grace.

There is a meaning in the fact that the person receiving the Sacrament has a part to perform in the ordinance,—that in the Lord's Supper he personally takes and partakes of the elements of bread and wine, and that in Baptism he personally submits himself to and receives the sprinkling of water. In both Sacraments there is a personal act on the part of the participator, which has its spiritual meaning, which cannot and ought not to be overlooked in the transaction. That act forms the link that connects the receiver of the ordinance with the ordinance itself; and the spiritual faith embodied in the act forms the link which connects his soul with the covenant blessings which the ordinance represents. The Sacrament is a seal, then, of more than the covenant generally; it is a seal of the covenant in its appropriation by the believer to himself personally in the ordinance.

There are some theologians indeed who in their explanation of the Sacraments make them seals of the covenant in general, and not seals of the believer's own personal interest in the covenant. They make the Sacraments attestations vouching for God's promises of grace at large, but not vouching for those promises as appropriated by the believer and realized in the experience of the worthy receiver of the Sacrament. This explanation of the Sacraments, however, is, I think, much too narrow and limited. It overlooks the personal act of the receiver in the Sacrament, and the spiritual meaning of that act. It disowns or neglects as not essential to the ordinance, the part which the participator has to perform, when in the case of the Lord's Supper he personally takes of the bread and wine, or when in the case of Baptism he personally presents himself to be sprinkled with water in the name of the Trinity. There is a spiritual meaning in these personal acts not to be overlooked in our explanation of the Sacraments, and essential to a right understanding of them. These personal acts constitute the part performed by the believer in the covenant transaction between him and Christ in the ordinance, and are necessary to make up the covenant. And the Sacrament, as a seal, is applicable to that part of the covenant transaction by which the believer appropriated the blessing to himself, not less than to that other part of the covenant transaction by which Christ exhibits or makes offer of the promise of grace to the believer. In other words, the Sacrament is not merely a seal of the covenant offered, or exhibited, or declared in general, but a seal of the covenant appropriated by the believer in particular, and, through means of his own spiritual act in the ordinance as well as Christ's, received in his personal experience.

In the case of Baptism administered to a believing adult, his own personal part in the ordinance, when he presents himself to the sprinkling of water, is the sign of that spiritual act of his through which the blessings of justification and regeneration, represented in the Sacrament, have previously become his; and Baptism is to him a seal not merely of these blessings as exhibited and promised in the covenant generally, but of these blessings realized and enjoyed by himself. Through the channel of his faith, and by means of the Spirit in the ordinance, Baptism becomes a seal in his justification and regeneration, and so a means of grace and spiritual blessing to his soul.[^02.05.01]

[^02.05.01]: Turrettin, *Op.* tom.\ iii. loc.\ xix. qu.\ xix.

Such is the efficacy of Baptism administered to an adult believer. What is the virtue or efficacy of the ordinance when administered to infants incapable of faith, although not incapable of being made partakers in the grace which the Spirit confers? In entering on the consideration of this delicate and difficult subject, it is necessary, in order to clear our way to it, to lay down one or two preliminary propositions of much importance in the discussion.

*First*, The proper and true type of Baptism, as a Sacrament in the Church of Christ, is the Baptism of adults, and not the Baptism of infants. In consequence of the altered circumstances of the Christian Church at present, as compared with the era when Baptism was first appointed, we are apt to overlook this truth. The growth and prevalence of the visible Church, and the comparative fewness of the instances of adult conversion to an outward profession of Christianity amongst us, have led to the Baptism of infants being almost the only Baptism with which we are familiar. The very opposite of this was witnessed in the Church of Christ at first. And the true type of Baptism, from examining which we are to gather our notions of its nature and efficacy, is to be found in the adult Baptisms of the early days of Christianity, and not in the only Baptism commonly practised now in the professing Church, the Baptism of infants. It is of very great importance, in dealing with the question of the nature and efficacy of Baptism, to remember this. Both among the enemies and the friends of infant Baptism the neglect of this distinction has been the occasion of numberless errors in regard to the import and effects of the Sacrament. Men have judged of the nature and efficacy of Baptism from the type of the ordinance, as exhibited in the case of baptized adults. They have reversed the legitimate order of the argument, and argued from the case of infants to that of adults, and not from the case of adults to that of infants. It is abundantly obvious that adult Baptism is the rule, and infant Baptism the exceptional case; and we must take our idea of the ordinance in its nature and effects not from the exception, but from the rule. The ordinance of Baptism is no more to be judged of from its ministration to children, than is the ordinance of preaching to be judged of from its ministration to children. The Sacrament in its complete features and perfect character is to be witnessed in the case of those subjects of it whose moral and intellectual nature has been fully developed and is entire, and not in the case of those subjects of it whose moral and intellectual being is no more than rudimental and in embryo. Infants are subjects of Baptism in so far as, and no farther than their spiritual and intellectual nature permits of it. And it is an error, abundant illustration of which could be given from the writings both of the advocates and opponents of infant Baptism, to make Baptism applicable in the same sense and to the same extent to infants and to adults, and to form our notions and frame our theory of the Sacrament from its character as exhibited in the case of infants. It is very plain, and very important to remember, that the only true and complete type of Baptism is found in the instance of those subjects of it who are capable both of faith and repentance, not in the instance of those subjects of it who are not capable of either. The Bible model of Baptism is adult Baptism, and not infant.

*Second*, The virtue of infant Baptism, whatever that may be, is not more mysterious than the virtue ascribed to adult Baptism, although it may have the appearance of being so. It is a very common idea, that the difficulty in framing an explanation of the efficacy of Baptism in the case of infants, is peculiar to the ordinance in its administration to them, and does not attach to it in its administration to adults. I believe that this is not the case. There may be greater difficulty in gathering from the statements of Scripture what the virtue of Baptism really is in its application to infants, than in ascertaining what it is in its application to adults. But to explain the supernatural virtue itself is just as difficult in the one case as in the other, and simply from this reason, that it is supernatural. Up to a certain point it is easy enough to explain the efficacy of adult Baptism, but beyond that fixed point it is impossible to explain it. That point is where the natural efficacy of the ordinance passes into the supernatural efficacy. There is a certain natural influence which Baptism, as expressive of certain spiritual truths, and through means of these truths, is fitted to exert upon the adult, because he is a moral and intelligent being, with his faculties developed and complete. And this natural influence of Baptism, through means of the truths expressed by it, cannot be exerted upon the infant, because, although he is a moral and intelligent being, his faculties are not developed or complete. As a sign of spiritual truths understood by the adult, and not understood by the infant, Baptism has a certain natural effect on the one and not on the other, which it is not difficult to explain. But this effect is moral or natural, and not, properly speaking, the sacramental efficacy that is peculiar to the ordinance. The sacramental efficacy peculiar to the ordinance is not natural, but supernatural,—an efficacy not belonging to it from its moral character, but belonging to it in consequence of the presence and power of the Spirit of God in the ordinance. This distinctive efficacy of Baptism as a Sacrament, we cannot understand or explain, either in the case of adults or the case of infants. It is a supernatural effect of a gracious kind, wrought by the Spirit of God in connection with the ordinance; and because it is supernatural, it is not more and not less a mystery in the case of infants than in the case of adults.

The supernatural efficacy connected with Baptism, and owing to the presence of the Spirit of God with the ordinance, is an efficacy competent to infants as much as to adults. Even upon their unconscious natures the Spirit is free to work His work of grace, not less than upon the natures of adults whose understandings and hearts are consciously consenting to the work. The work of regeneration by the Holy Ghost is a work which it is as easy for Him to accomplish upon the infant of days as upon the man of mature age,—upon the child who enjoys but the rudiments of his moral and intellectual life, as upon the adult whose moral and intellectual powers are co-operating in and consenting to the gracious change. But broadly marked although the regeneration of the infant and the regeneration of the adult be, by the absence in the one instance, and the presence in the other, of a capacity moral and intellectual for faith and repentance, yet it is never to be lost sight of or forgotten that the work is the work of the Spirit of God, and not to be explained on any natural principle either in the former case or in the latter. The presence of his complete and perfect intellectual and moral powers in the case of the baptized adult, and the exercise of those powers in connection with the truths represented and signified in the Sacrament, afford no adequate explanation of the sacramental grace or efficacy connected with the ordinance in consequence of the power of the Spirit in it. At this point we have got beyond the limits of the natural, and into the region of the supernatural; and it is not more and not less supernatural in the case of infants than in the case of adults. Sacramental grace, properly so called, is a mystery of which there is no explanation, except that it is the grace of the Spirit of God. Admit that this grace is conveyed in any given case through the channel of Baptism to the believing adult, and you admit a mystery, which the presence and active exercise of his moral and intellectual powers do not in the least explain. Admit that this grace is conveyed in any given case through the channel of Baptism to the infant incapable of believing, and you admit a mystery too, but one not more mysterious than the former, and not more difficult to explain, from the absence or incapacity of his moral and intellectual faculties. In one word, the efficacy of infant Baptism, whatever that may be shown from Scripture to be, is not more mysterious than the sacramental virtue ascribed to adult Baptism.

Bearing in mind these preliminary remarks, what, I ask, are the effects of Baptism in so far as regards infants baptized? I do not pause at present in order to examine into the nature and benefit of the ordinance in so far as regards parents, who, in the exercise of a parent's right to represent their unconscious children, claim the administration of the ordinance for their offspring. In acting as the substitute for the infant, who cannot act for itself, in the solemn federal transaction between it and Christ,—in becoming a party in its name to the covenant made between the baptized infant and its Saviour through the ordinance,—the parent comes under a very great and solemn obligation on behalf of the child, thus pledged and given to the Redeemer through the parent's deed and not its own. But passing by this, let us confine our attention to the case of the infant, and proceed to inquire what are the benefits and efficacy of Baptism to the infant participators in the ordinance? In the case of adults, we know that Baptism is fitted and designed not to confer faith, but rather to confirm it,—not to originate grace, but to increase it,—not to effect that inward change of regeneration by which we are numbered with the children of God, or that outward change of justification by which we are accepted of Him, but to seal these blessings before bestowed. With adults, Baptism is not regeneration or justification, but the seal of both to the regenerated and justified man. And in the case of infants, the Sacrament cannot be regarded as accomplishing *without their faith*, what in the case of adults *with their faith*, it fails to accomplish. In other words, infant Baptism is not infant regeneration or justification, any more than in the instance of adults. The Baptism with water to a child is not the same thing as the birth by the Spirit. It is not a supernatural charm. It is not a magic spell to confer the washing of regeneration and the renewal of the Holy Ghost. Sacraments in the case of infants, as in the case of adults, have no mysterious and supernatural power of their own to impart, by the bare administration of them, spiritual life. Let us endeavour to understand what *are* the effects of Baptism in the case of infants.

### [Gives to them an interest in the Church]

Baptism, in the case of all infants baptized, gives to them an interest in the Church of Christ, as its members.

Circumcision gave to infants in other days a place in the ancient Church as its members; and they grew up within its pale entitled to all its outward privileges and rights, needing no other admission in after life. And what circumcision did during the time when it was in force, that Baptism does now in regard to infants baptized. It constitutes the door of admission into that visible Church of God on earth of which the parent himself is a member; and the baptized one grows up within the pale of its distinctive communion, needing no other admission, marked off at least outwardly from a world that has no interest in God, and having a right to the enjoyment of privileges which, as an outward provision for His own in this earth, God has given to them and not to the world. And this of itself is no small privilege, outward and temporal though it be, and not inward and spiritual. That outward provision of the means of grace, which has been given to the visible Church in this world for its establishment and benefit, is always represented in Scripture as a gift of Christ to His people, not to be undervalued or despised because it comes short, in those who enjoy it, of a saving blessing, but rather to be accounted exceeding great and precious. It is a gift of Christ to His Church which is of such worth and moment that the giving of it is spoken of in the Word of God as one of the great purposes for which the Saviour ascended up on high. "When He ascended up on high," says the Apostle Paul in his Epistle to the Ephesians,—"when He ascended up on high, He led captivity captive, and gave gifts unto men. And He gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers; for the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ."[^02.05.02] That outward provision of ordinances and means of grace for the visible Church, the bestowment of which is thus represented as one of the grand objects for which Christ left this world and ascended to the Father, must be to that Church of no ordinary importance and value. It is a right to this provision of outward ordinances and means of grace which the baptized infant receives, when by his Baptism he becomes formally a member of the visible Church; and growing up in the use and enjoyment of them, the benefit to him, although short of a saving benefit, is beyond all price. Baptism as the sign of membership and the passport to the infant into the sanctuary of the visible Church, does not bestow the saving blessing, but brings him in after life into contact with the blessing; it does not constitute him a member of the kingdom of heaven, but it brings him to the very door, and bids him there knock and it shall be opened unto him.

[^02.05.02]: Eph.\ 4:9, 11–12.

### [Right of property in the covenant of grace]

Baptism, in the case of all infants baptized, gives them a right of property in the covenant of grace; which may in after life, by means of their personal faith, be supplemented by a right of possession.

In regard to this matter, I would have recourse again to a distinction, which in other discussions we have found it necessary to adopt, and which has more than once helped us to clear our way to a right understanding of the question in debate. A man may have a right of property in an estate, and yet a stranger may be in possession of it; and he may require to add to his right of property a right of possession, acquired by making good the former in a court of law, before the stranger is extruded, and he himself introduced into the enjoyment of the inheritance. Now, to apply this distinction to the case in hand, a right of property in the blessings of the covenant of grace is conferred by the gift and promise of God, made over to every man who hears the Gospel message addressed to him. "And this is the record, that God has given to us eternal life, and this life is in His Son."[^02.05.03] This right of property in the blessings of the covenant of grace, belonging to every man, is written down in these words. The charter which every man has, bearing in it inscribed his right of property to these blessings, is the revealed Word of God. This is the first and superior title. But in itself it is incomplete, and inadequate to put him into the personal possession of his heritage. It requires to be supplemented by another title, before he can actually enjoy the salvation so made over to him by right of property, and certified by God's word and promise. To his right of property there must be added a right of possession; and this latter is obtained by means of his own personal act of faith, appropriating to himself the salvation before made over to him. The Word of God addressed to him, giving him a right of property in the blessings of the covenant, and his faith receiving that Word, giving him a right of possession, complete the full and perfect title to the blessing; and both together admit him to the enjoyment of it. There are many, who have the right of property in the covenant of grace, who never complete their title by seeking for themselves a right of possession in it. The Word of God giving the one, is not supplemented by the faith in that Word which would confer the other; and hence they are never put in actual possession of the salvation of which they are invited to partake.

[^02.05.03]: 1\ John\ 5:11. 

Now, what the Word of God addressed to the intelligent and responsible adult is, that Baptism is when administered to the unconscious and irresponsible infant. The word of God's promise, giving a right of property in His covenant to all who hear it, cannot penetrate the silent ear, nor reach the unconscious spirit of the little child. That word cannot convey to its mind the glad tidings of its covenant right to God's grace. But is it therefore denied that right, which adults have by the hearing of the ear and the perception of the understanding, in connection with the word of promise addressed to them? Not so. If the outward word that speaks the promise of God cannot pierce to its dormant spirit,—sleeping in the germ of its moral and intellectual being,—the outward sign, that represents the promises of God, can be impressed upon it, giving to the unconscious infant, as the word gives to the intelligent adult, a right of property in the blessing of the covenant. And that is much. The infant, sprinkled with the water of that Baptism which is a sign of the covenant, has—even as the adult addressed with the word of the covenant has—a right of property in the blessings which the covenant contains; and in after life he may, by his own personal act, supplement his right of property by a right of possession obtained through faith. When the period of infancy is passed and he is a child no longer, he bears about with him, in virtue of his Baptism, a right of property in the promise of his God; and laying his hand upon that right, and pleading it with God in faith, he may add to it the right of possession, and so enter into the full enjoyment of the salvation that he requires for his soul. The written or preached Word cannot speak to the mute and insensible infant, as it speaks to the hearing ear and understanding mind of the adult, making over to him in conscious possession a right of property in the blessings of the everlasting covenant. But the little one is not thereby shut out from all interest in the covenant. The outward sign suited to his state of infancy, the outward mark impressed upon his outward person, when the significant Word were in vain addressed to his ear, have been given by God in gracious condescension to supply to him the want of that Word heard and understood. By the act of Baptism, suited and appropriate to his wholly sensitive condition of being and life, his name is put into the covenant with his God. And after years may witness the infant,—then an infant no more,—reading in faith his name there, and with the charter of his right in his hand making good his right, not of property merely, but of personal possession in all the blessings which are written in it.

Baptism, then, in the case of all baptized infants, gives them a right of property in the covenant of grace; which may in after life, by means of their personal faith, be supplemented by a right of possession, so that they shall enter into the full enjoyment of all the blessings of the covenant. The benefits of Baptism in the case of infants are not fully experienced by them until in after years they add to Baptism their personal faith, thereby really making out a complete title, not only to the property, but also to the possession of salvation. In this respect there is an obvious distinction between the Baptism of infants and the Baptism of adults. Infants are not capable of faith and repentance; and Baptism can be to infants no seal of the blessings which these stand connected with, at the time of its administration. But it may become a seal of such blessings afterwards, when the child has grown to years of intelligence, and has superinduced upon his Baptism a personal act of faith, and thereby become possessed of the salvation which he had not before. In such a case, he can look back upon his Baptism with water, administered in the days of his unconscious infancy; and through the faith that he has subsequently received, that Baptism which his own memory cannot recall, and to which his own consciousness at the time was a stranger, becomes to him a seal of his now found salvation. In adults it is otherwise; and the difference is appropriate to their condition as adults. Baptism to the believing adult is a seal at the moment of his interest in the covenant of grace; a sensible attestation of the blessings of justification and regeneration, of which at the time he is in possession, through the exercise of his faith contemporaneously with his Baptism. In the case of the adult, Baptism is a *present* seal in connection with the faith which he presently has. In the case of the infant, it is a *prospective* seal in connection with the faith which he has not at the moment, but which he may have afterwards. The full enjoyment of the benefits of the ordinance the adult experiences at the moment of its administration, in virtue of the faith which at the moment makes him a partaker in the blessings of the covenant. The full enjoyment of the benefits of the ordinance the infant cannot experience at the moment of its administration, in virtue of his incapacity of faith; but it may be experienced afterwards, when, in consequence of his newly formed faith in Christ, he too is made partaker of the covenant, and can look back in believing confidence on his former Baptism as a seal. "The efficacy of Baptism," says the Confession of Faith, "is not tied to that moment of time wherein it is administered; yet notwithstanding, by the right use of this ordinance, the grace promised is not only offered, but really exhibited and conferred by the Holy Ghost, to such (whether of age or infants) as that grace belongeth unto, according to the counsel of God's own will in His appointed time."[^02.05.04]

[^02.05.04]: Conf. chap.\ xxviii.\ 6. Williams, *Antipæd. Exam.* vol.\ i. pp.\ 208–214, 220–224. Goode, *Doct. of the Church of Engl. as to the Effects of Baptism in the case of Infants*, 2d\ ed. pp.\ 9–26, 143–162, etc. [Goode, *Vind. of Defence of the XXXIX Articles*, etc., in reply to the Bishop of Exeter, 2d\ ed. pp.\ 19–21. *Letter to the Bishop of Exeter*, Lond. 1850, pp.\ 11, 23–44, 72–78. *Review of Sir H.\ J. Fust's Judgment in the Gorham Case*, Lond. 1850, pp.\ 23–31,\ 34.]

### [Ordinarily connected with regeneration of those regenerated in infancy]

There seems to be reason for inferring that, in the case of infants regenerated in infancy, Baptism is ordinarily connected with that regeneration.

To all infants without exception, Baptism, as we have already asserted, gives an interest in the Church of Christ as its members. To all infants without exception, Baptism, as we have also already asserted, gives a right of property in the covenant of grace, which may, by their personal faith in after life, be completed by a right of possession, so that they shall enter on the full enjoyment of all the blessings sealed to them by their previous Baptism. And beyond these two positions, in so far as infants are concerned, it is perhaps hazardous to go, in the absence of any very explicit Scripture evidence; and certainly, in going further, it were the reverse of wisdom to dogmatize. But I think that there is some reason to add to these positions the third one, which I have just announced, namely, that in the case of infants regenerated in infancy, Baptism is ordinarily connected with such regeneration. I would limit myself to the case of baptized infants regenerated in infancy,—a class of course to be distinguished broadly from baptized infants who never at any time in their lives experience a saving change; and also to be distinguished from baptized infants who experience that change, not in infancy, but in maturer years. There are these three cases, plainly to be distinguished from one another. There are, *first*, those infants baptized with an outward Baptism who never at any period come to know a saving change of state or nature. To such Baptism may be an ordinance giving them a place in the visible Church, and giving them also a right of property in the covenant of grace, never completed by a right of possession, and therefore given to them in vain; but it can be nothing more. There are, *secondly*, those infants baptized with water in infancy, but not regenerated in infancy by the Spirit of God, whose saving change of state and nature is experienced by them in after life. To such Baptism is an ordinance giving them a place in the visible Church, and giving them also a right of property in the covenant, at the moment of its administration; and in after years, when born again by the Spirit through faith, Baptism becomes to them, in addition, the seal, as it had previously been the sign, of the covenant,—their right of property having been completed by the right of possession, and the Sacrament, although long past, having become in consequence a present grace to their souls. But there are, *thirdly*, those infants baptized with water in infancy and also regenerated in infancy; and with regard to them I think there is reason to believe that this Baptism with water stands connected ordinarily with the Baptism of the Spirit.

That many an infant is sanctified and called by God even from its mother's womb, and undergoes, while yet incapable of faith or repentance, that blessed change of nature which is wrought by the Spirit of God, there can be no reason to doubt. There are multitudes born into this world who die ere their infancy is past,—who open their unconscious eyes upon the light only to shut them again ere they have gazed their fill,—and who, in the brief moment of their earthly being, know nothing of life save the sorrow which marks both its beginning and its close. And with regard to such infants dying in infancy, there is a blessed hope, which the Scriptures give us to entertain, that they are not lost but saved,—that they suffer, and sorrow, and die here from their interest in Adam's sin, but that, not knowing sin by their own personal act or thought, they are redeemed through their interest in Christ's righteousness.[^02.05.05] But saved though infants dying in infancy may be, yet there is no exemption, even in their case, from the universal law of God's spiritual dispensation towards men, that "except a man be born again, he cannot see the kingdom of God." Within the brief hour of an infant's life, and ere the unconscious babe passes through the avenue of death into the Divine presence, must that mighty change of regeneration be undergone, which none but the Spirit of God can work; and among the rudiments of its intellectual and moral life, sleeping in the germ, there must be planted the seed of that higher life, which in heaven is destined to expand and endure through all eternity. And where, in the brief history of the young life and early death of these baptized little ones, shall we say that this mysterious work is wrought? At what moment, rather than another, is this regeneration by the Spirit accomplished? We dare not limit the free Spirit of God. The beginning of the life that comes from Him may be contemporaneous with the commencement of natural life in the infant, or it may be contemporaneous with its close. The Spirit of God is *free* to do His own work at His own time. But in the appointment of an ordinance to signify and represent that very work,—in the command to administer that ordinance as a sign to the little infant during the brief hour of its earthly life and ere it passes into eternity, there does seem to me some ground to believe that in such a case, of infants regenerated in infancy, the sign is meant to be connected with the thing signified,—that the moment of its Baptism is the appointed moment of its regeneration too,—and that, ordinarily, its birth by water and its birth by the Spirit of God are bound in one. It is Baptism which gives the baptized infant a right of property in the blessings of the covenant of grace; and when the infant is placed,—not from its own fault,—in such circumstances as to bar the possibility of its completing its title to those blessings by seeking through its personal faith a right of possession in them also, then it is consistent with the analogy of God's appointments in other departments of His Church, that in such extraordinary cases the absence of a right of possession should not exclude from the blessings, but that the right of property alone should avail to secure them; or in other words, that in the case of infants regenerated and dying in infancy, their Baptism should coincide with their regeneration.[^02.05.06]

[^02.05.05]: [[*Du kamst, du giengst mit leiser Spur, \
\ \ \ \ Ein flücht'ger Gast im Erdenland; \
Woher? Wohin? wir wissen nur: \
\ \ \ \ Aus Gottes Hand in Gottes Hand. \
—Uhland, *Auf den Tod eines Kindes*.*]{lang=de}]

[^02.05.06]: ["[Quos electione suâ dignatus est Dominus, si, accepto regenerationis signo, præsenti vitâ ante demigrent quam adoleverint, eos virtute sui Spiritûs nobis incomprehensâ renovat, quo modo expedire solus Ipse providet.]{lang=la}" "[Quoniam autem valde absurdum fore putant si infantibus tribuatur ulla cognitio Dei, quos boni et mali intelligentiâ Moses]{lang=la} (Deut.\ 1:39) [privat: respondeant quæso mihi, quid periculi sit si aliquam Ejus gratiæ partem nunc accipere dicantur cujus plenâ largitate paulo post perfruentur? Nam si vitæ plenitudo perfectâ Dei cognitione constat, quum eorum nonnulli, quos primâ statim infantiâ hinc mors abripit, in vitam æternam transeant, ad contemplandam certe Dei faciem præsentissimam recipiuntur. Quos ergo pleno lucis Suæ fulgore illustraturus est Dominus, cur non iis quoque in præsens, si ita libuerit, exigua scintilla irradiaret: præsertim si non ante exuit ipsos ignorantiâ quam eripit ex carnis ergastulo?]{lang=la}"—Calvin, *Inst.* lib.\ iv. cap.\ xvi.\ 19,\ 21. Turrettin, *Op.* loc.\ xix. qu.\ xx.\ 15–20. Witsius, *Miscell. Sacr.* tom.\ ii. Exercit.\ xix.\ 1.]

I do not wish to speak dogmatically on such a question as this, when Scripture has given us so little light to enable us to read the truth with certainty. But in the particular case of infants regenerated in infancy, there does seem to be some reason to believe, that the washing with water in virtue of God's own appointment stands ordinarily connected with the renewing of nature by God's own Spirit. In the instance of believing adults, regeneration is linked inseparably with *the Word believed*. In connection with the *Word*,—although the Spirit of God is free to work without it,—He does His mysterious work of regeneration upon the adult's nature. But that Word cannot profit the little infant who is to die ere his eyes can look upon it. The Spirit of God cannot, therefore, do His gracious work of spiritual renewal and cleansing on the unconscious babe in connection with the Word believed. But there is another ordinance adapted to the infant nature, which needs to be regenerated ere it passes into another state of being. There is another ordinance, not the Word, which we are commanded to administer to the babe, incapable of receiving or profiting by the Word. There is the Baptism with water, expressive of that very regeneration which, before the little one shall pass from us to eternity, its unconscious nature must undergo. And when the infant carries with it to the tomb the sign of the covenant, administered in faith, shall we not say that with the sign, and mysteriously linked to it, there was also the thing that was signified; and that in such a case of a dying babe regenerated in infancy, the laver of Baptism was the laver of regeneration too? In the sign of the covenant thus administered to the child, and linked, as we believe, in such a case to a new and spiritual life, there is a ground of hope and consolation to a bereaved but Christian parent beyond all price. There is a joy at its birth, which none but a mother can feel, when it is said unto her that a man-child is born into the world; and there is a bitter sorrow at its early death, which none but a mother can know, when she is called upon to resign the little one whom she brought forth in sorrow, and to give it to the dust in sorrow deeper still. And when a Christian mother has been called upon thus to weep at the open grave of many of her infants, ere it close in peace upon herself, it is an unspeakable consolation for her to know, that the little one, whom she took from off her bosom to lay in the tomb, was indeed signed with the sign of a Christian Baptism; and that in its case the Baptism with water and the Baptism with the Spirit were bound up in one.

::: {.poetry}
- <!-- removed opening quote from poetry -->Oh when a mother meets on high \
- The babe she lost in infancy,
- Hath she not then for pains and fears,
  - The day of woe, the watchful night,
- For all her sorrows, all her tears,
  - An over-payment of delight?<!-- removed closing quote from poety -->[^02.05.07]
:::

[^02.05.07]: Southey, *Curse of Kehama*.
