## The Subjects of Baptism as Regards Adults

Having discussed the general nature of Baptism, the question that next awaits our consideration is, as to the subjects of Christian Baptism, or the parties to whom this ordinance ought to be administered. There are three opinions that may be maintained in regard to this matter. There is one party who affirm that Baptism ought to be administered to all, not infants, who are qualified to become members of the Christian Church in virtue of a credible profession of faith in Christ and a corresponding conduct. There is a second party who assert that Baptism rightfully belongs not only to such persons, but also, in virtue of a representative relation between parents and their offspring, to their children. And there is a third party who hold that Baptism ought to be administered without restriction to parents and children, without demanding, as a prerequisite from the applicant, any profession of faith or corresponding conduct. These three classes, holding principles markedly different from each other, probably exhaust the answers to the question: To whom is Baptism to be administered? The first, or the Antipædobaptists, administer the ordinance only to adults, who, by their faith and obedience, appear to be possessed personally of a title to be regarded as members of the Christian Church, and exclude infants, who cannot, by their own faith and profession, make good their claim to be regarded as proper subjects of the ordinance. The second, or the Pædobaptists, administer the ordinance not only to adults, who personally possess a right to be regarded as members of the Christian Church, but also to their infants, who can have no right except what they derive from their parents. And the third class, or the advocates of indiscriminate Baptism, administer the ordinance to all applicants without any restriction, and without demanding, in the case of adults, that they establish their claim to the ordinance by exhibiting a credible profession of faith in their own persons, or, in the case of infants, in the persons of their parents or guardians.

In proceeding to examine these different systems, it will not be necessary for me to discuss over again what occupied our attention at an early period of the course,—the question of what are the qualifications that give a person a title to be regarded as a member of the Christian Church,—or to enter into the controversy between Independents and Presbyterians as to the necessity in order to membership of a true and saving faith, or simply an outward profession and consistent practice.[^02.02.01] Without entering upon that subject a second time, the three systems of opinion as to the proper subjects of Baptism now mentioned may be conveniently discussed under the head of these two questions. *First*: Are we warranted by the Word of God to administer the ordinance of Baptism to *all* applicants for themselves or their children, without any restriction as to religious profession and character in the case of the applicant? And *second*: Are we warranted by the Word of God to administer the ordinance of Baptism to the children of a parent who would himself be a proper subject for Baptism, and is a member of the Church? The first question, or the point in debate between our Church and the advocates of indiscriminate Baptism, we shall now proceed to deal with, reserving the second, or the question of infant Baptism, for after consideration.

[^02.02.01]: [See above, vol.\ i. pp.\ 68–80.]

The doctrine of Baptism without restriction, and apart from the religious character and profession of the applicant, has assumed an aspect of more than ordinary importance recently, in consequence of the extent to which it has prevailed and the manner in which it has been advocated among Independents. Dr.\ Wardlaw,—who was no friend of such a doctrine, but the reverse,—when speaking in reference to a former statement of opinion, to the effect that all parties were of one mind as to the necessity for a religious profession as a prerequisite to Baptism, says: "Until of late, I had no idea of the degree or of the extent of this laxity, both as to the requisites in adults to their own baptism, and in parents, to the baptism of their children. It has been a cause of equal surprise and concern to me to find, from the publications of more than one of my brethren which have recently appeared, that in my first statement I have been so very wide of the truth. The lax views to which I now refer have been propounded and argued at length in the Congregational Lecture for 1844, by my esteemed friend, Dr.\ Halley of Manchester." The surprise expressed by Dr.\ Wardlaw at the acceptance which the doctrine of indiscriminate Baptism has received, and the prevalence which the practice has obtained among English Independents, is not without foundation. Dr.\ Halley may, I believe, be fairly regarded as the representative of the views of Independents, at least in England, on the subject; and he is perhaps the ablest defender of the practice which prevails, very nearly universally, among them. The doctrine of the class to which he belongs, and whose views he advocates, is expressed by Halley as follows. After stating the principles held by other and opposite parties, he says: "There are, lastly, those who baptize all applicants whatsoever, provided the application does not appear to be made scoffingly and profanely,—for that would be a manifest desecration of the service,—and all children offered by their parents, guardians, or others who may have the care of them." "The third class maintain that, as no restriction is imposed upon baptism in the New Testament, none ought to be imposed by the ministers of the Gospel."[^02.02.02] "These views,"—I quote again from Dr.\ Wardlaw,—"these views, which he broaches and defends, are characterized by a latitudinarian laxity, which in my eyes is as mischievous as unscriptural,—the former, because the latter."[^02.02.03] The question, then, of indiscriminate Baptism is one of very great interest and importance,—more especially in the present day,—and amply deserves discussion. In that discussion we must of course appeal for the only arguments which can decide the controversy to the Scriptures themselves. We learn from them that Baptism is a positive institution of Christ in the worship of the Christian Church; and from them also we must learn the terms on which the ordinance is to be dispensed, and the parties entitled to receive it. Is the ordinance, then, to be administered to all applicants indiscriminately without regard to religious profession or character,—to believers and unbelievers alike,—without any restriction, except, according to Dr.\ Halley, that they do not apply for it "scoffingly and profanely"?<!-- original had ? inside quotation mark --> Or, on the contrary, does a title to participation in the ordinance of Baptism imply, as a prerequisite, a religious profession and corresponding conduct on the part of the applicant?

[^02.02.02]: Halley, *The Sacraments*, Lond. 1844, vol.\ i. p.\ 496.

[^02.02.03]: Wardlaw, *Dissertation on the Scriptural Authority, Nature, and Uses of Infant Baptism*, 3d.\ ed. Glasg. 1846, pp.\ 221–223.

Now, in examining into the doctrine and practice of Scripture bearing upon this question, it is important to understand distinctly at the outset the real point in debate. There are two preliminary remarks which may help to place it in its true light.

**1st**, The question in debate between the advocates and opponents of indiscriminate Baptism is *not*, as Dr.\ Halley has stated it to be: "Whether the Apostles and their assistants baptized indiscriminately all applicants, leaving their characters to be formed and tested by subsequent events."[^02.02.04] The question rather is: Whether, in such application made to the Apostles for Baptism, there was not included or implied a religious profession of faith in Christ, such as to warrant them to administer the ordinance because of the profession. It is manifest that, in apostolic times, when men were called upon in consequence of a Christian Baptism to forsake all that was dear to them on earth, and to incur the hazard of persecution and death, almost any such application necessarily involved or implied at least a credible profession of faith in Christ; inasmuch as hardly any conceivable motive except a belief in Christ would have induced any one to make the application, except, it may be, in rare and exceptional cases. Generally speaking, the fact of a man's applying for Baptism in apostolic times was itself the evidence of a credible profession, and enough to warrant the administration of the ordinance, not on the principle of baptizing all, believers and unbelievers alike, with a profession or without it; but rather on the principle that the applicant, by the very act of application, in the circumstances of the early Church, professed his faith in Christ. Upon this principle we can easily explain why, in the Scripture narrative of the practice of baptizing in the early Church, we find no example of the applicant being kept for a length of time in the position of candidate for Baptism, so as thereby to test his character and profession.

[^02.02.04]: Halley, *The Sacraments*, Lond. 1844, vol.\ i. p.\ 505.

**2d**, The question in debate between the advocates and opponents of indiscriminate Baptism is *not*, whether the Apostles, in their administration of the ordinance, baptized, as Dr.\ Halley asserts, "bad men as well as good."[^02.02.05] That the Apostles did so in particular instances, the case of Simon Magus plainly attests. But that case no less plainly attests that the Baptism was administered, not in the absence of any religious profession, but in consequence of such a profession. Nothing can be more undeniable than that it was upon the ground of his professed belief in the Gospel preached by Philip that Simon Magus was baptized. "Then Simon," says the inspired account of the transaction, "then Simon himself *believed also*: and when he was baptized," etc.[^02.02.06] Like the other hearers who were baptized in consequence of their profession of faith in Philip's doctrine, Simon professed to believe, and, on the credit of that profession, was baptized as they were. But although among the number of those who received apostolic Baptism there were good men and bad men, as there must be among the members of the Church in all ages, this is not the real question at issue between the friends and opponents of indiscriminate Baptism. The real question in controversy between them is, whether Baptism was generally, or was ever, administered without a religious profession at all on the part of the applicant; or whether such a profession was invariably present as a prerequisite to Baptism. "Baptism," says the Shorter Catechism, "is not to be administered to any that are out of the visible Church, till they profess their faith in Christ and obedience to Him."[^02.02.07]

[^02.02.05]: *Ibid.* p.\ 505.

[^02.02.06]: Acts\ 8:13.

[^02.02.07]: Shorter Catechism, qu.\ 95.

Bearing in mind these preliminary remarks, it is not difficult, I think, from an examination of Scripture doctrine and practice in regard to Baptism, to establish the conclusion, that it is a sacramental ordinance not to be administered indiscriminately and without restriction to all applying for it, but, on the contrary, limited to those maintaining an outward character and profession of Christianity.

### [Nature of Baptism inconsistent with indiscriminate administration]

The nature and import of the ordinance of Baptism are inconsistent with the idea of an indiscriminate administration of it to all, without respect to religious character and profession.

The doctrine and practice of the advocates of indiscriminate Baptism very naturally arise out of the system maintained by them as to the nature of the ordinance. With Dr.\ Halley and the Independents, whom he represents, Baptism is not, in the proper and peculiar sense of the term, a Sacrament, but only a sign; and a sign, too, of a very restricted meaning indeed. It is a sign that the person holds certain Christian truths, or is willing to learn them; which truths may be held in the way of a mere intellectual apprehension, without the man who so holds them being a Christian, or even seriously professing to be one. Upon this theory,—that Baptism is no more than a sign, expressive of certain truths of Christianity,—it is quite possible to engraft the doctrine of an indiscriminate administration of the ordinance in every instance where those truths, as is usually the case in a Christian country, are not openly renounced or publicly denied. To affix the sign of allegiance to those truths in the case of every man who merely does not deny them, and must be held by the very act of applying for the sign, as at least in some tolerable degree acquainted with them, is consistent enough. To affix the sign to all infants proposed for Baptism, is also consistent; for they are capable of being instructed in the truths represented, and the act of their parents in bringing them to receive the ordinance may be regarded as an acknowledgment that they are willing that their children be so instructed. Restrict the import of Baptism to that of a mere sign of certain Gospel truths, and it is quite in accordance with the theory of indiscriminate administration. "Practically," says Dr.\ Halley, "those who baptize indiscriminately all applicants and all children proposed for baptism, and those who reckon upon the prospect of teaching the baptized, will be found seldom at variance; for scarcely ever is any one proposed whose religious instruction might not be secured by proper care."[^02.02.08] As a sign expressive of acquaintance with certain Christian truths, or of a capacity and willingness to receive them, Baptism may consistently enough be administered without restriction to all applicants, whether adults or infants.

[^02.02.08]: Halley, *ut supra*, p.\ 479.

But the very opposite doctrine and practice must be maintained, on the supposition that the Sacrament of Baptism is not a sign merely, and that in a very restricted sense, of Christian truth, but a seal of a federal transaction between two parties in the ordinance, whereby the recipient gives himself in Baptism to Christ, and Christ in Baptism gives Himself and His grace to the recipient. A seal of a covenant which the party baptized does not even profess to make, and has avowedly no intention of entering into,—a voucher to a federal transaction, in which there is no person in the least professing to be a party,—an attestation to a mutual engagement never pretended by the individual who is supposed to give the attestation,—this is a contradiction and inconsistency not to be got over. There is a manifest incongruity in administering equally to those who avow that they are believers, and to unbelievers with no such avowal, the same Christian ordinance,—in dispensing a Gospel Sacrament indiscriminately to those who profess to have received the Gospel, and to those who do not,—in giving a religious privilege to those who make no religious profession, not less than to those who do. If Baptism be no more than a sign of certain religious truths known, or at least that may be learned, by the party baptized, then indeed there is no such incongruity between the nature of the rite and its unrestricted administration. But if Baptism be the outward seal of a federal engagement, distinctively marking the true Christian, then the very nature of the ordinance forbids it to be administered to men with no profession of Christianity. If it be the Sacrament of union to the Saviour and admission into the Christian Church, the ordinance itself points out the necessity of its restriction to those who "name the name of Christ," and whose life and conduct are not outwardly inconsistent with their claim to be numbered among His people.

### [Baptism by John evidence against indiscriminate dispensation]

The administration of Baptism by John, the forerunner of our Lord, has been very generally appealed to in favour of an indiscriminate dispensation of the ordinance,[^02.02.09] but in point of fact may be regarded as affording evidence of a contrary practice.

[^02.02.09]: Halley, *ut supra*, pp.\ 163–167, 194–201.

The Baptism of John, when we are told that multitudes of the Jews flocked to him in the wilderness to be baptized, has been quoted in favour of the doctrine and practice of English Independents. There are two things which it is necessary to establish before any argument for indiscriminate Baptism in the Christian Church could be drawn from the preaching of John; and both these things, so far from being proved, may with good reason be denied. In the first place, it were necessary to prove that the Baptism of John was identical with Christian Baptism, before any countenance could be derived from his practice,—even if it were, as is alleged, that of indiscriminate Baptism,—in favour of the same custom in the Christian Church. And in the second place, it were necessary to establish the assumption that John really baptized all equally who came to him, without regard to their religious profession. I believe that neither the one nor the other of these positions can be established from Scripture, but the reverse.

With regard to the first position, there seems to be warrant from Scripture to say that John's Baptism was not identical with that of Christ. His doctrine and his office occupied an intermediate place between those of the Old Testament teachers and those of the Gospel Church; and his Baptism corresponded with his doctrine. He taught the doctrine of repentance and of preparation for Him that should come after him; he pointed to the future Saviour, rather than preached a present one; and his Baptism was the same in character. We have no reason to believe that he baptized in the name of Christ; and we have ground for asserting that the Baptism of John, in the case of those who received it, was afterwards replaced by Christian Baptism, when they were received into the Christian Church. That such was the case, the instance of the disciples at Ephesus proves; whom Paul rebaptized, as is recorded in the nineteenth chapter of the Acts of the Apostles: "And he said unto them, Unto what then were ye baptized? And they said, Unto John's baptism. Then said Paul, John verily baptized with the baptism of repentance, saying unto the people, that they should believe on Him which should come after him, that is, on Christ Jesus. When they heard this, they were baptized in the name of the Lord Jesus."[^02.02.10]

[^02.02.10]: Acts\ 19:3–5. Williams, *Antipædobaptism Examined*, Shrewsbury 1789, vol.\ i. pp.\ 113–120. Wardlaw, *Dissert. on Infant Baptism*, 3d\ ed. Glasg. 1846, pp.\ 223–269.

With regard to the second point, or the assumption that the Baptism of John was really given to all applicants indiscriminately, without respect to religious character, there seems to be no evidence for it in Scripture, but the reverse. We seem to have as good evidence, that John demanded a profession of a religious kind from those whom he baptized, as the character of the very brief and scanty narrative which has come down to us of the transaction would naturally lead us to expect. That vast multitudes of the Jews enrolled themselves by Baptism in the number of John's disciples, would appear to admit of no doubt; for we are expressly told that "there went out unto him into the wilderness all the land of Judea, and they of Jerusalem, and were all baptized of him in the river Jordan." That of this great multitude all were truly brought to repentance, and turned from sin, and savingly taught to look forward to the Messiah who was to come, may, from many circumstances, appear improbable. But that they were all admitted to the ordinance of John's Baptism, without any regard to the religious profession that they made, is undeniably contradicted by the express language of the sacred historian; for it is added: "They were all baptized of him in the river Jordan, *confessing their sins*."[^02.02.11] The Baptism and the confession of sins went together,—the one being the accompanying condition of the other. So far is it from being true that the practice of John gives countenance to the theory of indiscriminate Baptism, that the very opposite may be proved from the inspired narrative, brief though it be.

[^02.02.11]: Matt.\ 3:5–6.

### [Great commission forbids indiscriminate Baptism]

The terms of the commission given by our Lord after His resurrection to His Apostles in regard to founding and establishing the Christian Church, seem very clearly to forbid the practice of indiscriminate Baptism, and to require a profession of faith in Christ as a prerequisite to Baptism in His name.

The terms of the commission, as recorded in the Gospel by Matthew, are these: "Go ye therefore, and disciple—[μαθητευσατε]{lang=el}—all nations, baptizing them into the name of the Father, and of the Son, and of the Holy Ghost; teaching them to observe all things whatsoever I have commanded you."[^02.02.12] Such is the language employed by our Lord in what must be regarded, I think, as the original institution of Christian Baptism. The commentary of Dr.\ Halley on these words brings out his argument in favour of indiscriminate Baptism. "The question," says he, "respecting the subject of Baptism is here resolved into one of grammar and criticism. It is simply what is the antecedent to the word *them*, or for what noun is that pronoun substituted. 'Going forth, disciple all the nations—[παντα τα ἐθνη]{lang=el}—baptizing *them*—[αὐτους]{lang=el}—all the nations, into the name of the Father, and the Son, and the Holy Ghost; teaching *them*—all the nations—to observe all things whatsoever I have commanded you.' So far as the grammatical construction is concerned, the meaning of the terms is precisely the same, as it would be if the words of the commission were, 'baptize all the nations.' Adhering, therefore, to the grammar of the words, we say, the commission, which no man has a right to alter, is, 'baptize all the nations.'"[^02.02.13] Now, this somewhat summary and confident mode of reasoning may be satisfactorily set aside in two ways.

[^02.02.12]: Matt.\ 28:19.

[^02.02.13]: Halley, *ut supra*, p.\ 489.

1. There is some weight due to the order in which the terms of the commission run, as indicating the order in which the discipling, the baptizing, and the teaching of all the nations were to take place, and were to be accounted necessary parts of the Apostles' or the Church's obedience to the commission of Christ. There are three particulars embraced in the authoritative commission addressed to the Apostles, and, through them, binding upon the Church in every age. *First*, the command is to make disciples of all nations, turning them to the profession and belief of the faith of Christ. *Second*, there is the command to baptize all nations, granting them the formal and public rite by which their admission into the Church was to be attested and ratified. And *third*, there is the command to teach all nations to observe all things whatsoever Christ had appointed for His Church collectively, or His people individually. This is the order in which, according to the nature of the various particulars embraced in the commission, they were to be accomplished. That the order of procedure here indicated is in harmony with the nature of the work to be done by the Church in reference to the world, is abundantly plain from the scriptural account given of it in many other passages of the Bible. First of all is the preaching of the Gospel, as the grand instrument employed by the Church to gather in the disciples of Christ within its pale. Next there is the affixing to the disciples thus gathered the characteristic badge of discipleship, and granting them, by the initiatory rite of Baptism, formal admission into the Christian Church. And lastly, there is the instructing those thus admitted in the observance of all their appointed duties as disciples of Christ and members of His Church. This is plainly, I think, the order of procedure indicated in the apostolic commission; and it is an order which implies that a knowledge and profession of the faith as disciples preceded the administration of Baptism to them. The expression, "*all nations*"—[παντα τα ἐθνη]{lang=el}—upon which Dr.\ Halley builds his argument for universal and indiscriminate Baptism, is not to be regarded so much as declaring the duty of the Apostles to teach and baptize every individual of the world, or as denoting the absolute extent of the commission, as asserting that individuals of every nation were to be discipled and baptized, and marking out that no nation or class were excluded from the range of the commission. The terms, "disciple," "baptizing," must be taken together, and not separately; and in the order of the inspired declaration, and not in the reverse of that order.

2. The words of institution in the baptismal service seem to imply that a knowledge and profession of the faith of Christ are necessary as a prerequisite to Baptism. The recipients of the ordinance are to be baptized "into the name, [εἰς το ὀνομα]{lang=el}, of the Father, the Son, and the Holy Ghost,"—language which obviously refers to the peculiar character the Three Persons of the Godhead sustain, and the offices they discharge in the work of man's redemption. Unless Christian Baptism, then, be a mere heathen mystery, to suffice as a sign or to work as a charm, it necessarily implies previous knowledge and instruction in the fundamental truths of the Gospel system; and this, again, implies that the Church, in administering the ordinance, has a right to require some evidence, such as an intelligent profession of the faith, that such knowledge has been obtained. All this points very distinctly to a profession of faith in Christ as a necessary prerequisite to the administration of the ordinance in the case of candidates for Baptism.

### [Scripture demonstrates profession of faith is necessary]

An examination in detail of Scripture practice, as bearing upon the doctrine of indiscriminate Baptism as contradistinguished from Baptism restricted to professing Christians, will sufficiently bear out the conclusion to be drawn from the previous considerations, that at least a profession of faith is necessary as a prerequisite to the scriptural administration of the ordinance.

It is impossible, and indeed unnecessary, for us to enter at length into this field of argument. Nothing but the most violent injustice done to the language of Scripture by a bold and unscrupulous system of interpretation can suffice to get rid of the evidence which, in the case of the Baptism of converts mentioned in Scripture, connects the administration of the rite with a profession of faith in Christ on the part of the person who was the recipient of it. The association of the person's profession, faith, repentance, or believing, with Baptism, appears in a multitude of passages; while not one passage or example can be quoted in favour of the connection of Baptism with an *absence* of profession. "He that believeth, and is baptized, shall be saved;" "repent every one of you, and be baptized;" "many having believed, and been baptized,"[^02.02.14]—these and many other passages of a like import connect together, as inseparable in the process by which under the eye of the Apostles many in their days were added to the Christian Church, the two facts of the religious profession of the candidate, and the administration of the religious ordinance by which formally he became a member of the Church of Christ. In the history, although brief and incomplete, of the Baptism of the early converts to the Christian faith, there is almost invariably some statement by which is attested the distinctive Christian profession that stands connected with the administration of the outward rite; while in no instances are there any statements from which it could be proved that Baptism ever stood connected with the absence of such a profession. Connected with the Baptism of the three thousand on the day of Pentecost, there stands the statement, "Then they that gladly received the Word were baptized." Connected with the Baptism of the people of Samaria in consequence of the preaching of Philip, there stands the assertion, "When they believed Philip preaching the things concerning the kingdom of God, and the name of Jesus Christ, they were baptized, both men and women." In regard to the Baptism of the Ethiopian treasurer, we are told that, after the Gospel was preached to him by the same evangelist, "the eunuch said, See, here is water; what doth hinder me to be baptized? And Philip said, If thou believest with all thine heart, thou mayest. And he answered and said, I believe that Jesus Christ is the Son of God. And he commanded the chariot to stand still: and they went down both into the water, both Philip and the eunuch, and he baptized him." In connection with the Baptism of Lydia, and as preceding the administration of the rite, we have the statement: "whose heart the Lord opened, that she attended unto the things that were spoken of Paul." Connected with the Baptism of the Philippian jailer, there stands the statement: "And he rejoiced, believing in God, with all his house." In short, in almost every example of Baptism which the New Testament records, there is enough in the narrative, however scanty and compressed it be, to bring out the fact, that in close association with the administration of the rite appears the religious profession of the recipient. And, on the other hand, it may be safely asserted, that in no example of Baptism recorded in the New Testament can it be distinctly proved that no such profession was made.

[^02.02.14]: Mark\ 16:16; Acts\ 2:38, 41; 8:12–13, 36–38; 16:14–15, 30–34; 18:8.

What, then, is the answer given to this abundant and apparently satisfactory evidence for a Baptism restricted to and connected with a religious profession by the advocates of its indiscriminate administration? The answer given by them is twofold: first, that there are examples of bad men as well as good baptized by the Apostles; and second, that many or most of these Baptisms were administered so immediately in point of time after the profession made, that there was no opportunity to test by any satisfactory process the sincerity of it. Neither of these replies to the Scripture evidence is satisfactory. With regard to the first, or the fact that unbelievers and hypocrites were baptized, it is enough to say that we do not hold the Independent doctrine that a saving belief is necessary to entitle a man to Church membership; but, on the contrary, maintain that a profession of faith is enough,[^02.02.15] and that we have no security beyond the mere circumstance of an outwardly decent life against such profession being insincere. With regard to the second, or the fact that the profession on which the apostolic Baptisms in many instances proceeded could have been of no more than a few hours' standing, and therefore not proved by the lapse of time to be true, it is enough to say that there may be, and in apostolic times were, circumstances apart altogether from its duration sufficient to give credibility to the profession.[^02.02.16]

[^02.02.15]: [See above, vol.\ i. pp.\ 73–80.]

[^02.02.16]: Halley, *The Sacraments*, Lond. 1844, vol.\ i. pp.\ 488–527, 580–585. Wardlaw, *Dissert. on Infant Baptism*, 3d\ ed. pp.\ 291–346. Wilson, *Infant Baptism a Scriptural Service*, Lond. 1848, pp.\ 338–381.
