## The Sacrifice of the Mass, and Other Forms of the Sacrificial Theory

The claim to the possession of a real priesthood, and to the power of making and presenting to God a real propitiatory sacrifice, is fundamental to the theory of the Church of Rome, and is one of the great pillars on which its spiritual strength leans. The right to stand between God and man in the character of mediator, to exercise the priest's office in place of Christ on the earth, to negotiate as man's intercessor with God, and to arrange the terms of his acceptance or condemnation, to make and offer the sacrifice which alone can avail unto justification of life, to retain or remit sin, to give or withhold saving grace,—in short, the claim to the *sacerdotal* office lies at the very foundation of the Popish system. This one principle of a priestly power existing in her ministry, accompanying all their administrations, and sanctifying all their acts, runs through the whole details of the Church system of Rome, and is the grand secret of very much of its success. We see it fully and conspicuously developed in connection with the Romish doctrine of the Supper, and as the foundation of the sacrifice of the mass. But it is not confined to that one department of the Popish Church system. The sacerdotal principle pervades it, more or less, throughout its entire range; and the Church of Rome has thus added to its many sins the one emphatic sin of usurping the place of Him who has an unchangeable priesthood in heaven and on earth, and of seizing out of *His* hands the powers that He wields as "Priest for ever." But great and awful though the sin be of arrogating the place and prerogatives of the one High Priest of His people, it is yet a sin which pays its price to the Church that commits it, in the spiritual prestige that it confers, and the spiritual authority that it brings along with it. A sense of the need of some mediator between the sinner and an offended God, a feeling of the absolute necessity of a priest and intercessor for a fallen creature, to negotiate the terms of his pardon and acceptance, can hardly ever be rooted out from the guilty conscience. And the Church of Rome, when it ventures to arrogate to itself on earth that very office which guilty nature needs, and succeeds in its perilous claim to be regarded as the only priest and intercessor between sinners and God, establishes for itself a spiritual dominion over the souls of its victims, greater and more absolute than any other dominion in this world.[^03.04.01] And hence the tenacity with which the Romish Church clings to the claim of a priestly or sacerdotal office, inseparably connected as it is with some of the most monstrous and incredible pretensions, with the dogma of transubstantiation, with the claim to forgive sin, which none but God can do, with the pretence of making and presenting a Divine and propitiatory sacrifice to the Almighty.

[^03.04.01]: ["Then that feast of free grace and adoption to which Christ invited His disciples to sit as brethren and co-heirs of the happy covenant, which at that table was to be sealed to them, even that feast of love and heavenly-admitted fellowship, the seal of filial grace, became the subject of horror and glouting adoration, pageanted about like a dreadful idol; which sometimes deceives well-meaning men, and beguiles them of their reward by their voluntary humility, which indeed is fleshly pride, preferring a foolish sacrifice and the rudiments of this world, as St.\ Paul to the Colossians explaineth, before a savoury obedience to Christ's example. Such was Peter's unseasonable humility, as then his knowledge was small, when Christ came to wash his feet, who at an impertinent time would needs strain courtesy with his Master, and falling troublesomely upon the lowly, all-wise, and unexaminable intention of Christ, in what He went with resolution to do, so provoked by his interruption the meek Lord, that He threatened to exclude him from his heavenly portion, unless he could be content to be less arrogant and stiff-necked in his humility."—Milton, *Prose Works*, Lond. 1753, vol.\ i. p.\ 2.]

In spite of the explicit abrogation of the office with the abrogation of the Old Testament dispensation; in spite of the palpable inconsistency of the office with the spirit of the Gospel, and the privileges of believers; and, worse still, in spite of the inconsistency of the office with the sole priesthood of Christ, the Church of Rome ordains each one of her ministers to be a *priest*, and invests him with the power and authority of an earthly priesthood. It needs must be that a priest have a sacrifice to present unto God. "This man must of necessity have somewhat to offer." And having ordained, as she alleges, a real priest, the Church of Rome proceeds to put into his hands a real sacrifice, and gives him warrant to offer it to God for the sins of the living and the dead.

The doctrine of the Church of Rome on this vital point is laid down in such a manner in her authorized formularies that it is impossible to explain it away. The Council of Trent has defined it in such terms, that the attempts made by more modern Romanists to soften down the atrocious dogma of the real offering-up of the sacrifice of the Lord, body and blood, soul and Divinity, in the Sacrament by the priest, are in vain.[^03.04.02] Speaking of "the institution of the most holy sacrifice of the mass," the Council declares that it is "a visible sacrifice, as the nature of man requires, by which that bloody one, once to be accomplished on the Cross, might be represented, and the memory of it remain even unto the end of the world." And with this statement, expressive of the representative or commemorative character of the ordinance, the apologists of the Church of Rome, whose desire is to conceal the real doctrine held by her on this subject, very often terminate their quotation, as if the Council of Trent held it to be no more than a symbolical sacrifice in memory of Christ's. But that this is not the case, the words of the Council's definition leave us no room to doubt. It proceeds: "For after the celebration of the old passover, which the multitude of the children of Israel sacrificed in memory of their departure from Egypt, Christ instituted a new passover, even Himself, to be sacrificed by the Church through the priests under visible signs ([*Seipsum ab Ecclesiâ per sacerdotes sub signis visibilibus immolandum*]{lang=la}<!-- italics added, not in original -->), in memory of His departure out of this world unto the Father, when by the shedding of His blood He redeemed us and snatched us from the power of darkness, and translated us into His kingdom." "And since in this Divine sacrifice, which is performed in the mass, that same Christ is contained and immolated in an unbloody manner, who on the altar of the Cross once offered Himself with blood, the holy Synod teaches that that sacrifice is, and becomes of itself, truly propitiatory; so that if with a true heart and right faith, with fear and reverence, we approach to God, contrite and penitent, we may obtain mercy and find grace to help in time of need. Wherefore the Lord, being appeased by the offering of this, and granting grace and the gift of repentance, remits crimes and sins, even great ones. For it is one and the same victim,—He who then offered Himself on the Cross being the same Person who now offers through the ministry of the priests, the only difference being in the manner of offering ([*Una enim eademque est hostia, idem nunc offerens sacerdotum ministerio, qui Seipsum tunc in cruce obtulit, sola offerendi ratione diversa*]{lang=la}<!-- italics added, not in original -->)." And, once more: "If any shall say that the sacrifice of the mass is only one of praise and thanksgiving, or a bare commemoration of the sacrifice which was made upon the Cross, but not propitiatory; or that it only profits him who receives it, and ought not to be offered for the living and the dead, for sins, pains, satisfactions, and other necessities,—let him be accursed."[^03.04.03]

[^03.04.02]: ["The mass is the great Diana of the Popish priests, the craft by which mainly they have their living, and they will never renounce it; but some Papists have shown a great desire to explain away the doctrine of the Council of Trent upon this point. Bossuet, in his *Exposition*, ch.\ xiv. (*Doct. Cath. Expositio*, Antwerpiæ 1680, p.\ 145), explains the sacrifice of the mass in such a way as to exclude the idea of its being a propitiatory sacrifice, and in substance resolves it into the intercession of Christ personally present on the altar under the appearances of bread and wine. He says that 'it wants nothing to be a true sacrifice,'—a statement sufficiently cautious, but which, in the first or suppressed edition of his work, was thus expressed: 'it may be very reasonably *called* a sacrifice.' He swore at his ordination that it was not only a true, but a proper and propitiatory sacrifice. .\ .\ . Another attempt has been made by Popish controversialists to escape from the doctrine to which they are all sworn, thus betraying a consciousness that that doctrine is, in its plain honest meaning, incapable of defence. It is set forth in Prof. Brown's *Supplement to the Downside Discussion*, 1836, p.\ 44\ f., as affording a conclusive answer to Protestant objections. It is in substance this, that a sacrifice may be called propitiatory in two different senses: first, as being actually satisfactory to Divine justice, and paying the price of our redemption; and second, as making application to us of the benefits purchased by Christ. In the first sense, the death of Christ on the Cross is the only propitiatory sacrifice, and it is only in the second sense that the mass is called by that name. But this is evidently a mere evasion. To say that the benefits of one sacrifice are applied to us by means of another sacrifice of a different kind, is surely very like nonsense. A propitiatory sacrifice, in the fair and honest meaning of the words, can be nothing else than a sacrifice which expiates sin, by satisfying Divine justice and paying the price of our redemption. If the Council of Trent taught merely that the Lord's Supper is one of those means of grace by which the benefits purchased by Christ's propitiatory sacrifice are applied to men individually, no Protestant would object to it; but if this had been their meaning, they would never have defined the mass to be a propitiatory sacrifice, which, according to the established use of language, ascribes to it a far higher efficacy. The great body of Popish writers are in the habit of asserting, in accordance with the decrees of the Council of Trent, that the sacrifices of the Cross and of the mass are one and the same sacrifice; but if it be true, as the pretence which we are exposing implies, that the sacrifice of the Cross is a propitiatory sacrifice in one sense, and that the sacrifice of the mass is not a propitiatory sacrifice in the same, but only in a different sense, then surely they cannot possibly be one and the same sacrifice."—Cunningham, in *Notes on Stillingfleet's Doct. and Pract. of the Church of Rome*, p.\ 213\ ff.]

[^03.04.03]: [*Concil. Trident. Canones et Decreta*]{lang=la}, Sess.\ xxii.; [*De Inst. SS. Missæ Sacrificii*]{lang=la}, cap.\ i. ii. can.\ iii.

There are two things in regard to the doctrine of the Church of Rome put beyond all dispute or cavil by these statements. *First*, it is Christ Himself transubstantiated into the elements, and corporeally present in the Sacrament, that is offered up by the priest as a real sacrifice. It is utterly impossible for Romanists to escape from this dogma so long as the language of Trent remains uncancelled. No attempt can succeed to give it a mystical or symbolical meaning, and soften down the authoritative assertion of the Council, that in the Supper there is a real sacrifice of Christ Himself by the priest. Romish controversialists may indeed adopt different modes of explaining how the sacrifice of the mass stands related to the sacrifice of the Cross. Some of them, like Harding the Jesuit, in his reply to Bishop Jewel, may plainly and unhesitatingly assert "that Christ offered and sacrificed His body and blood twice,—first in that holy Supper, unbloodily, when He took bread in His hands and brake it, and afterwards on the Cross with shedding of His blood."[^03.04.04] Others of them, like Möhler, in his *Symbolism*, with a view to make the doctrine less palpably inconsistent with Scripture, may assert another form of it, and maintain that there are not two sacrifices, but one, and that the sacrifice of the Supper constitutes a part of that sacrifice which Christ offered on the Cross; or, to use Möhler's own language, "Christ's ministry and sufferings, as well as His perpetual condescension to our infirmity in the Eucharist, constitute one great sacrificial act, one mighty action undertaken out of love for us, and expiatory of our sins, consisting, indeed, of various individual parts, yet so that none by itself is, strictly speaking, *the* sacrifice." "The will of Christ to manifest His gracious condescension to us in the Eucharist, forms no less an integral part of His great work than all besides, and in a way so necessary, indeed, that whilst we here find the whole scheme of redemption reflected, without it the other parts would not have sufficed for our complete atonement."[^03.04.05] But however Romanists may choose to explain it,—whether as a repetition of the sacrifice of the Cross, or a continuation of it,—the Supper is unquestionably, according to the doctrine of the Church of Rome, a *real* sacrifice, made up of Christ's body and blood. And *second*, this real sacrifice is truly propitiatory in its nature, having virtue in it to satisfy Divine justice, and to constitute a proper atonement for sin. These two doctrinal positions are clearly and undeniably laid down by the Council of Trent, and in such a manner that Romanists cannot evade them. And it is certainly one cause of thankfulness, and no small one, that the Council of Trent was overruled by Divine Providence to put this and other of the monstrous tenets of Romanism into such a dogmatic and articulate form, that it is now utterly impossible for the Church of Rome to deny or escape from them.

[^03.04.04]: Jewel, *A Replie unto M. Hardinge's Answear*, Lond. 1565, p.\ 564. [For some of the methods of evading the legitimate consequences of the sacrificial theory, which have been in use from Harding's time to our own, see the same work, art.\ xx. pp.\ 593–598. Cf. Goode, *Rule of Faith*, vol.\ ii. pp.\ 173\ ff.]

[^03.04.05]: Möhler, *Symbolism*, Robertson's Transl. 2d\ ed. vol.\ i. p.\ 337. [[*Symbolik*]{lang=de}, 6te\ Aufl. p.\ 307.]

What, then, are we to say to the real sacrifice asserted by the Church of Rome, a true propitiation to God for sin, repeated day after day by countless priests who have authority and power to make and offer it?

### [There is one Priest, and no more than one under the Gospel]

The doctrine of the Church of Rome is in direct contradiction to the doctrine of Scripture, which declares that there is one Priest, and no more than one under the Gospel.

"Sacrifice and priesthood," say the Fathers of the Council of Trent, "are so joined together by the ordinance of God, that they existed under every dispensation."[^03.04.06] There can be no doubt that the statement is correct in this sense, that wherever there is a sacrifice, there must be a priest to offer it, and wherever there is a priest, he must of necessity have a sacrifice to offer.[^03.04.07] And hence, as part of the sacrificial theory of the Supper and essential to it, the ordination by which the Church of Rome sets apart persons for the work of the ministry includes, as its main and characteristic feature, a commission not to preach the Gospel and to dispense its ordinances, but to make and offer sacrifices to God for the souls of men. Hers is mainly and distinctively an order of priests, and not an order of ministers,—a succession from age to age of sacrificers and intercessors, and not of preachers. And thus her system is distinctively opposed to the system of Scripture, which points to *one* Priest, and forbids our lips to name a second in the Gospel Church. The argument of the last section might be sufficient, without further illustration, to establish this. But the point is so vital, and it is brought out with such power and effect by the Apostle Paul, that I cannot help adverting to his statements on this subject.

[^03.04.06]: Sess.\ xxiii. cap.\ 1.

[^03.04.07]: ["If we deny," says Dr.\ Jolly, "that there is any proper material sacrifice in the Christian Church, we pull down proper priesthood, and open a door to Socinianism ./ ./ . While the Church of England retains the Christian priesthood, she retains by implication the Christian sacrifice; for every priest must have somewhat to offer, sacrifice and priesthood being correlative terms; they stand or fall together."—*The Christ. Sac. in the Euch.* 2d\ ed. p.\ 139.]

The grand design of that magnificent exposition of the doctrine of Christ's office and nature and work in the Epistle to the Hebrews, is to prove that, far above and beyond the mediators and priests under the law, Christ was the *one* Son and the *one* Priest of God, in a way and manner altogether exclusive and peculiar, and such as to contrast Him with all others who ever, in any secondary sense, bore these names. In regard to the priesthood more especially, there were under former dispensations two orders of priests, with one of which the apostle *compares* our Lord, with the other of which the apostle *contrasts* Him; and both the comparison and the contrast serve to bring out more distinctly the singular and exclusive character that He bears as *the* Priest of God, who has neither partner nor successor in the office. There was, according to the apostle, a priesthood after the order of Melchisedec, and there was a priesthood after the order of Aaron. With the priesthood after the order of Melchisedec our Lord is compared. There was room in that order for but one Priest, and no more than one; and for this reason, as stated by the apostle, "He abideth a Priest continually." In the office that he held He had no predecessor, and He had no successor. Melchisedec stood alone in the typical order that bears his name; and the more surely and distinctly to mark out this singularity of his position, we are told, with respect to his office, that he was "fatherless, motherless, ungenealogied, having neither beginning of days nor end of life" ([ἀπατωρ, ἀμητωρ, ἀγενεαλογητος, μητε ἀρχην ἡμερων μητε ζωης τελος ἐχων]{lang=el}).[^03.04.08] And such as the type was, so is the Antitype. The Lord Jesus Christ was "made a Priest after the order of Melchisedec;" and, like that of His type, His office is singular and exclusive; He knows neither predecessor nor successor in it; having not only in His Divine nature, but in His mediatorial character, "neither beginning of days nor end of life." None went before, and none shall come after this Priest; or, as the apostle expresses it, His office is one "that passeth not from Him to any other."[^03.04.09] The comparison instituted between our Lord's priesthood and that of Melchisedec demonstrates that He is the *one* Priest, with none to go before or succeed Him in that character.

[^03.04.08]: Heb.\ 7:3.

[^03.04.09]: Heb.\ 7:24.

But again, with the priesthood of Aaron that of our Lord is contrasted by the apostle; and the contrast serves to bring out in like manner the very same grand doctrine. In that priesthood there were not *one*, but many priests, following each other in rapid succession. The mortal and dying men who inherited the blood and the office of Aaron "were not," as the apostle tells us, "suffered to continue by reason of death."[^03.04.10] One after another passed away in swift succession, so that in the not lengthened period of the Aaronic Church there were truly "*many priests*," following each other rapidly in office, as ever and anon death removed them from beside the altar where they sacrificed and interceded. With them our Lord is contrasted, and not compared in this respect. "This man, because He continueth ever, hath an unchangeable priesthood." "He is consecrated for evermore." He is endued with "the power of an endless life," and "ever liveth to make intercession for His people."[^03.04.11] Compared with the order of Melchisedec, and contrasted with the order of Aaron, our Lord is emphatically marked out as the one Priest of God, who can have none to follow, even as He had none to go before Him in His office. And the many priests, anointed day by day continually, and succeeding each other in rapid succession in the Church of Rome, are most decisively declared to be inconsistent with His *one* glorious priesthood.

[^03.04.10]: Heb.\ 7:23.

[^03.04.11]: Heb.\ 7:16, 24, 25, 28.

### [There is one sacrifice, and no more than one, under the Gospel]

The Popish theory of the Lord's Supper is in direct opposition to the doctrine of Scripture, which declares that there is one sacrifice, and no more than one, under the Gospel.

This argument is likewise brought out with commanding force and effect—as if by way of anticipation of the very error of the Papacy—in Paul's Epistle to the Hebrews. He exhibits the contrast between the many priests under the law and the one Priest of God under the Gospel, immortal, and living ever to discharge that office of priesthood in which He had no predecessor and can have no follower, and in which, like Melchisedec, He stood alone. But in close relation with this, he exhibits the contrast also between the many sacrifices under the law with their ceaseless repetition, and the *one* sacrifice of the Lord Jesus Christ, which never was, and never could be, repeated. The argument by which the apostle demonstrates the unspeakable superiority of the sacrifice of Christ over the sacrifices offered by the sons of Aaron, is a brief and decisive one. The very fact of the repetition of the one, and the non-repetition of the other, was the conclusive evidence of that superiority. The sacrifices under the law were repeated day by day continually; the priest had never done with offering, and the altar never ceased to be wet with the blood of the victims. What was done to-day had to be repeated to-morrow; and the sacrifice was never so completely made and finished but that it had to be repeated afresh, and renewed times without number. And why? The reason was obvious. They were essentially imperfect. They could never so accomplish the great object of atoning for sin but that their renewal was necessary; and what was done on one day had to be supplemented by what was to be done on the next. "The law," says the apostle, "having a shadow of good things to come, and not the very image of the things, can never with those sacrifices which they offered year by year continually make the comers thereunto perfect. For then would they not have ceased to be offered? because that the worshippers once purged should have had no more conscience of sins. But in those sacrifices there is a remembrance again made of sins every year."[^03.04.12] The fact of their ceaseless repetition was the evidence of their essential imperfection. But in contrast with this, and as an evidence of its sufficiency, the apostle urges the consideration that the sacrifice made by Christ was offered up *once*, and no more than once. It stood alone, as an offering made once for all, and never again to be repeated,—a sacrifice so complete in its single presentation that it admits of no repetition or renewal. Christ cannot die a second time upon the Cross, as if His first death were incomplete in its efficacy or its merits; for "by one offering He has perfected for ever them that are sanctified" or atoned for. Again and again the apostle renews his argument, and his assertion of the fact on which the argument is founded. "Christ was *once* offered to bear the sins of many." "Nor yet that He should offer Himself *often* as the high priest." "For then must He *often* have suffered since the foundation of the world." "He entered in *once* into the holy place;" and "we are sanctified through the offering of the body of Jesus Christ *once* for all." "By *one* offering He hath perfected for ever them that are sanctified."[^03.04.13] The argument is decisive. The perfection of Christ's sacrifice, and the non-repetition of Christ's sacrifice, are inseparable. If that sacrifice needs to be repeated, then it cannot be perfect.

[^03.04.12]: Heb.\ 10:1–3. 

[^03.04.13]: Heb.\ 9:12, 25–26, 28; 10:10, 12, 14.

And the reasoning of the apostle is conclusive, as if by anticipation, against the many sacrifices of the Church of Rome in the Supper, whatever explanation may be adopted by its advocates to explain away the contradiction between their practice and the doctrine of Scripture. Let the sacrifice of the mass be a repetition of the sacrifice of Christ upon the Cross, as some Romanist controversialists hold it to be,—and their explanation plainly and undeniably means, that the sacrifice of the Cross needs to be repeated day by day, in order to accomplish the salvation of sinners. Or, let the sacrifice of the mass be a continuation of the sacrifice of Christ on the Cross, and a part of the same atonement, as other Romanists expound it,—and this explanation plainly and undeniably means, that the sacrifice of the Cross was not finished when Christ bowed His head and gave up the ghost. Explain the connection as you will between the sacrifice of the mass and the atonement made upon the Cross, it is utterly inconsistent with the argument of the apostle by which he proves the unapproachable perfection of Christ's work, from its being that one offering which never can be repeated or followed by another.[^03.04.14]

[^03.04.14]: [Comp. the *seven* senses in which the Church of England, according to Dr.\ Wordsworth's interpretation of her sentiments, holds that there is a sacrifice in the Lord's Supper. *Theoph. Angl.* ed.\ 1863, p.\ 220.]

### [Mass is a pretended sacrifice]

What is essential to the very nature of a true propitiatory sacrifice is awanting in the pretended sacrifice of the mass.

What was offered on the altar in former times could be no propitiatory sacrifice to God unless it was dedicated to Him by death. Believing sacrifice itself to be a positive institution of God, we must look for the nature and import of the observance only in His Word, and in the practice sanctioned by His appointment. And taking the case of the Old Testament sacrifices, we are warranted in saying that they were uniformly dedicated to God by death, and that "without shedding of blood there could be no remission."[^03.04.15] There were, indeed, offerings under the law not connected with the shedding of blood, and not accompanied by the destruction of life; but these were not propitiatory. In every case of a propitiatory offering the victim was slain, and the atonement made through the shedding of blood. Expiation and the death of the offering—atonement and shedding of blood—were so inseparably connected, that there could be no real sacrifice of a propitiatory nature when the sacrifice was not dedicated to God by death. From the very earliest times blood was accounted a holy thing, not to be eaten or made use of for common purposes; and the very terms of the prohibition explain the reason of it: "For the life of the flesh is in the blood, and I have given it to you upon the altar to make an atonement for your soul; for it is the blood that maketh atonement for the soul."[^03.04.16] Without blood shed there could be no expiation. And here lies one difficulty of the Romish dogma of the sacrifice of the mass. It is a propitiation for the sins of the living and the dead; it is no bare commemoration of a sacrifice, but itself a sacrifice, with virtue to satisfy Divine justice and atone for sin; it is an offering of expiation offered wherever there is a priest to consecrate the ordinance and present it to God. It is a sacrifice of Christ, offered up in propitiation of His Father's righteous displeasure, and efficacious for the remission of sin. But yet we are assured by the apostle that "Christ dieth no more; death hath no more dominion over Him. For in that He died, He died unto sin *once*: but in that He liveth, He liveth unto God."[^03.04.17] The Lord Jesus Christ, in His glorified human nature, has long since passed away from the scene of His suffering and humiliation; seated at the Father's right hand, He has rested Him from His work of sorrow and blood, and can repeat no more the agony of the Garden or of the Cross. He does bear with Him indeed in heaven, impressed for ever on His human flesh, the tokens of suffering and crucifixion; "as a lamb that has been slain," He appears on high in the sight of His Father and His angels, marked with the visible evidence of sacrifice and death. But He repeats the sacrifice no more; His blood is not afresh poured out. The proofs of His once finished sacrifice which He carries about in His person are enough; and with these silent but eloquent witnesses to make good His cause, He pleads the virtue of that sacrifice, and never pleads in vain. His uninterrupted and continual advocacy, founded on the merits of His one sacrifice, all-sufficient and complete, supersedes the necessity of its repetition; He needs to die no more for the many sins of His people, which they daily renew, because He once died a death enough for them all, and now lives a life of everlasting intercession, based upon that death, for His people. Without shedding of blood, without atoning suffering, without life rendered as expiation for life, the pretended sacrifice of the mass is inconsistent with the scriptural idea of sacrifice dedicated to God by death.[^03.04.18]

[^03.04.15]: Heb.\ 9:22. 

[^03.04.16]: Lev.\ 17:11.

[^03.04.17]: Rom.\ 6:9–10.

[^03.04.18]: Bellarm. *Disput. de Euch.* lib.\ v. cap.\ ii. etc. Ames. *Bellarm. Enerv.* tom.\ iii. lib.\ iv. cap.\ ix. [Stillingfleet, *Doct. and Pract. of the Church of Rome*, Cunningham's ed. pp.\ 197–221; with the copious references to the literature of this subject given by the Editor, p.\ 220\ f.]

Upon such grounds as these we are warranted to say that the sacrificial theory of the Church of Rome, more fully developed in her dogma of the mass, but running throughout her whole spiritual system, is entirely opposed to the doctrine of the Word of God, which asserts, as fundamental to the Gospel, that as there is but one Priest, so there is but *one* sacrifice known in the New Testament Church. But there are various modifications of this sacrificial theory which, avoiding the extreme doctrine of the Papacy, are held by many semi-Romanists, and still assert that the Lord's Supper is a sacrifice. There are two of these held very commonly by High Churchmen in the English Establishment, to which I would very briefly advert.

**1st**, In a sense very different from the Romish, it was held by not a few of the Christian Fathers in the early centuries,—and the doctrine has been revived in more recent times in the Church of England,—that the elements of bread and wine were a true material sacrifice, not indeed propitiatory, but eucharistic; very much in the same way as the first fruits laid upon the altar by appointment of the Mosaic law, were a thank-offering to God for the overflowing of His bounties to His creatures. According to this view, the elements of bread and wine, offered to God in the Supper as a material sacrifice without blood, are the fulfilment of the prophecy of Malachi, in which he foretells, in regard to Gospel times, that "a pure offering," as contradistinguished from the bloody sacrifice of the law, should then be offered in to God's name. "From the rising of the sun to the going down of the same, Thy name shall be great among the Gentiles; and in every place incense shall be offered unto Thy name, and a pure offering."[^03.04.19] This sacrificial theory of the Supper is certainly free from the vital and most fundamental error of the Church of Rome, when it ascribes to the sacrifice in the ordinance a propitiatory character; but it is open to insurmountable objections.

[^03.04.19]: Mal.\ 2:11.

First, a material sacrifice, in the sense of a thank-offering to God for the bounties of His providence, has not the slightest countenance in any of those passages of the New Testament which describe the nature and design of the Supper. It is hardly anything else than a conceit, gratuitously invented by those who saw that it was impossible to regard the Supper as a propitiation for sin, but who were anxious, in conformity with the unguarded language of the patristic writers on the subject, to devise some plausible excuse for applying the term "sacrifice" to the Supper.[^03.04.20] Second, the theory is entirely inconsistent with the first and primary characteristic of the Supper, as clearly laid down in Scripture, namely, that it is an ordinance commemorative of the propitiatory sacrifice of Christ. Third, the theory of a material sacrifice in the Supper, in the sense of a thank-offering of bread and wine for the bounties of Providence, is repugnant to the spiritual nature of the Gospel dispensation, which stands opposed to typical worship.

[^03.04.20]: ["[Equidem quum pium atque orthodoxum de toto hoc mysterio sensum retinuisse eos]{lang=la} (some of the Fathers who used sacrificial language about the Supper) [videam, neque deprehendam voluisse unico Domini sacrificio vel minimum derogare, ullius impietatis damnare eos non sustineo; excusari tamen non posse arbitror quin aliquid in actionis modo peccaverint. Imitati sunt enim propius Judaicam sacrificandi morem quam aut ordinaverit Christus, aut Evangelii ratio ferebat. Sola igitur est præpostera illa anagoge in quâ merito eos quis redarguat, quod non contenti simplici ac germanâ Christi institutione, ad Legis umbras nimis deflexerunt. .\ .\ .\ . Sacerdotes Levitici, quod peracturus erat Christus, sacrificium jubebantur figurare; sistebatur hostia quæ vicem ipsius Christi subiret; erat altare in quo immolaretur; sic denique gerebantur omnia, ut ob oculos poneretur sacrificii effigies, quod Deo in expiationem offerendum erat. At peracto sacrificio, aliam nobis rationem Dominus instituit, nempe ut fructum oblati sibi a Filio sacrificii ad populum fidelem transmittat. *Mensam* ergo nobis dedit, in quâ epulemur, non *altare* super quod offeratur victima; non *sacerdotes* consecravit qui immolent, sed *ministros* qui sacrum epulum distribuant.]{lang=la}"—Calvin, *Inst.* lib.\ iv. cap.\ xviii. 11, 12. Cf. Waterland, *Review of the Doct. of the Euch.* Camb. 1737, pp.\ 467–534. Arnold, *Fragment on the Church*, 2d\ ed. pp.\ 111\ ff. 126–132.]

**2d**, There is another sacrificial theory of the Supper, much more common than the one now mentioned, and indeed, with various but unimportant modifications, the prevalent theory among those High Churchmen of the English Establishment who reject the extreme views of Popery, as asserted in the doctrine of the mass, but who hold that in the Supper there is a real propitiatory sacrifice, and a real sacrificing priest. According to this view, the elements of bread and wine, not transubstantiated, but remaining unchanged, become, by the words of institution and the consecration of the priest, the body and blood of Christ symbolically and mystically; in consequence of the sacramental union between the sign and the thing signified in the Sacrament, the elements are both to God and to us equivalent to and of the same value with Christ Himself; and the offering up to God of the elements, thus both representing a crucified Saviour, and not inferior in virtue or worth to the Saviour Himself, becomes a true propitiatory sacrifice made to the Almighty for sin.[^03.04.21] Upon this theory of the Supper, the office of priest in the Christian Church is similar to that of priest under the law: both offer to God real, although symbolical sacrifices, equally pointing to Christ,—there being this difference, that the Aaronic priesthood offered a sacrifice of blood in the prospect of the Saviour's sacrifice to come; while the Christian priesthood offers an unbloody sacrifice in memory of the Saviour's sacrifice now past; and also, that the sacrifices presented now in the Supper, in consequence of their sacramental union with Christ, are infinitely more precious than the sacrifices of the former economy. Such, briefly, and so far as I am able to understand it, is the prevalent doctrine among the majority of the High Church party in the Church of England at the present day, who are not yet prepared, as an extreme section of them appear to be, to accept the Tridentine definitions of the nature and efficacy of the Sacrament of the Lord's Supper. It is maintained and expounded at length in a work recently republished in the Anglo-Catholic Library, entitled, *The Unbloody Sacrifice and Altar Unveiled and Supported*, by Johnson.

[^03.04.21]: "I conclude that, though the eucharistical elements are not the substantial Body and Blood,—nay, they are the figurative and representative symbols of them,—yet they are somewhat more too: they are the *mysterious* Body and Blood of our ever blessed Redeemer. By the *mysterious* Body and Blood, the reader will easily perceive I mean *neither substantial nor yet merely figurative, but the middle between these extremes*, viz. the Bread and Wine made the Body and Blood of Christ by the secret power of the Spirit; and apprehended to be so, not by our senses, but by our faith, directed and influenced by the same Holy Spirit, and made the Body and Blood in such a manner as human reason cannot perfectly comprehend."—Johnson, *The Unbloody Sacrifice*, Oxf. 1847, vol.\ i. p.\ 323. Cf. pp.\ 265\ ff.

This theory, while excluding the dogma of transubstantiation, which Romanists feel to be necessary to give consistency and foundation to their doctrine of the Supper, approaches in other essential respects very closely to that doctrine, asserting, as it does, a real sacrificing priest and a real propitiatory sacrifice in the Supper.[^03.04.22] The principles already laid down in opposition to the Popish theory of the Supper are almost all equally available against the now mentioned modification of it. It is subversive of the whole doctrine and character of the Gospel. Under the Christian dispensation there is no priest but *One*, and He is in heaven. It is His incommunicable name, which none in heaven or on earth may bear but Himself. There is no sacrifice or propitiation but *one*, and that was finished on the Cross erected upon Calvary, looking back, as it does, for thousands of years over the long array of bloody offerings, which were but the types that pointed towards it, not yet come; and looking forward, as it does, over the long array of ordinances in the Christian Church, commemorative of it, now that it is past. Neither type beforehand, nor commemoration afterhand, could share in its character as an expiatory sacrifice for sin. There is now no dedication of victims to God by death,—life given for life, and blood exchanged for blood,—in order to make a propitiation. The tragedy of the Cross cannot now be renewed, nor atoning blood be shed afresh; and yet "without the shedding of blood there is no remission" in Sacrament or in sacrifice. Under whatever form or modification the sacramental theory be held, which asserts in the Supper a real sacrifice, and a true propitiation for sin, it is a dishonour done to the Lamb of God, who "by the one offering of Himself has perfected for ever them that are sanctified," and who, in virtue of that one Divine offering, now "liveth for ever to make intercession for His people."[^03.04.23]

[^03.04.22]: ["The Eucharist, after Baptism, is the *only* mean of the forgiveness of our sins."—Jolly, *Christ. Sacrifice in the Euch.* 2d\ ed. p.\ 155. Goode, *The Case as it is*; a Reply to Dr.\ Pusey's Letter to the Archbishop of Canterbury, 3d\ ed. pp.\ 17–20.]

[^03.04.23]: Johnson, *The Unbloody Sacrifice and Altar Unveiled and Supported*, Oxf. 1847, vol.\ i. pp.\ 265–433, vol.\ ii. p.\ 30, etc. Garbett, *Bampton Lecture*, 1842, vol.\ i. pp.\ 231–354. Wilberforce, *Doct. of the Holy Eucharist*, 3d\ ed. pp.\ 299–338. Goode, *Nat. of Christ's Pres. in the Euch.* Lond. 1856, vol.\ i. pp.\ 11–28, etc., vol.\ ii. pp.\ 973–978. *Rule of Faith*, Lond. 1842, vol.\ ii. pp.\ 135–190. ["Q.\ What institution hath Christ appointed for the preserving and nourishing in us this Divine principle or spiritual life, communicated to us in Baptism and Confirmation?—A.\ The Christian Sacrifice of the Holy  Eucharist. Q.\ Did He not offer the sacrifice of Himself upon the Cross?—A.\ No. It was slain upon the Cross; but it was offered at the institution of the Eucharist. .\ .\ .\ .  Q.\ What is the consequence of that privilege (the priest's repeating our Lord's 'powerful words')?—A.\ They (the bread and wine) are in a capacity to be offered up to God as the great Christian sacrifice. Q.\ Is this done?—A.\ Yes. The priest immediately after makes a solemn oblation of them. Q.\ Does God accept of this sacrifice?—A.\ Yes; and returns it to us again to feast upon. Q.\ How do the bread and cup become capable of conferring all the benefits of our Saviour's death and passion?—A.\ By the priest praying to God the Father to send His Holy Spirit upon them. Q.\ Are they not changed?—A.\ Yes; in their qualities."—Catechism of Bishop Innes of Brechin, 1841, as quoted in *Peculiarities of the Scottish Episcopal Church, taken from authentic sources*, Aberdeen 1847, p.\ 2. Bishop Jolly laments that this "primitive doctrine" is "so dimly seen" in the present Communion Service of the Church of England. "The words require some stretch of thought to make them speak the meaning and produce the effect of the former" more ancient liturgies. He thinks, however, that Bishop Andrews and others "must have *understood* the English Office to have implied the eucharistic sacrifice, however lamelike the form was."—*Christ. Sacrifce in the Euch.* 2d\ ed. pp.\ 93, 99. Cf. pp.\ 81\ ff. 129–136.]
