## Transubstantiation

Both the Lord's Supper and Baptism are Divine appointments of perpetual authority in the Christian Church. Both are outward and sensible signs, expressive of spiritual truths; both are seals of a federal transaction between Christ and the believer in the ordinance; and both, while they presuppose the existence of grace on the part of the receiver, are at the same time the means, by the Spirit, and through the believer's faith, of adding to that grace, and imparting a fresh spiritual blessing. And thus, parallel as the Sacraments of the Christian Church are in their nature and efficacy, they are alike also in the misapprehensions to which they have been exposed. Baptism has been misrepresented as an ordinance possessed in itself of an independent and supernatural virtue, apart from the spiritual state or disposition of the participator, so that, [*ex opere operato*]{lang=la}, it infallibly communicates saving grace to the soul. And, in like manner, the Sacrament of the Lord's Supper has been misrepresented as an ordinance embodying in itself a spiritual power, and efficacious of itself to impart saving grace. The full-grown and legitimate development of these views in regard to the Lord's Supper is to be found in the principles of the Church of Rome, and in the doctrine which she propounds under the name of transubstantiation.

The Romish system of belief and instruction in regard to the ordinance of the Supper is briefly this. At the original institution of the ordinance, it is believed by the Church of Rome that our Lord, by an exertion of His almighty power, changed miraculously the bread and wine into His body and blood, His human soul and His Divine Godhead; that this supernatural change was effected in connection with the words of institution uttered by Him: "This is my body; this is my blood;" that in giving the appearance of ordinary elements into the hands of His Apostles, He actually gave Himself, including both His humanity and His Divinity; and that they really received and ate His flesh, and drank His blood, with all their accompanying blessings to their souls. And what was thus done in a supernatural manner by Christ Himself at the first institution of the ordinance, is repeated in a manner no less supernatural every time the Lord's Supper is administered by a priest of Rome with a good intention.[^03.02.01] The priest stands in the place of Christ, with an office and power similar to Christ's, in every case in which he dispenses the Supper; the words of institution repeated by the lips of the priest are accompanied or followed by the same supernatural change as took place at first; the substance of the bread and wine used in the ordinance is annihilated, while the properties of bread and wine remain. In place of the substance of the natural elements, the substance of Christ in His human and Divine nature is truly present, although under all the outward attributes of bread and wine; and those who receive what the priest has thus miraculously transubstantiated are actual partakers of whole Christ, under the appearance of the ordinary sacramental elements.

[^03.02.01]: [In what is called the "Scotch Communion Office" the words of "Invocation" are: "We most humbly beseech Thee, merciful Father, to bless and sanctify with Thy Word and Holy Spirit these Thy gifts and creatures of bread and wine, *that they may become* the body and blood of Thy most dearly beloved Son." The corresponding words in the Romish missal are: "*that they may become to us* the body and blood of Thy most dearly beloved Son" ([ut nobis corpus et sanguis fiant dilectissimi Filii Tui]{lang=la}). The words of the Scotch Office, therefore—as has often been pointed out—seem to make an even more unqualified assertion of transubstantiation than those of the Romish service,—the subjective element, which may be thought to be introduced by the "[nobis]{lang=la}," being in the former case entirely thrown out. By the 21st canon of the Scotch Episcopal Church, it is enacted "that the Scotch Communion Office continue to be held of primary authority in this Church." Compare some of the recent utterances of English High Churchmen: "We are teaching men to believe *that God is to be worshipped under the form of bread*; and they are learning the lesson from us, which they have refused to learn from the Roman teachers who have been among us for the last three hundred years," etc. *Essays on the Re-union of Christendom*, edited by Rev.\ F.\ G. Lee (Secretary to the A.\ P.\ U.\ C.); with Preface by Dr.\ Pusey, 1867, pp.\ 179\ f.]

Under this fearful and blasphemous system there are properly two grand and fundamental errors from which the rest flow; and which it is important to mark and deal with separately, although they are intimately connected, and form part of the same revolting theory of the Sacrament. There is, first of all, that supernatural change alleged to be wrought upon the elements by the authority of the priest in uttering the words of institution,—the transubstantiation properly so called,—by which the bread and wine become not a sign or symbol, but the actual substance of the crucified Saviour; and there is, secondly, and in consequence of such transubstantiation, the making of the elements not the signs of Christ's sacrifice, but the reality of it,—the bread and wine having become Christ Himself, and the priest having, in so transubstantiating them, actually made the sacrifice of the Cross once more, and offered it to God. These two doctrines of real transubstantiation, and a real sacrifice in the ordinance of the Supper, are both avowed as fundamental in the theory of the Church of Rome; and from these two doctrines all the others connected with the subject are derived. *First*, From the doctrine of the transubstantiation of the elements into the actual humanity and Divinity of the Lord Jesus Christ, there very obviously, and perhaps not unnaturally, follows that other doctrine, which declares that the elements are proper objects for the worship of Christians; and hence we have the elevation and adoration of the Host in connection with the Romanist doctrine of the Supper.[^03.02.02] *Second*, From the doctrine that the elements, transubstantiated into a crucified Saviour, become a real sacrifice, and a true repetition or continuation of the offering made upon the Cross, there very obviously and naturally follows that other doctrine, which teaches that the ordinance procures for the participator in it atonement and forgiveness of sin; and hence we have the saving grace infallibly communicated by the Sacrament wherever there is a priest to dispense it, or a soul to be saved by the participation of it. We shall consider, then, the doctrine of the Church of Rome in connection with the Supper, under the twofold aspect of the real transubstantiation alleged to pass upon the elements, and the real sacrifice alleged to be offered in the ordinance. These two points form the grand and essential features of the Romanist theory of this Sacrament; and, separately discussed, will enable us to review all that is of chief importance connected with it.

[^03.02.02]: [An interesting fact regarding John Knox's influence in effecting the change of doctrine as to transubstantiation and adoration of the elements in the English Prayer Book of 1552, as contrasted with that of 1549, is brought out by Laing in his ed. of Knox's Works, vol.\ iii. pp.\ 79\ f. The Scottish Reformer, however, counselled the abandonment of kneeling at the Communion altogether, instead of a mere disavowal of the Popish interpretation of the attitude, p.\ 279. Cf.\ Proctor, *Hist. of Book of Com. Prayer*, pp.\ 30\ ff.]

The doctrine of transubstantiation is thus laid down in the Canons of the Council of Trent: "If any shall deny that in the Sacrament of the most holy Eucharist there is contained truly, really, and substantially the body and blood, together with the soul and Divinity of our Lord Jesus Christ, and so whole Christ, but shall say that He is only in it in sign, or figure, or virtue, let him be accursed." "If any shall say that in the Holy Sacrament of the Eucharist there remains the substance of bread and wine, together with the body and blood of our Lord Jesus Christ, and shall deny that wonderful and singular conversion of the whole substance of the bread into the body, and of the whole substance of the wine into the blood, while only the appearances (species) of bread and wine remain—which conversion the Catholic Church most aptly styles transubstantiation,—let him be accursed." "If any shall say that Christ, as exhibited in the Eucharist, is only spiritually eaten, and not also sacramentally and really, let him be accursed."[^03.02.03]

[^03.02.03]: [*Concilii Trident. Canones et Decreta*]{lang=la}, Sess.\ xiii. can.\ i. ii. viii. [Compare *Lateran*, iv. can.\ i.; *Creed of Pius IV. Super form. jurament.* Percival, *The Roman Schism*, Lond. 1836, pp.\ 132\ f. xlviii.] 

This monstrous and audacious perversion of the doctrine of Scripture by the Church of Rome is founded upon and defended by an appeal to the literal meaning of the words of Scripture in speaking of the ordinance, in contradistinction to the figurative meaning of them. It is on this literal sense of the Scripture language that the only argument of Romanists in support of their system is built; and, over and above an appeal to the bare literalities of the expressions employed, there is not the shadow of a reason that can be alleged in defence of it. "It is impossible for me," says Cardinal Wiseman in his *Lectures on the Principal Doctrines and Practices of the Catholic Church*,—"it is impossible for me, by any commentary or paraphrase that I can make, to render our Saviour's words more explicit, or reduce them to a form more completely expressing the Catholic doctrine than they do themselves: 'This is my body; this is my blood.' The Catholic doctrine teaches that it *was* Christ's body, that it *was* Christ's blood. It would consequently appear as though all we had here to do were simply and exclusively to rest at once on these words, and leave to others to show reason why we should depart from the literal interpretation which we give them."[^03.02.04] Since Romanists, then, take up their position in defence of transubstantiation on the literal construction of the words employed in reference to the ordinance, and on that alone, what is material or essential to the argument is brought within a very narrow compass indeed. That argument may be, and indeed often is, encumbered with much irrelevant matter. But the main and only essential point to be discussed is simply this: Are we bound to interpret the Scripture phraseology employed in connection with the Lord's Supper in a literal sense, as affirming that the true body and blood of Christ are given in the ordinance; or, do the very terms of that phraseology, and the nature of the thing spoken of, compel us to adopt not a literal, but a figurative interpretation? This is evidently the [*status quœstionis*]{lang=la} between the Romanists and their adversaries in reference to the debate about transubstantiation. Romanists never pretend to bring any argument in aid of their theory of the Supper, except the argument of the literal meaning of the sacramental words. This disposed of, there is no other in the least available to defend their position. Is it, then, *possible* to adopt a literal interpretation of the words which Scripture employs to describe the sacramental elements? Is it *competent* to adopt a figurative interpretation? Is it *necessary* to adopt a figurative interpretation? These three questions, fairly answered, will embrace the whole controversy necessary to the discussion of the Romanist dogma of transubstantiation.

[^03.02.04]: Wiseman. *Lect. on the prin. Doct. and Pract. of the Cath. Church*, Lond. 1847, vol.\ ii. p.\ 174. *Reply to Turton*, Lond 1839, p.\ 125. [The position of the advocates of consubstantiation since the days of the Conference of Marburg, has been in this respect precisely identical with the Romanist one. "[Das Subject]{lang=de}," says Thomasius in reference to the words of institution, "[ist natürliches Brod und Wein, das Prädikat aber der natürliche, substantielle Leib, das natürliche, wesenhafte Blut des Herrn, der Leib in dem er leibhaftig vor ihnen sitzt, das Blut welches das Leben dieses seines Leibes ist, und das er zu vergiessen im Begriff steht. .\ .\ .\ . Die Einsetzungsworte sagen nichts davon, dass Brod und Wein Zeichen oder Unterpfänder des Leibes und Blutes Christi seien, sie gestatten auch nicht den Begriff beider umzusetzen in den der Lebenshingabe und Blutvergiessung, und eben so wenig ihn aufzulösen in den des Personlebens des Erlösers, oder des [*Christus cum omnibus suis bonis*]{lang=la}, sie sagen endlich auch nichts von einer [*manducatio spiritualis*]{lang=la}; das Alles sind willkürliche Ausdeutungen oder Eintragungen; sondern einfach und bestimmt bezeichnen sie als die [*res*]{lang=la}, die im heiligen Mahle mitegetheilt und empfangen wird, den Leib und das Blut, und zwar den wesenhaften, stofflichen, natürlichen Leib und das leibliche Blut des Herrn, womit selbstverständlich der münliche Genuss mitausgesagt ist.]{lang=de}"—*Dogmatik*, 3ter\ Th. 2te\ Abth. Erlangen 1861, pp.\ 58, 60. Cf.\ *Form. Concord.* vii.\ 2–40, in Hase, *Lib. Symb.* pp.\ 597–604.]

### [Impossible to adopt a literal interpretation of the sacramental phraseology]

It is impossible to adopt a literal interpretation of the sacramental phraseology; and this is evinced by Romanists themselves, in their own departure from it in the very matter under discussion.

The principle of a strictly literal interpretation of the sacramental language of Scripture is the only principle which furnishes a single plea in favour of the dogma of transubstantiation; and yet the necessities of the language employed compel Romanists to surrender that principle in its application to the very case in which they demand that we shall observe it. The advocate of transubstantiation, by his own practice in the very matter in hand, nullifies his own solitary argument. He demands from us a literal rendering of the Scripture language; and yet in the very same passage of Scripture he is himself forced to adopt a non-literal. Take the words of Luke as he records the first institution of the Supper, and we see at once that in these the Romanist is forced again and again to abandon a literal, and have recourse to a figurative interpretation. "And He took the cup," says the evangelist, describing our Lord's action, "and gave thanks, and said, Take this, and divide it among yourselves." According to the strictly literal method of interpretation advocated and demanded by the Romanist, it was the cup, and not the wine in the cup, that was to be taken and shared by the disciples; and the Romanist is obliged to adopt the non-literal rendering in this case to suit his views of what occurred. Again, we find the inspired historian saying, in reference to what our Lord did, "Likewise also the cup after supper, saying, This cup is the New Testament in my blood,"—language which once more demands that the Romanist shall surrender his literal, and have recourse to a non-literal interpretation, so that he may not identify the vessel in which the wine was contained with the New Covenant, nor transubstantiate the cup into a covenant, but make the one merely a sign or symbol of the other by a figurative use of the language. Once more, the Romanist departs from his principle of a literal interpretation, when the evangelist tells us that Christ spoke of His blood "which *is* shed for you."[^03.02.05] At the moment of the utterance of these words, the shedding of His blood was a future event, to happen some hours afterwards, and not a present one, as the words literally rendered would assert; and, accordingly, the Romanist has no scruple in interpreting it in a non-literal sense, as indeed he is forced to do by the very necessity of the language. Or, take the words of the Apostle Paul in his account of the ordinance of the Supper, which he had, separately from the evangelists, himself received of the Lord. Here, again, we have the same use of terms which no literal interpretation will enable even the Romanist to explain. The apostle, like the evangelist, tells us that the words of our Lord were expressly, "This cup is the New Testament in my blood,"—language which, interpreted upon the principle of strict literality, would identify the vessel containing the wine with the Divine covenant, and which requires, therefore, even in the opinion of the Romanist, to be understood figuratively.[^03.02.06] And, further still, the apostle, *after* the giving of thanks by our Lord, still speaks of the elements, not in language which denotes their transubstantiation, but in terms which plainly declare that they were bread and wine still. "For as often as ye eat *this bread*, and drink *this cup*, ye do shew the Lord's death till He come."[^03.02.07] In this case no literal rendering of these words will be sufficient to reconcile them with the dogma of transubstantiation; and even in supporting that dogma, the Romanist is compelled in this passage to fall back upon an interpretation not literal. We are warranted, then, by the practice of Romanists themselves, in the very case of the sacramental language employed in Scripture, to say that it is not possible to adhere to, or consistently to carry out, a strictly literal interpretation.[^03.02.08]

[^03.02.05]: Luke\ 22:17–20.

[^03.02.06]: Wiseman, *Lectures on the Real Presence*, Lond. 1836, pp.\ 170\ f. *Reply to Dr.\ Turton*, etc. Lond. 1839, pp.\ 239\ f. 262.

[^03.02.07]: 1\ Cor.\ 11:25–26.

[^03.02.08]: Turton, *Rom. Cath. Doct. of the Eucharist Considered*, Camb. 1837, pp.\ 323–326. ["Twa things are necessaire and maun concur to the nature and constitution of a Sacrament, to wit, there maun be *a word*, and there maun be *an element* concurrand—(referring to Augustin's '[accedit verbum ad elementum et fit Sacramentum]{lang=la},' in *Joann.* Tract.\ lxxx.\ 3);—there is not a sect but they grant this. .\ .\ .\ . We by the 'word,' as I have said, understand the hail institution of Christ Jesus,—quhatsoever He said, quhatsoever He did, or commanded to be done,—without eiking, without pairing, without alteration of the meaning or sense of the word. Quhat understandis the Papists by the 'word?' They preach not the institution of Christ, nor takis not the hail institution as He left it; but instead thereof they select and pykis out of His institution four or five words, and they make the hail vertu of the institution to stand in the four or five words; and it maid nocht gif they contented them with thae words, because they are the words of the institution, but they eike to these words, they paire frae the words, and alteris the meaning of these same words quhilk they keep as they please."—Bruce, *Serm. on the Sacr.* Wodrow Soc.\ ed. p.\ 74. Stillingfleet, *Doct. and Pract. of the Church of Rome*, Cunningham's\ ed. pp.\ 59–61. 70\ f. Goode, *Nat. of Christ's Pres. in the Euch.* vol.\ i. pp.\ 66, 71–80.]

### A figurative interpretation of the sacramental language is perfectly competent and possible.

It cannot be denied—and we have no occasion or wish to deny it—that, as a general canon of interpretation, it is true that the literal rendering of any statement made by a writer ought, in the first instance, to be tried and to be adopted, if it be in accordance with the use of words and the import and object of the statement. But the necessities and use of language justify and demand a figurative interpretation of terms, rather than a literal, in manifold instances; and those instances in which words are to be rendered not literally, but figuratively, must plainly be determined by the nature, connection, and object of the words. Now, in reference to the use of the sacramental language found in the Bible, it has often been argued, and has never yet been fairly met by the advocates of a literal meaning, that many similar passages are to be found in Scripture in which the same words admit of, and indeed require, not a literal, but a figurative interpretation, by the confession of all parties; and the conclusion is drawn from this, and fairly drawn, that the terms used in regard to the ordinance of the Supper may be figurative too. The occurrence of such texts, demanding, as all parties allow, a figurative or non-literal rendering, is valid and relevant evidence in regard to the nature of Scripture language, and proves at least this, that the words employed in reference to the Supper *may* admit of a figurative rendering also. This citation of parallel language does not in itself, indeed, demonstrate that the sacramental terms *must* be figurative; but it unquestionably proves that they *may* be figurative. Cardinal Wiseman, in his discussion of the doctrine of transubstantiation, gives a list of some texts bearing on the question, which have been referred to by Protestants as evidence in their favour, to the effect that the language, "This is my body," "this is my blood," may be understood, not literally, but figuratively. They are to the following effect:

"The seven good kine are seven years."\
"The ten horns are ten kings."\
"The field is the world."\
"And that rock was Christ."\
"For these are the two covenants."\
"The seven stars are the angels of the seven churches."\
"I am the door."\
"I am the true vine."\
"This is my covenant between me and you."\
"It is the Lord's passover."[^03.02.09]

[^03.02.09]: Gen.\ 41:26–27; Dan.\ 7:24; Matt.\ 13:38–39; 1\ Cor.\ 10:4; Gal.\ 4:24; Rev.\ 1:20; John\ 10:7; 15:1; Gen.\ 17:10; Exod.\ 12:11.

In these instances, and many similar ones, it is admitted by all parties, Romanists as well as Protestants, that the verb *to\ be* must be understood in its non-literal signification, and cannot by any possibility be understood literally. From the nature of the assertion made, from the context, and from the manner in which the terms are made use of, there is no possibility of denying that these texts are to be understood not literally, but figuratively; and they seem, therefore, by this parallelism to the words employed in connection with the Supper, to prove all that they were ever quoted to prove, namely, that the expressions, "This is my body," "this is my blood," *may* be understood in a figurative sense too. Such texts are not quoted to demonstrate that the sacramental phraseology of Scripture *must* be figurative; they are only quoted to prove that there is nothing in the nature of Scripture language, judging by its use in similar cases, to prevent us, if the nature of the statement and the context should require it, from interpreting the language concerning the Supper in a non-literal or figurative sense also. The multitude of texts closely analogous in form to the phrases, "This is my body," "this is my blood," and which, as all parties allow, *must* be understood figuratively, may not indeed, taken singly, necessitate a non-literal rendering in the latter case also; but they, at the very least, authorize it, should the import and connection of the passage make the demand, if they do not go a step further, and of themselves recommend a figurative interpretation.

Now, how is it that Cardinal Wiseman in his *Lectures* deals with these passages, and disposes of the argument drawn from them? He bestows a vast deal of minute criticism upon them, in order to show that these passages must, either from the meaning of the statement made in each, or the sense of the context, or the express assertion of the sacred writer, be accounted figurative and symbolical; and that, therefore, the verb *to\ be* in each of these cases must be reckoned equivalent to the verb *to\ signify*. And having done this, he considers he has done enough to prove that the cases referred to are not parallel to the sacramental language, "This is my body," "this is my blood." Now, it is enough, in reference to such an argument, to say that we willingly adopt his explanation of these passages, accounting them, as he does, to be figurative, and reckoning, as he does, the verb *to\ be*, when employed in such texts, as equivalent to the verb *to\ signify*. And it is for this very reason that we quote them as a justification of our assertion, that the same verb, when employed in reference to the Lord's Supper, *may* be equivalent there also to the verb *to\ signify*. If these texts did not admit of a figurative interpretation, and if the verb *to\ be* did not in them appear equivalent to the verb *to\ signify*, we should not have quoted them, because they would not have served our purpose. The reasoning of the Cardinal is certainly a singular specimen of an attempt at logical argument. I shall give it in his own words: "Suppose," says he in his *Lectures*, "suppose I wish to illustrate one of these passages by another, I should say this text, 'The seven kine are seven years,' is parallel with 'The field is the world,' and both of them with the phrase, 'These are the two covenants;' and I can illustrate them by one another. And why? Because in every one of them the *same thing* exists; that is to say, in every one of these passages there is the interpretation of an allegorical teaching,—a vision in the one, a parable in the second, and an allegory in the third. I do not put them into one class because they all contain the verb *to\ be*, but because they all contain the same thing. They speak of something mystical and typical,—the interpretation of a dream, an allegory, and a parable. Therefore, having ascertained that in one of these the verb *to\ be* means *to\ represent*, I conclude that it has the same sense in the others; and I frame a general rule, that wherever such symbolical teaching occurs, these verbs are synonymous. When, therefore, you tell me that 'this is my body' may mean 'this represents my body,' because in those passages the same word occurs with this sense, I must, in like manner, ascertain not only that the word *to\ be* is common to the text, but that the same thing is to be found in it as in them; in other words, that in the forms of institution there was given the *explanation of some symbol*, such as the interpretation of a vision, a parable, or a prophecy .\ .\ . Until you have done this, you have no right to consider them all as parallel, or to interpret it by them."[^03.02.10]

[^03.02.10]: Wiseman, vol.\ ii. p.\ 186.

The objection here urged by Cardinal Wiseman seems to amount to this, that we have quoted passages which, by the nature of the statement they contain, or by the context, or by the direct assertion of the writer, are plainly demonstrated to be figurative, while the sacramental expressions, "This is my body," "this is my blood," are not so demonstrated to be figurative. The answer is obvious. We do not quote such texts to prove that the terms of the sacramental institution *must* be understood figuratively, but to prove that they *may* be understood figuratively; to demonstrate that there is no bar in the shape of Scripture usage in the way to prevent us from interpreting them figuratively, if it is necessary. We are prepared to prove, by the very same means as the Cardinal employs,—by the nature of the statement itself, by the context, and such like considerations,—that the sacramental terms are figurative, just as Cardinal Wiseman proves that the words, "This cup is the New Testament," are to be understood figuratively, or as these other terms, "The seven kine are seven years," must be interpreted figuratively. The very nature of the statement itself proves it to be a statement to be understood, not in a literal, but a figurative sense. We interpret the expression, "The seven kine are seven years," in a figurative sense, not because these words occur in the interpretation of a dream,—for both the dream and the interpretation may be embodied in words, literal, and not figurative,—but because the very nature of the proposition and the sense of the context necessitate it, it being impossible that the seven kine can be literally seven years. Again, we interpret, and so does Cardinal Wiseman, the expression, "This cup is the New Testament," not literally, but figuratively, for a similar reason,—that the very nature of the proposition, and the sense of the context, demand a non-literal rendering; and in like manner we interpret the expression, "This is my body," "this is my blood," not literally, but figuratively, for the very same reason, because the very nature of the proposition, and the sense of the context, necessitate such an interpretation.[^03.02.11] The citation of other passages of Scripture in which the verb *to\ be* is used for the verb *to\ represent* or *signify*, is had recourse to in the argument simply to prove that the usage of Scripture language does not forbid, but countenances such a kind of interpretation. And the numerous texts already referred to are both relevant and sufficient to accomplish that object.[^03.02.12]

[^03.02.11]: ["[Diess [τουτο]{lang=el}]{lang=de}," says Meyer, commenting on 1\ Cor.\ 11:24, "[kann gar nichts anderes heissen als; *diess gebrochene Brod da*, und damit ist [εστι]{lang=el} als die Copula des symbolischen Seins zu fassen *geboten*.]{lang=de}" So too, Martensen, representing though he does the High Church Lutheran doctrine of the Sacraments: "[Gegen diese Verwandlungslehre, welche die natürlichen Elemente zu einem leeren Schein verflüchtigt und dem Reiche der Natur zu nahe tritt um das der Gnade zu verherrlichen, protestirt die ganze evangelische Kirche, und behauptet die natürliche Selbstständigkeit der sinnlichen Zeichen. 'Brot ist Brot, und Wein ist Wein,' ist nur Sinnbild vom Leibe und Blute Christi. In diesem Sinne als Verwerfung der Transsubstantiation bekennt sich die ganze evangelische Kirche zu Zwingli's 'diess bedeutet.']{lang=de}"—*Dogmatik*, 4te\ Aufl. p.\ 376.]

[^03.02.12]: Turton, *Rom. Cath. Doct. of the Euch. Considered*, pp.\ 259–288.

### [A figurative interpretation is necessary]

A figurative interpretation of the sacramental language, "This is my body," "this is my blood," is not only possible and competent, but necessary.

In no other way can we ever discriminate between figurative and literal terms, whether scriptural or non-scriptural, whether used by inspired or uninspired men, than by a reference to the nature of the proposition which the language embodies, to the sense of the context, and to the object of the speaker or writer; unless in those exceptional cases in which he directly tells us that he is to be understood in the one way or in the other. Very seldom indeed, in regard to language not meant to deceive, is it difficult to understand, from a consideration of these points, whether it is to be interpreted figuratively or not. In the case of the Lord's Supper, the words employed in reference to the elements could have presented to the disciples who heard them no difficulty at all. The ordinance was grafted upon the passover, with the figurative language and actions of which the Apostles, as Jews, were abundantly familiar; and this circumstance alone must have familiarized their minds with, and prepared them for the figurative meaning of the words and elements in the Supper. Above all, the nature of the proposition, "This is my body," "this is my blood," interpreted by the commentary of our Lord, "This do in remembrance of me," and understood in the light of His accompanying actions and words, renders it nearly impossible that they could believe that a miracle had been wrought on the bread and wine, and that the body and blood, soul and Divinity of the Lord Jesus Christ, then present to their eyes, could be at the same instant contained under the appearance of the morsel of bread and the mouthful of wine that they ate and drank. Nothing but the "strong delusion that believes a lie" can lead any man who reads and understands the simple narrative of Scripture, to deny that the interpretation of the sacramental phraseology employed must be figurative, and not literal.[^03.02.13]

[^03.02.13]: Turton, *ut supra*, pp.\ 289–308.

There are two attempts commonly made by Romanists to explain away the impossibility of the Apostles,—or indeed any other man not wholly blinded by spiritual delusion,—believing in the literal interpretation of the sacramental words that refer to the Supper.

**1st**, The power of Christ to work a miracle, like that which is alleged to have been wrought in the case of the bread and wine, is asserted; and it is averred that the Apostles could not doubt the supernatural ability of their Lord and Master, so often in other days exerted before their eyes. "What," asks Dr.\ Wiseman, "is possible or impossible to God? What is contradictory to His power? Who shall venture to define it further than what may be the obvious, the first, and simplest principle of contradiction,—the existence and simultaneous non-existence of a thing? But who will pretend to say that any ordinary mind would be able to measure this perplexed subject, and to reason thus: 'The Almighty may indeed, for instance, change water into wine, but He cannot change bread into a body?' Who that looks on these two propositions with the eye of an uneducated man, could say that in his mind there was a broad distinction between them, that while he saw one effected by the power of a Being believed by him to be omnipotent, he still held the other to be of a class so widely different as to venture to pronounce it absolutely impossible?. .\ .\ . Now, such as I have described were the minds of the Apostles,—those of illiterate, uncultivated men. They had been accustomed to see Christ perform the most extraordinary works. They had seen Him walking on the water, His body consequently deprived for a time of the usual properties of matter,—of that gravity which, according to the laws of nature, should have caused it to sink. They had seen Him, by His simple word, command the elements and raise the dead to life, etc. Can we, then, believe that with such minds as these, and with such evidences, the Apostles were likely to have words addressed to them by our Saviour, which they were to interpret rightly, only by the reasoning of our opponents,—that is, on the ground of what He asserted being philosophically impossible?"[^03.02.14]

[^03.02.14]: Wiseman, *Lectures*, vol.\ ii. pp.\ 205\ f. [Thomasius, *Dogmatik*, 3ter\ Th. 2te\ Abth. p.\ 61\ f.]

It is hardly necessary to reply to such an argument as this. *In the first place*, the miracles with which the Apostles were familiar had no analogy whatsoever to the stupendous wonder of transubstantiation. Those miracles were appeals to the senses in proof of truths not seen; and they were tested by the senses, as things to be judged of by them all. The so-called miracle of transubstantiation is no appeal to the senses, but the reverse,—a thing not to be tested by the exercise of any one of them, if it were possible, and a thing denied by any one of them, because impossible.[^03.02.15] If it were a possible thing, it would subvert the very principle on which our perceptions are made to us by God the primary source of our beliefs, and the foundation of truth to us; and it would cause the very instincts which His hand has laid deep within our inmost being to be to us a lie. The conversion of water into wine at that marriage supper in Cana of Galilee of old was a wonder seen by the eye, and in agreement with the evidence of the senses, because the properties, first of the water, and afterwards of the wine, were seen and judged of by all. The conversion of the bread into the body of the Lord, while yet the properties of bread remain, is a wonder that contradicts the evidence of our senses, and involves an impossibility.

[^03.02.15]: [Compare Tillotson's famous sermon on the subject.]

*In the second place*, even Cardinal Wiseman himself admits that there are impossibilities in the nature of things, not competent even for Almighty power to accomplish. Such an impossibility, according to his own statement, is the "existence and simultaneous non-existence of a thing;" and side by side with this one limitation, which, upon the authority of Dr.\ Wiseman, is to be put even upon the power of God, we may put another limitation, and that upon higher authority than his: "God cannot deny Himself."[^03.02.16] In that revelation which He has given to us in our instinctive and primary perceptions of sensible things, and in that other revelation which He has given to us in His Word, God, who is the Truth, cannot contradict Himself.[^03.02.17]

[^03.02.16]: 2\ Tim.\ 2:13.

[^03.02.17]: ["Now quhen the Papists are dung out of this fortress (the impossibility of a figurative interpretation), they flee as unhappily to a second, to wit, that God, by His omnipotency, may make the body of Christ baith to be in heaven and in the bread, baith at ae time; *ergo*, say they, it is so. Gif I denied their consequent, they would be weil fashed to prove it; but the question stands not here, quhether God *may\ do* it or not, but the question stands quhether God *will* it or not, or *may* will it or not. And we say, reverently, His majesty may not will it; for suppose it be true that He *may* monie things quhether He will or not, yet it is as true that there are monie things that He may not will: of the quhilk sort this is; and thir are reduced to twa sorts. *First*, He may not will these things that are contrare to His nature, as to be changeable, to decay, and sic others. .\ .\ . *Secondly*, God may not will some things by reason of a presupponed condition, as sic things quhereof He has concluded their coutrair of before: of the quhilk sort is this, quhilk is now controverted. For seeing that God has concluded that all human bodies suld consist of organical parts, and therefore to be comprehended and circumscrived within ae and the awin proper place, and also seeing He has appointed Christ Jesus to have the like body, and that not for ane time, but eternallie, in respect of this determined will, I say, God may not will the contrair now, either to abolish this body quhilk He has appointed to be eternal, either yet to make it at ae time, in respect of ae thing, a body and not a body, quantified and not quantified, finite and infinite, local and not local. For to will thir things quhilk are plain contradicent in themselves He may not, na mair nor it is possible to Him to will a lie." See the remarks which follow on the nature of the miraculous, embodying very much Bishop Butler's view of the question as given in his *Analogy*.—Bruce, *Serm. on the Sacr.* p.\ 86\ f.]

**2d**, An attempt is made by Romanists to identify, as one and the same in principle, the dogma of transubstantiation and what are called the mysteries of revelation. "What," says Cardinal Wiseman, "becomes of the Trinity? What becomes of the incarnation of our Saviour? What of His birth from a virgin? And, in short, what of every mystery of the Christian religion?"[^03.02.18] It will be time enough to answer such questions as these when it is proved that such mysteries contradict our rational nature, in the same manner as the dogma of transubstantiation contradicts our perceptive nature. Such mysteries as those referred to are *above* our reason, but not *against* it. They are *beyond* the powers of our rational nature fully to understand, but not contradictory to our rational nature so as to be inconsistent with it. The argument in defence of transubstantiation, drawn from such a source, is but one example out of many that could be quoted, of the common tactics of Romish controversialists, who are but too often prepared to hand over to the unbeliever the most sacred truths which the Scripture has recorded, rather than not make out a plea for their own superstitions.[^03.02.19]

[^03.02.18]: Wiseman, *Lectures*, vol.\ ii. p.\ 209.

[^03.02.19]: Calvin, *Inst.* lib.\ iv. cap.\ xvii.\ 12–23. Turrettin, *Op.* loc.\ xix. qu.\ xxvii. Jewel, *A Replie unto M.\ Hardinge's Answeare*, Lond. 1565, Art.\ v.–xii. pp.\ 316–477. Cosin, *Hist. of Popish Transubstantiation*, Lond. 1676. Faber, *Christ's Discourse at Capernaum fatal to the Doct. of Transubst.* Lond. 1840. Goode, *Nat. of Christ's Pres. in the Euch.* Lond. 1856, vol.\ i. pp.\ 130–224. [Stillingfleet, *Doct. and Pract. of the Church of Rome*, Edin. 1837, pp.\ 55–77. See especially the full references to the literature of this subject given by Dr.\ Cunningham in his notes to the above work. *Essay on Transubstantiation* in the *Princeton Essays*, 1st\ Series, Edin. 1856, pp.\ 366–385. Bruce, *Serm. on the Sacr.* Wodrow Soc.\ ed. pp.\ 74–96. Reuss, [*Histoire de la Theologie Chrétienne au Siècle Apostolique*]{lang=fr}, 3me\ ed. Strasbourg 1864, tom.\ i. pp.\ 244–246, tom.\ ii. 191\ f.]
